
# Philosophy & Psychology

## The art of loving [Erich Fromm]
### Is love an art?

- Is love an art? Then it requires knowledge and effort. Or is love a pleasant sensation, which to experience is matter of chance, something one "falls into" if one is lucky?

> <span style="color:blue">Hui: The author answered this question in the next Chapter "The Theory of love". he believes love is active not passive; it is a “standing in” not “falling for”; It is practiced by human power in **freedom** never a result of compulsion. What does the “active character of love” mean? It means that love is primarily giving not receiving. In the next chapter, the author will discuss what is giving and what if a person can't give. </span>

- What most people in our culture mean by being lovable is essentially a mixture between being popular and having sex appeal...Our whole culture is based on the appetite for buying, on the idea of mutually favorable exchange...."Attractive" usually means **a nice package of qualities** which are popular and sought after on the **personality market**.

### The theory of love
#### Love, the answer to the problem of human existence

- The experience of separateness arouses anxiety; it is, indeed, the source of all anxiety...The awareness of human separation, without reunion by love--is the source of shame. It is at the same time the source of guilt and anxiety...Man is confronted with the solution of one and the same question: the question of how to overcome separateness, how to achieve union, how to transcend one’s own individual life and find atonement...The answer varies. The question can be answered by animal worship, by human sacrifice or military conquest, by indulgence in luxury, by ascetic renunciation [n. 放弃，脱离关系], by obsessional work, by artistic creation, by the love of God, and by the love of Man...The answer depends, to some extent, on the degree of individuation which an individual has reached...The more the human race emerges from these primary bonds, the more it separates itself from the natural world, the more intense becomes the need to find new ways of escaping separateness.

> <span style="color:blue"> Hui: "Separateness" is a key concept in Erich Fromm's work. In his book "Escape from freedom", Erich said human escape from freedom because they want to escape separateness. He stated three ways of achieving this aim:  </span>

1. In all kinds of orgiastic state...orgiastic union have three characteristics: (1) they are intense, even violent; (2) they occur in the total personality, mind and body; (3) **the unity is transitory**.  

1. Based on **conformity** with the group, its customs, practices and beliefs. It is the most frequent solution chosen by man in the past and in the present. It is **pseudo-unity**.   

1. In creative activity (artist, artisan). In any kind of creative work the creating person unites himself with his material, which represents the world outside of himself. It is **not interpersonal**  

> <span style="color:blue">Hui: In the author's view, all the three are only partial answers to the problem of existence. The full answer is the **interpersonal union by love** which is the most powerful striving in man. Failing to achieve means destruction (self or others).</span>
     
- The **dictatorial system** use threats and terror to induce this conformity; the **democratic countries**, suggestion and propaganda.There is, indeed, one great difference between the two systems...But actually people want to conform to a much higher degree than they are forced to conform, at least in the Western democracies.
     
- **Symbiotic union [共生性结合]**
     1. Biological pattern: mother and foetus, they need each other
     1. Psychic symbiotic union: the two bodies are independent, psychological attachment
     1. Passive form: masochism [ˈma-sə-ˌki-zəm 受虐狂]
     1. Active form: sadism
     
- **Mature love** is union under the condition of _preserving one's integrity, one's individuality_. (contrast to symbiotic union). Two beings become one and yet remain two. 

> <span style="color:blue">Hui: Discussion around "giving":</span>

- Giving is the highest expression of **potency**.
- It is well known that the poor are more willing to give than the rich. Nevertheless, poverty beyond a certain point may make it impossible to give, and is so degrading, not only because of the suffering it causes directly, but because of the fact that **it deprives the poor of the joy of giving**.

> <span style="color:blue">Hui: It reminds me a sentence from the book “Maxims” which says:"What we call liberality is often but the vanity of giving which we like more than that we give away." The word “vanity” has negative connotation here. It is not a graceful motivation to give but it is not bad either. At least people with this mind are willing to give. Only God can see people's mind perfectly. Other than God, who knows what is real under the sun? That is why making judgement about others is dangerous because all we can see is (part of) people’s behavior and you don’t know what are in people’s heart. On the other hand, we are judging all the time since we have to make a decision. I like the analogue saying “human are living on a dial of a clock. We can never open the back to examine how it works. We see what we see and guess the reason." We are too stupid to be complicated. We are just sinful and making each other’s life tough.</span>

- **Love is a power which produces love; impotence is the inability to produce love.**

> <span style="color:blue">Hui: I like this way to describe love and impotence! Being a potent person is to be someone who can produce and give love not just receive. </span>


## Escape from Freedom [逃避自由, Erich Fromm]
### Ch3 现代人的两种自由观念

- 如果我们对于工作缺乏高度的热心以及对积极投资以发挥最高生产力的推进毫无野心，则绝无进步的可能。
- 无资者是受雇于人的，也就是说，他无须顾虑市场问题，无须为营运之好坏担忧，也不必考虑祈求进步的技术问题，这些都是资本家的责任。受雇佣的人，只是默默的遵循。
- 对于这种一面牺牲自我为整个社会的机器献身，另一方面趋于追求自我利益的矛盾，我们如何去协调呢？我们只有从心理上的基本因素才能寻求解答。

## Maxims [La Rochefoucauld, 1613-1680, French]

- The constancy of the wise is only the talent of concealing the agitation of their hearts.
- Neither the sun nor death can be looked at without winking.[直视太阳和死亡，不能不眨眼。]
- If we had no pride we should not complain about that of others.
- _**We have not enough strength to follow all our reason**_
- We are never so happy or so unhappy as we suppose.
- What grace is to the body, good sense is to the mind.[优雅之于身体，犹如良知之于精神。]
- Our distrust of another justifies his deceit.
- In the intercourse of life, we please more by our faults than by our good qualities.
- There are different kinds of curiosity: one springs from interest, which makes us desire to know everything that may be profitable to us; another from pride, which springs from a desire of knowing what others are ignorant of.
- There are relapses in the diseases of the mind as in those of the body; what we call a cure is often no more than an intermission or change of disease. 
- We easily forget those faults which are known only to ourselves.
- **Sovereign ability consists in knowing the value of things.**
- There is great ability in knowing how to conceal one’s ability.
- Interest sets at work all sorts of virtues and vices.
- Humility is often a feigned （\fend\ 假装的）submission which we employ to supplant others. It is one of the devices of pride to lower us to raise us; and truly pride transforms itself in a thousand ways, and is never so well disguised and more able to deceive than when it hides itself under the form of humility. [谦卑往往是一种假装的顺从，人们利用它来排挤掉别人。谦虚还是骄傲的一种诡计，它以退为进，以贬求扬。虽然骄傲形式各异，却没有任何一种能比隐藏在谦卑的形象下更具隐蔽性和欺骗性了。]
- Good taste arises more from judgment than wit. [良好的品味更多来自判断而非理性]
- What we call liberality is often but the vanity of giving which we like more than that we give away. [被称之为“慷慨”，往往不过是赠予者的虚荣心，人们对这种虚荣心花费的心思远远超过自己所赠送出去的东西]
- Absence extinguishes small passions and increases great one as the wind blow out a candle, and blow in a fire.
- Pride, which inspires, often serves to moderate envy. [骄傲，既激起我们对他人的嫉妒心，也不断地帮助我们缓和它。]
- **What commonly hinders us from showing the recesses of our heart to our friends is not the distrust we have of them, but that we have of ourself. [能阻止人们向朋友透露自己内心隐私的，通常不是对朋友的不信任，而是对自己的不信任。]**
- **Weak persons can’t be sincere.**
- **We pardon in the degree that we love.**
- To be a great man one should know how to profit by every phase of fortune. 
- We hardly find any persons of good sense, except those who agree with us.
- The greatest miracle of love is to eradicate flirtation. [爱情的最大奇迹在于它杜绝了调情]
- Ordinary men commonly condemn what is beyond them. 
- The desire of talking about ourselves, and of putting our fault in the light we wish them be seem, forms a great part of our sincerity. [谈论自己和把我们愿给别人看的那些缺点亮出来的欲望，构成了我们的真诚的一大部分]
- A man is often more clever than one other, but not than all others.
- It appears that nature has hidden at the bottom of our hearts talents and abilities unknown to us. It is only the passions that have the power of bringing them to light, and sometimes give us views more true and more perfect than art could possibly do. [本性是潜藏在我们心灵深处的不为我们所知的各种才智和能力，有能力揭开它面纱的只有激情]
-  We reach quite inexperienced the different stages of life, and often, in spite of the number of our years, we lack experience. [我们毫无经验地抵达人生的不同时期，而且无论我们在哪个年龄阶段，我们总是缺少那一时期的经验] "To most men experience is like the stern lights of a ship which illumine only the track it has passed———Coleridge"

- The most dangerous folly of old persons who have been lovable is to forget that they are no longer so. 

> <span style="color:blue">Hui: hope it is not that bad……</span>

- In love the quickest is always the best cure. 
- **Few knows how to be old.**
- Penetration has a spice of divination in it which tickles our vanity more than any other quality of the mind. [洞察力有一副预言家的神奇，它比精神的其它特性都更能满足我们的虚荣心。]
- In the old age of love as in life we still survive for the evils, though no longer for the pleasure.
- **Nothing prevents our being unaffected so much as our desire to seem so.[没有什么比期望看起来不矫揉造作更加矫揉造作的了]**
- However disposed the world may be to judge wrongly, it far often favors false merit than than does justice to true. [无论这个世界如何规划布置，它仍可能是不公平的，它总是宠爱伪善的德行，而非公正地对待真正的德行]
- **There are few women whose charm survives their beauty.**
- It is only people who possess firmness who can possess true gentleness. In those who appear gentle, it is generally only weakness, which is readily converted into harshness.[只有那些拥有坚强力量的人，才能拥有真正的温文尔雅。那些仅仅外表表现为温文尔雅的人，通常不过是软弱而已，并且这种文雅会轻易地转变为粗俗不堪]
- Usually we are more satirical \sə'tɪrɪkl\ from vanity than malice. [一般来说人们的尖酸刻薄主要来自虚荣心而非心怀恶意]
- We have more idleness in the mind than in the body.
- **Quarrels would not last long if the fault was only on one side.**

## The Tibetan Book of Living and Dying [西藏生死书，Sogal Rinpoche]

> <span style="color:blue">Hui: 这本书让你严肃系统的思考死亡，从藏传佛教的角度讲述生死。这本书意在写给西方人看的，结合了中西方思想，时而引入基督教的例子，相对其它佛教书籍更加通俗易懂。书的核心观点是我们从出生的那一刻开始就在准备死亡，好好活着是为了最终能够好好死去。书中指出一切都是无常，看穿我执的虚妄，理解无常，回归本性。虽然对许多地方有疑问，但还是非常推荐这本书。看过之后或许能向不畏死，亦能好好活跨进一步。</span>

### Living [生]

Karma: 业力  
Phowa: 颇瓦法    
Samsara: 轮回世界  
Rigpa: 本觉  
Nangpa: 佛教徒，内省的人  
Luminosity: 觉明  
Wisdom-energy: 智慧能  
Heart-center: 心轮  
Wisdom-channels: 智慧脉  
Karmie winda: 业风  
Prana: 呼吸  

#### In the Mirror of Death [在死亡的镜子中]

- The disastrous effects of the denial of death go far beyond the individual: They affect the whole planet. Believing fundamentally that this life is the only one, modern people have developed no long-term vision. So there is nothing to restrain them from plundering the planet for their own immediate ends and from living in a selfish way that could prove fatal for the future. （否定死亡的可怕影响力，绝不止于个人层面，它影响着整个地球。由于大多数人相信人生就只有这么一世，现代人已经丧失长远的眼光。因此，他们肆无忌惮地为着自己眼前的利益而掠夺地球。）

#### Impermanence [无常]

- To practice death is to practice freedom. A man who has learned how to die has unlearned how to be a slave. [Montaigne]
- Death is a vast mystery, but there are two things we can say about it: (1) It is absolutely certain that we will die; (2) It is uncertain when or how we will die.
- Why do we live in such terror of death? Because our instinctive desire is to live and to go on living, and death is a savage end to everything we hold familiar.
- Perhaps the deepest reason why we are afraid of death is because we do not know who we are.
- Without our familiar props, we are faced with just ourselves, **a person we do not know, an unnerving stranger with whom we have been living all the time but we never really want to meet**.

> <span style="color:blue">Hui: 我们被各种各样的刺激、快感催眠(hypnotize)，生活渐渐沦为手段淹没目的的过程。不知道自己是谁，不知道为什么活着。</span>

- Just look at your mind for a few minutes. You will see that it is like a flea, constantly hopping to and fro. 
- The birth of a man is the birth of his sorrow. The longer he lives, the more stupid he becomes, because his anxiety to avoid unavoidable death becomes more and more acute. What bitterness! He lives for what is always out of reach! His thirst for survival in the future makes him incapable of living in the present. (人之生也，与忧俱生。寿者昏昏，久忧不死。何苦也！其为形也，亦远矣！《庄子至乐篇》)
- Our lives are monotonous, petty, and repetitive, wasted in the pursuit of the trivial, because we seem to know of nothing better.....The pace of our lives is so hectic that the last thing we have time to think of is death. 
- As a Tibetan saying goes:"Tomorrow or the next life, which comes first, we never know."
- Discipline is to do what is appropriate or just; that is, in an excessively complicated age, to simplify our lives......the only serious goals in life are **"learning to love other people and acquiring knowledge(学习爱别人和获得知识)"**......**Whatever we have done with our lives makes us what we are when we die.(我们一生的所作所为，造就了我们去世时的模样。)** And everything, **absolutely everything counts**.
- In our minds changes always equal loss and suffering. And if they come, we try to anesthetize ourselves as far as possible. We assume that permanence provides security and impermanence does not. (我们害怕变化)
- The past is past, the future not yet risen, and even the present thought, as we experience it, becomes the past. The only thing we really have is now......Has my understanding of death and impermanence become so keen and so urgent that I am devoting every second to the pursuit of enlightenment?

#### Reflection and Changes [反省与改变]

- There is one way, and one way only, out of samsara's ceaseless round of birth and death, which is the path to liberation.
- Those with dualistic perception（分别心） regard suffering as happiness, like they who lick the honey from a razor edge.
- We may idealize freedom, but when it comes to our habits, we are completely enslaved.
- Learning to live is learning to let go.
- There is nothing wrong with the desire to be happy, but what we grasp on to is by nature ungraspable. The Tibetans say you cannot wash the same dirty hand twice in the same running river, and, "No matter how much you squeeze a handful of sand, you will never get oil out of it."
- How can we work to overcome attachment? Only by realizing its impermanent nature; this realization slowly releases us from its grip. 

> <span style="color:blue">Hui: understand and accept uncertainty. being mortal</span>

- Nothing has any **inherent** existence of its own when you really look at it, and this absence of independent existence is what we call "emptiness".

> <span style="color:blue">Hui: It reminds me the beginning of Ecclesiastes.   
**[Ecclesiastes 1:2-10]** "Everything is meaningless", says the Teacher, "completely meaningless!" What do people get for all their hard work under the sun? Generations come and generations go, but the earth never changes. The sun rises and the sun sets, then hurries around to rise again. The wind blows south, and then turns north. Around and around it goes, blowing in circles. Rivers run into the sea, but the sea is never full. Then the water returns again to the rivers and flows out again to the sea. No matter how much we see, we are never satisfied. No matter how much we hear, we are not content. History merely repeats itself. It has all been done before. Nothing under the sun is truly new. Sometimes people say, "Here is something new!" But actually it is old; nothing is ever truly new.</span>

- Always recognize the dreamlike qualities of life and reduce attachment and aversion. (认知生命有如梦幻，减少执著和嗔怨)

> <span style="color:blue">Hui: 无所不有是**全**，一无所有是**空**。全是面子，空是里子。什么都是也就无所谓是什么，等于什么都不是，意识到这一点，就可以放下了。</span>

#### The Nature of Mind[心性]
- "the homage of the View" It is a devotion that springs spontaneously from seeing the View of the nature of mind.(“知见皈依”这是从看到心性的知见而当下产生的恭敬心。)
- **Life and death are in the mind, and nowhere else.**

> <span style="color:blue">Hui: It resonates what Bible says. Jesus came to show us the way, teach us the truth and invite us to find life. As Jesus said to the Samaritan woman:"Anyone who drinks this water will soon become thirsty again. But those who drink the water I give will never be thirsty again. It becomes a fresh, bubbling spring within them, giving them eternal life." Indeed, life and death depend on your mind, your faith. </span>

- There are many aspects to the mind, but two stand out.   
     1. Ordinary mind, called by the Tibetans _sem_. One master defines it:"That which possesses discriminating awareness, that which possesses a sense of duality--which grasps or rejects something external--that is mind. Fundamentally it is that which can associate with an 'other'--with any 'something', that is perceived as different from the perceiver."(凡夫心，分别，相对心)
     1. Then there is the very nature of mind, its innermost essence, which is absolutely and always untouched by change or death. At present it is hidden within our own mind, our _sem_, enveloped and obscured by the mental scurry of our thoughts and emotions.(本性，心的底蕴，不受凡夫心影响。)
- The nature of mind is the very root itself of understanding. In Tibetan we call it _Rigpa_, a primordial, pure, pristine awareness that is at once intelligent, cognizant, radiant, and always awake. It could be said to be the knowledge of knowledge itself. (心性是了解的基础。)
- When a much larger number of people know the nature of their minds, they'll know also the glorious nature of the world they are in, and struggle urgently and bravely to preserve it. It's interesting that the word for "Buddhist" in Tibetan is _nangpa_. It means "insider-er": someone who seeks the truth not outside, but within the nature of mind.
- The central truth of Buddha's teaching: that we are all already essentially perfect.

> <span style="color:blue">Hui: I don't agree that we are already essentially perfect.</span>

#### Bringing the Mind Home [把心带回家]
- In fact, we are already perfectly trained by and for samsara, trained to get jealous, trained to grasp, trained to be anxious and sad and desperate and greedy, trained to react angrily to whatever provokes us. We are trained, in fact, to such an extent that these negative emotions rise spontaneously, without our even trying to generate them. 
- We will find that with time, patience, discipline and the right training, our mind will begin to unknot itself and know its essential bliss and clarity. [只有有耐心，纪律和正确的训练，我们的心将开始解开它自己的结，并认识它自己本有的喜悦和清明]
- Because from the mind are derived all fears and immeasurable sorrows.
- We are fragmented into so many different aspects. We don't  know who we really are, or what aspects of ourselves we should identify with or believe in. So many contradictory voices, dictates, and feelings fight for control over our inner lives that we find ourselves scattered everywhere, in all directions, leaving nobody at home.Meditation is **bringing the mind home**.
- Three things make all the difference between your meditation being merely a way of bringing temporary relaxation, peace, and bliss or of becoming a powerful cause for your enlightenment and the enlightenment of others:
      1. **Good in the Beginning:** springs from the awareness that we can all sentient Beings fundamentally have the buddha nature as our innermost essence, and that to realize it is to free of **ignorance** and to put an end, finally, to **suffering**. [believe in the equality of all beings]
      1. **Good in the Middle:** frame of mind with which we enter into the heart of the practice, one inspired by the realization of the nature of mind, from which arises an attitude of non-grasping, free of any conceptual reference whatsoever, and an awareness that all things are inherently "empty", illusory, and dream-like.
      1. **Good at the End:** the way in which we bring our meditation to a close by dedicating all its merit and praying with real fervor......Merit is the positive power and benefit, the peace and happiness that radiate from your practice.

- Three sacred principles make meditation truly enlightening and powerful:
     1. the skillful motivation [善巧的动机]
     1. the attitude of non-grasping that secures the practice [让修行成功的不执着的态度]
     1. the dedication that seals it [结束时的回向]
- The practice of mindfulness, of bringing the scattered mind home, and so of bringing the different aspects of our being into focus, is called "Peacefully Remaining" or "Calm Abiding" which accomplishes three things:
     1. all the fragmented aspects of ourselves, which have been at war, settle and dissolve and become friends. In that settling we begin to understand ourselves more, and sometimes even have glimpses of the radiance of our fundamental nature.[自己被撕裂成碎片的所有部分，过去一直都处在战争之中，现在则安住而定下来，而溶化，而变成朋友。在那种安定之中，我们开始了解自己，有时候甚至还可瞥见自性的光芒。]
     1. the practice of mindfulness defuses our negativity, aggression, and turbulent emotions, which may have been gathering power over many lifetimes. [正念的修行可以舒缓我们多生多世以来所累积的负面心侵略性和混乱情绪。] 
     1. this practice unveils and reveals your essential Good Heart, because it dissolves and removes the unkindness or harm in you. [这种修行揭开并显露出你根本的善心，因为它消除了你心中的仇恨或伤害。]
- To _release_ means to release mind from its prison of grasping, since you recognize that all pain and fear and distress arise from the craving of the grasping mind.
- meditation is nothing other than getting used to the practice of meditation.
- The mantra "Om Ah Hung Benza Guru Pema Siddi Hung" is uniquely powerful for peace, healing, transformation and protection in this violent, chaotic age. 
- There is a famous saying:"_If the mind is not contrived, it is spontaneously blissful, just as water, when not agitate, is by nature transparent and clear._"

> <span style="color:blue">Hui: But why is human heart so easily disturbed? we are BORN WITH SIN!</span>

- In meditation, as in all arts, there has to be a delicate balance between relaxation and alertness.
- Ancient meditation instructions:
     1. at the beginning thoughts will arrive one on top of another, uninterrupted
     1. steep mountain waterfall
     1. water in a deep narrow gorge
     1. still and placid ocean ruffled by only the occasional ripple or wave

- So have a spacious, open and compassionate attitude toward your thoughts and emotions, because in fact your thoughts are your family, the family of your mind......thoughts are like the wind; they come and go. The secret is not to "think" about thoughts, but to allow them to flow through the mind, while keeping your mind free of afterthoughts......there is gap between each thought......the Rigpa, the nature of mind in revealed in the gap. So the work of meditation is to allow thoughts to **slow down**, to **make that gap become more and more apparent**.
- Traditionally it's said that for a real practitioner, it's not the negative experiences but the good ones that bring obstacles.
- Then after meditation, it's important not to give in to the tendency we have to solidify the way we perceive things. When you do reenter everyday life, let the wisdom, insight, compassion, humor, fluidity, spaciousness, and detachment that meditation brought you pervade your day-to-day experience. (在禅修之后，不要回到我们易于将事物固化的习气。当你重新进入日常生活时，要让禅修所带给你的智慧、洞察力、慈悲、幽默、柔软、旷达和自在充满你每天的生活经验。)
- When I eat, I eat; When I sleep, I sleep. (这就是禅修)
- Meditation is an art and you should bring to it an artist's delight and fertility of invention.....Be alert for any sign of beauty or grace.

#### Evolution, Karma, and Rebirth [演化、业与轮回]

Shelley 雪莱  
Balzac 巴尔扎克  
Voltaire 伏尔泰  

- How much would it help us, I sometimes wonder, if we did remember them? Couldn't that just confuse us even more?
- Dalai Lama: " _**The basis on which Buddhists accept the concept of rebirth is principally the continuity of consciousness.**_ "

## On the Old Age [论老年, Marcus Tullius Cicero]

- 最适合老年的养身之道莫过于研究学问和培养美德，一个人随时注意培养美德，在他度过漫长的一生时，便会收到惊人的结果。
- 当我认真思考老年为什么被认为是不幸的时候，我想出了四条理由：
     1. 老年使人退出事业
     1. 老年使人失去感官娱乐
     1. 老年使人身体朽弱
     1. 老年离死期不远
- 成就伟大事业有时不是靠气力、速度和灵巧，而是靠思想、威望和判断力。
- 有什么长处就好好利用，没有，也不要叹息；否则青年就该叹息少年的消逝，成年就该叹息青春的消逝了。生命的途径是固定的，**自然的道路是惟一的，单向的，生命的每一个阶段自有与其相对应的特性**：童年软弱，青年狂妄，中年严厉，老年成熟，所有这些都是自然的属性，每一种特性分别属于与其相对应的生命时期。
- 谁也不能怀疑，只要一个人沉湎于享乐之中，他是不可能运用他的智能的，凡事需要思索、考虑的事他都不可能去做。
- 姑且认为青年更能享受那些娱乐，但正如我们所说的，首先，他们是在享受没有价值的东西；其次，老年虽然不强烈追求，但也不是完全不能享受。一个人的心灵若能在战胜情欲、野心、斗争、仇恨以及一切贪欲之后获得自有，或如常言说的获得解脱，该是多好啊！如果一个人真能做到求得知识和学问如同获得事物一般，那么没有什么比闲逸的老年时期更令人愉快的了。
- 人死的时候也许有某种感觉，不过也是转瞬即逝，或者感觉快乐，或是毫无感觉。但是从青年时期起就要对死有这种认识，这样才能蔑视死亡；没有这种认识，便不会有宁静的心境，因为每个人都是要死的。死亡随时都可能降临。一个人害怕死亡，他的心怎能平静呢？......**贪求一切的人才贪生**。
- 当我们被禁锢在这肉体的躯壳里的时候，我们是在尽某种必尽的责任，完成某种劳苦的工作，因为灵魂本是来自天上，它从最高的居所降落下来后，好似沉沦于大地，沉沦于这个与其神圣天性相悖的地方。
- 你们肯定注意到，没有什么比死更像睡眠了。人睡着的时候灵魂最能表现它神圣的本质；当灵魂自由自在，不受桎梏的时候，它能预见许多未来的事情，由此可见，在灵魂完全摆脱肉体的束缚之后，它该是什么样子。
- 既然我们并非注定不死，那么到时候死去便是很好的事，因为自然像对待其他事物一样，也为生命规定了期限。有如戏剧，老年是人生的最后一幕，在我们活够了的时候，我们应该避免继续活下去，以免对生活感到厌倦。

## On the Friendship [论友谊, Marcus Tullius Cicero]

- 我们降生于世，相互便处于一种联系之中，并且彼此越接近，这种关系也越密切。由此，本国人便比外国人亲近，亲属间便比非亲属间亲近。自然本身让人们与常相接近的人之间产生友谊，不过这种友谊不是很稳固的。实际上，友谊在这里胜过亲属关系，因为亲属关系中可能没有情谊，而友谊中则不能没有它，因为如果没有情谊，真正意义上的友谊便不可能存在，而亲属关系却仍然保持。
- 再如若是我们偶然发现某人的品行和性格和我们相合，我们便会明显对他产生一种爱意，因为我们觉得似乎在他身上看到某种正直和美德的光辉。
- 预防和避免这一切过错和不愉快的惟一有效手段是不要很快就开始表露自己的敬爱之情，或者很快就敬爱一个不值得敬爱的人。只有那些本身具备令人敬爱的品质的人才值得缔结友谊。这样的人很少！一切美好的东西都是稀少的，而且没有什么比找到一个自身在各方面都完美无缺的东西更困难。......**合理的是首先自己做一个高尚的人，然后再寻找与自己相似的朋友。......对一个人应该先判断，然后爱；而非先爱，然后判断。**
- 假设让一个人升上天空，让他看到宇宙的盛景和群星的璀璨，但这一惊人的壮观并不会令他愉快，只有他找到一个人述说后，他才会感到快乐。

## On the Immortality of the Soul [论灵魂, Marcus Tullius Cicero]

- 荣誉滋养艺术，声名激励每个人去从事它们，**任何东西凡不受人重视，总是处于可怜的状态。**

## On the Laws [Cicero Marcus Tullius]
## On the Nature of the Gods [Cicero Marcus Tullius]


## An Insight of Chung-yung [中庸洞见]
## 推理的迷宫 [Labyrinths  of Reason, William Poundstone]

## Gravity and Grace [重负与神恩, Simone Weil] 


> <span style="color:blue">Hui: 这是我在2012年读的一本书，书很薄但很实，没有废话。Weil认为，不幸是绝对的。人的存在的不幸是无法消除的。她尖锐的地指出任何社会形态——哪怕是最近完美的社会形态都不能消除人的不幸，不幸不同于不义，所以革命不能代替人的救赎，而只能掩盖不幸，忽略看轻人的不幸，这也就是柏拉图所谓的猛兽式的社会性残忍。“爱是一种神圣的东西。若深入内心，就会将它撕裂。人心被创造出来就是供撕裂的。当它被其它东西撕裂时，就是最可悲的浪费。但它宁可被其它东西撕裂而不是被神圣的爱。因为神圣的爱只撕裂自愿被撕裂的心。这种自愿是困难的。”从一个基督徒的角度，我对这句话的理解是我们只有摒弃过去的自己（也就是所谓的撕裂），将自己交给神，相信神，才能得到永恒的神恩。神恩的翻译是Grace，我及其喜欢这个关于Grace的定义： “Grace is God's kindness, his love, his care, his work on our behalf, his blessings, his gifts, his goodness, his forgiveness, and his salvation. But it is more than that--it is all these things **when they are undeserved**, when they are **pure gift**”.   只有来自神恩的爱才能够改变我们，改变接受神恩的人，也改变了这些接受神恩后向其他人传递神恩的人。为什么放弃原来那个自己那么困难？因为骄傲，我们放不下内心的骄傲，便无法接受神的恩典。这种放下和自愿被撕裂当然是困难的，否则神恩来的太便宜了。    
此外，作者认为包含真理的思想存在于不同的宗教经典，文学与科学著作中，真理遵循不同的途径显示在人们的精神中。比如希腊几何学和诗歌，中国的道教，埃及的俄赛里斯教，印度佛经等，都融合了圣经所包含的真理。</span>

- 两种力量主宰着宇宙：光(light)和重力(gravity)。重负，一般地说，人们期待他人的事是我们身上的重负效果决定的；人们从他人那里得到的由他人身上重负效果所决定。**为何一旦有人表示有一点，或非常需要别人时，别人会选择远离？重负所致。** 灵魂的一切自然的运动受物质万有引力一类的规律制约。唯有神恩例外。

> <span style="color:blue">Hui: 神的爱是无条件的。</span>

- 在这种情况下，我至少由有好几次忍不住说出伤人之语。向重负屈服了。这是大逆不道。话语的功能就是如此被滥用，话语是用来表达事物关系的。
- 伤害他人，就是要从中得到什么。得到什么呢？当伤害他人时，赢得了什么？人们扩展了自己。发展了自己。在他人身上建立虚无以填平自身的虚无。
- 若想到上帝不存在而爱上帝，他将会显示他的存在。

> <span style="color:blue">Hui: 我们对上帝的爱也需要是无条件的。</span>

- 一切虚空，（不被接受）产生仇恨、刻薄、苦涩、积怨。人们盼望自己所恨的遭到恶报，以及人们想象的饿恶重建起了平衡。
- 创造是一种矮的行为，它是永久的。我们存在的每时每刻都是上帝对我们的爱。但上帝只能爱自己。他对我们的爱是通过我们去爱他自己。因此，是他赋予我们存在，他爱我们而甘愿不存在。......我们的存在只是由于他的期待，由于我们不同意不存在造成的他永久地向我们乞求他赋予我们的这个存在。他把存在给予我们是为了向我们乞求它。......正是上帝出自爱而离开我们，以便我们能爱他。因为倘若我们直接沐浴在他的爱的辉映下而没有空间、时间和物质的掩护，我们就会像阳光中的水一样蒸发掉；我们就不会有足够的我可以为了爱而放弃那个“我”。
- 只要我们尚未明白我们有底，我们便是无底的桶。......我们只拥有自己弃绝的东西。人们失去了自己不愿意弃绝的东西。在此意义上，不经由上帝，人们便不能拥有任何东西。
- 上帝并不仅只有一次使自己成为血肉，他每天都使自己成为物以共给人，供人食用。反之亦然，人由于劳累，不幸和死亡而成为物，并被上帝食用。怎么能拒绝这种相互性？
- 因为不幸的伤口和不幸所引起的屈辱使人认识人间疾苦，这种认识乃是一切智慧之门。
- 人的生命中只有两个完美的赤裸和纯洁的时刻：出生和死亡。
- 在没有我们的情况下创造了我们的人并不会在没有我们的情况下拯救我们——Saint Augustine  
幕，就是人的苦难：甚至对于基督也有帷幕。......扎根于漂泊不定之中。
- 我身上具有的精力，天赋等等，又有何用？我受够了，可以消失了。......当我在某处时，我的呼吸，我的心跳，会玷污天上和地下的宁静。
- 必然的两面：行使必然和承受必然。阳光(sunshine)和十字架(cross)。......服从必然而非服从束缚。......行为是天平的指针。不应触碰指针，而是触碰砝码。......惟有完全的超脱才能使人透过骗人的价值的迷雾看到赤裸的事物。

> <span style="color:blue">Hui: 如何完全超脱呢？</span>

- 我们接受在我们面前显现的虚假的价值，当我们认为在行动时，实际上我们静止未动，因为我们依然处在同样的价值体系中。......有关尘世事物的错觉并不涉及其存在，而是其价值。
- 我们身上源于撒旦的东西便是想象。

> <span style="color:blue">Hui: I don't understand it.</span>

- 期限，对于文明来说是以世纪计数，对于个人来说是以年，数十年计数，它具有一种不适者消亡的达尔文式的功能。
- 在屈辱中，傲慢使内在的谎言越来越大。......所有无价值的东西都逃避光照。在尘世，人可以借肉体隐藏自身。死后就办不到了。人就赤裸裸地把自己交付给光照。

> <span style="color:blue">Hui: 和西藏生死书里的观点类似。</span>

- 人们不可能面对面见到上帝而不死，但人们并不愿死。......肉体并非是使我们远离上帝的东西，它是我们遮在面前的帷幕以在我们和上帝之间制造屏障。

> <span style="color:blue">Hui: 人一边说爱着上帝，要追随上帝，一边却又紧紧抓住尘世的光阴。我至今也不明白为什么。或许在活着的时候就是为了要努力的修行，使我们能够在死时见到上帝而不逃离，抓住那光明，并且于光明同在。所以我们在准备，一直在准备，我们抓住尘世，是因为觉得自己还没有准备好。</span>

- 渴望躲避孤独是一种胆怯行为。......模仿上帝是一种不良企图。
- 恶，当人们身处恶中时它并不被感知为恶，而是被感知为必然性或者责任。
- 只有在无望使距离的意识变得无法容忍并且将痛苦转变为仇恨时，相应的犯罪才会产生。
- 人们无法注视人可能做的恶和可能承受的恶的规模而不感到恐惧。......只有处在他人无法再伤害我们的境地时，我们才可能厌恶对他人造成伤害（于是爱他人就像爱过去的自己一样是有限的）

> <span style="color:blue">Hui: 非常喜欢这两句</span>

- 若这世上没有不幸，我们会以为自己在天堂。有一种不幸是：人们无力承受它延续下去，也无力从中摆脱出来。......有两种想法会减轻一点不幸。一是不幸即可就会停止，另一种不幸永不止息。
- 苦难，教育和转化。被授予宗教奥义者不应是学到些什么，而是在他们自身实现某种转化，这种转化使他们能接受教育。
- 必须通过快乐，拥有了真实的揭示才能在痛苦中获得真实。否则，生活只是一场或深或浅的噩梦。......必须在虚无和虚空的困难中努力找到更为充实的现实。同样，应当热爱生活以更加热爱死亡。
- 战争和情欲是人中间的两大幻想和谎言之源。两者的混合是最大的不纯。
- 基督治愈残疾者，使死者复活等等，这些是他使命中不足道的、人间的、几乎卑下的部分。基督的使命的超自然部分，则是血泪，是抚慰人的愿望并未实现，是祈求得到宽容，是被上帝抛弃的感情。......“My God, my God, why have you abandoned me? 我的上帝，我的上帝，你为何离弃我？”这就是基督成为某种神圣东西的明证。
- 穿过时间和空间的无限厚度，上帝为找到灵魂并诱惑它而精疲力竭。如果灵魂表示了纯净而全面的赞同，即使是闪电般的一瞬间，上帝便政府了灵魂。当灵魂变成完全归于他的东西时，上帝便抛弃它。他让灵魂孤身独处。轮到灵魂穿过时间和空间的无限厚度，摸索寻找灵魂所爱者。就这样，灵魂从相反方面重做上帝朝它而来的旅行。这就是十字架。
- 基督的仁慈宽厚，就是上帝与造物之间的距离。......中介的功能，在其自身，意味着左右为难。
- 上帝把自己奉献给人，作为强大无比者或者作为完美无缺者——由人自己选择。
- 基督十字架的秘密在于某种矛盾中，因为这即是一种自愿的奉献，又是一种他身不由己受到的惩罚。

> <span style="color:blue">Hui: “自愿”源自于上帝的仁慈和爱；“身不由己”则因为人性中的罪。</span>

- 她否认上帝在自然中留下的不确定性和“无根据”的余地，而这种余地使自由和奇迹得以进入尘世。同样，在事实上，重负确实是强大无比的：圣.托马斯承认，大部分人的行为是受命于感官的盲目的欲望，并屈从于星辰的决定性的.[原编者注]

- 惟一不受偶然性支配的善是尘世之外的善。要知道_**最珍贵的东西并不扎根于生存中**_。这是美的。为什么？它把灵魂抛到时间之外。想生一个白如雪，红似血的孩子的女人，得到了这样的孩子，但她死了，孩子托付给了继母。

- 凡是存在的东西绝对不值得爱。因此，应爱不存在之物。

> <span style="color:blue">Hui:不太理解这点，那么神存不存在呢？抑或这里讲的的世俗意义的存在，而非精神。</span>

- 信念（这里所说的是对自然的一种超自然的阐释）是一种建立在超自然经验基础上的通过类比做出的**臆测**。......神秘主义是人类品性的惟一源泉。因为，不相信在尘世的幕后有无限的慈悲，或是相信这种慈悲在幕前，两者都使人变得残忍。

> <span style="color:blue">Hui:也就是说，以作者看信念是一种主观想象，而非客观存在。</span>

- 只有当我们在内心深处需要某种表示什么意义的声音，当我们呼叫以求得回音而我们却得不到回音时，只有这时，我们才触及上帝的沉默。
- 在两个不曾体验过上帝的人中间，否认上帝的人也许离上帝最近。

> <span style="color:blue">Hui:怀疑否认比不假思索的盲信要好。</span>

- 专注，从其最高程度上来说同祈祷是一回事。它意味着信念和爱。专注丝毫不分心就是祈祷。高度的专注就是构成人的创造才能的东西，而惟有宗教的专注才是高度的专注。......若人们不把注意力从上帝的启示上挪开，若人们不拒绝这种启示，那么上帝的启示必定会不可抗拒的发生。对于上帝的启示，并无选择可做，只需要不拒绝承认它的存在。怀着爱把专注专向上帝（或转向更低层次，一切真正美的东西），这使一些事难以实现。这就是灵魂中祈祷的不起作用的行文。我不必担心不拼命努力。条件仅仅是不自欺并要专心。
- 极端的纯洁性可注视纯洁，也可注视非纯洁；非纯洁性两者均不能；前者使它害怕，后者将它吸收。

> <span style="color:blue">Hui:纯洁具有包容吸收的能力。海纳百川，有容乃大。能被玷污的，是因为原本就不够干净；能被伤害的，是因为原本就不够强大。</span>

- 要触及不可能，必须完成可能。应在规定的时间完成职责，以确信外部世界的实在。应确信时间的实在，不然，就在幻想。
- 假如在此之后和余生之中自己会成白痴，真理却继续存在。
- 若人人都始终按照自己所读的正义来行事，公正与不公正之间的差别又是什么？
- 美：是一种人们看着它而不向它伸手的水果。

> <span style="color:blue">Hui: 占有有可能既是破坏。</span>

- 我们一定是犯下了使我们被诅咒的罪过，因为我们已失去了宇宙的一切诗歌。

> <span style="color:blue">Hui: 这句话看了好难过啊。</span>

- 艺术只有在大混乱中才能产生......因为不幸会使许多事情变得简单。
- 现代生活全由过度摆布，过度侵入一切：行为和思维，公众和私人生活。由此造成艺术的堕落。任何地方都没有平衡。时光在流逝中，销蚀，摧毁了世俗的东西。因此，在过去中有比现在更多的永恒。
- 在人所爱和所恨之间是否有同一性？人所恨的东西，当它出现另一种形式时，人们会有必要去爱它吗？反之呢？革命的经久不灭的幻想在于认为由于权利的受害者是无辜遭受着暴力。倘若把权力放在他们手中，他们就会公正地使用它。然而除了接近神圣的人，受害者如同刽子手一样被权利玷污。剑柄上的恶传送到了尖端。如此般登上巅峰的受害者由于变化而陶醉，他们会同样作恶或是更多地作恶，然后又马上跌倒在地。
- 劳动使人疲乏不堪地感受到了像球一样踢回来的合目的性现象。

## Tolerence [宽容，Van Loon]
### The Tyranny of Ignorance [无知的暴君]

- It follows that a society in which everything happens as the result of the direct personal interference on the part of an invisible being must depend for its continuted existence upon a strict obedience of such laws as seem to appease the wrath of the Gods.  
The word **taboo** is of Australian origin.
[在一个社会中，如果任何事情都被认为是由看不见的生灵操纵的，那么社会要维持下去，就必须绝对服从能平息神灵怒火的律法。]

> <span style="color:blue">Hui: I wonder more about who is going to give the law and if God is the one, how are we supposed to know the laws we are given are really from God. I don't want to worry about the necessity of laws.</span>

- Whether the taboo was an _**invention of the priests**_ or _**the priesthood was created to maintain the taboo**_ is a problem which had not yet been solved. As tradition is much older than religion, it seems more than likely that taboos existed long before the world had heard of sorcerers and witchdoctors. [究竟是祭司发明了禁忌，还是为了维护禁忌才产生了祭司，这是尚待解决的问题。由于传统比宗教更为源远流长，因此很可能早在男巫师和女巫婆问世之前禁忌就存在了。]

> <span style="color:blue">Hui: According to the author, does he mean that **the priesthood was created to maintain the taboo**?</span>

What we sometimes mistake for tolerance was merely indifference caused by ignorance. The struggle for tolerance did not begin until after the discovery of the individual. And the credit for this, the greatest of all modern revelations, belongs to the Greeks. [我们有时看到的宽容，实际上是由于无知导致的漠不关心。为宽容的斗争直到个性被发现后才开始，在现代最伟大的新发现中，个性发现这一荣誉应归功于希腊人。]

### The Greeks [希腊人]

－ According to the best knowledge of modern scientists, life (animate existence as differentiated from inanimate existence) began when for once all physical and chemical elements were present in the ideal proportion necessary for the creation of the first living cell. Translate this into terms of history and you get this: _“A sudden and apparently spontaneous outbreak of a very high form of civilization is only possible when all the racial, climatic, economic and political conditions are present in an ideal proportion or in as nearly an ideal condition and proportion as they can be in this imperfect world."_

[根据现代科学家的研究成果：当所有物理和化学的成分都达到形成第一个细胞的理想比例时，生命便开始了。把上面的话应用到历史学的概念，就是：“只有当所有种族、气候、经济和政治条件在不健全的世界中都达到或接近一种理想比例时，高级形式的文明才会突然地貌似自发地脱颖而出。”]

－ Those farfamed heros were still the product of an exceedingly primitive form of civilization. They were over-grown children who regarded life as one long, glorified rough-house, full of excitement and wrestling matches and running races and all the many things which we ourselves would dearly love to do if we were not forced to stick to the rountine jobs which provide us with bread and bananas.

[当时那些远近闻名的英雄不过是最初级文明的产物，他们犹如四肢过于发达的孩子，生命在他们眼里只是一场漫长而有关荣的搏斗，充满了刺激、角斗、赛跑，以及所有诸如此类的竞技。]

## Why does the world exist? [世界为何存在]

## The Theory of Moral Sentiments [Adam Smith]
### Of the Propriety of Action
#### Of the Sense of Propriety
##### Of Sympathy
1. Principles in the nature, the emotion which we feel for the misery of others when we either see it, or are made to conveive it in a very lively manner. (人性中的原始感情)
1. 原因：看到引发那种感情的处境
1. 恐惧死亡：对死者同情。我们把自己还活着的灵魂塞进他们已失去活力的躯壳里，然后设想在这种情况下我们自己将会有什么样的情绪。正是该错觉，在我们死后无疑不可能给我们带来任何痛苦的那些情况，在我们活着时想起来却让我们心痛不已。

##### Of the Pleasure of Mutual Sympathy [论彼此同情的快感]
1. 最让我们愉快的事，显然莫过于发现他人的感觉和我们自己心理全部情绪一致；而最让我们震惊的，也莫过于发现他人和我们完全没有同感......同情感活化喜悦，缓和悲伤......我们更加渴望向朋友倾诉我们心理的不愉快；他们同情我们的不愉快，比同情我们的喜悦， 会让我们得到更大的满足，而他们对我们的不愉快缺乏同情感，则比他们对我们的喜悦缺乏同情感，更加另我们震惊。

## Personality [人格心理学, Jerry M. Burger, 7th Edition]
### What is Personality?

**人格**可以定义为源于个体身上的 _稳定_ 行为方式和 _内部过程_ 。该定义中有两个需要注意的点：

      1. 人格是稳定的，我们可以跨时间、跨情境地来审查这些稳定的行为方式。
      2. 内部过程， 它是从人的内心发生，影响人行为、感觉的所有情绪、动机和认知过程。

> <span style="color:blue">Hui: 该定义没有提到环境，而是着眼与个体层面，研究那些在不同情境下相对稳定的行为方式和内部心理过程。但是环境对人格还是会产生影响的，只是程度不同，这与背后存在共性并不矛盾。</span>

## Social Psychology [社会心理学, David G. Myers, 8th Edition]
### Introducing Social Psychology

## Intimate Relationship [亲密关系, Rowland S Miller & Daniel Perlman]

### The Building Blocks of Relationships 

The book is about:

> What  are intimate relationships? why do they matter so much? Fundamental building blocks of close relationships: the cultures we inhabit, the experiences we encounter, the personalities we possess, the human origins we all share, and the interactions we conduct.

- Most of us need others even more than we realize, and there is a reason prisons sometimes use _solitary confinement [单独监禁]_ as a form of punishment: Human beings are a very social species. People suffer when they are deprived of close contact with others, and at the core of our social nature is our need for intimate relationships.

#### The nature and importance of intimacy

- 人类社会属性的核心部分正是**对亲密关系的需要**。

- What is Intimate Relationship?
      1. Knowledge
      1. Care
      1. Interdependence
      1. Mutuality
      1. Trust
      1. Commitment
- Attachment styles
      1. Secure
      1. Anxious-ambivalent/Preoccupied
      1. Avoident (Fearful and Dismissing)
- 性别差异
      - 我们需要做更多工作并进行更复杂和精细思考的应该是个体差异，而非性别差异。
      - 约35%并不是完全“男子气”或“女人味”，他们既自信又热情，既敏感又独立。这些人同时拥有传统上认为应该属于男性和女性的特质，因而被称为**双性化**（androgynous）。与任务有关的“男子气”的才成称为**工具性**（instrumental）特质，与社交和情感有关的“女人味”的技能称为**表达性**（expressive）特质。...长期来看，与表达性低的配偶结婚的人就不如与那些更敏感、贴心和友善的人过得满意。低工具性的人（缺乏自信和个人魄力的人）往往不如那些高工具性的人（任务导向的技能高的人）自尊程度高和适应能力强。...**那些拥有满意、幸福伴侣的最理想的夫妇通常工具性和表达性都很高。在实际生活中，大多数人更喜欢双性化的恋人或配偶。**
      - 人格影响人际关系的程度远大于人际关系影响人格的程度。人们是否会结婚，似乎有部分是由基因决定的。某些人生而具有的人格使得他们比其他人更可能晚婚，而且这种倾向不大会受到他们后来经历的影响。
      - **自尊**：对自我的评价。 人际间的拒绝会损害人们的自尊，而其他沮丧事件则不会。
      - 低自尊的人有时低谷伴侣对他们的爱，从而损害亲密关系，还觉知到根本就不存在的伴侣的模式。

## The Road Less Travelled [M Scott Peck]

- Discipline  is the basic set of tools we require to solve life’s problems. Without discipline we can solve nothing.

- Franklin:”Those things that hurt, instruct.” It is for this reason that wise people learn not to dread but actually to welcome problems and actually to welcome the pain of problems.

- In the succinctly elegant words of Carl Jung: “Neruosis [精神官能症] is always a substitute for legitimate suffering.”

- The neurosis assumes too much responsibility; the person with a character disorder [人格失调] not enough. 

- Few of us can escape being neurosis or character disordered to at least some degree. The reason for this is that **the problem of distinguishing what we are and what we are not responsible for in this life is one of the greatest problems of human existence.**

- It is for this reason that Erich Fromm so aptly (恰当地) titled his study of Nazism  and authoritarianism “Escape from Freedom”. In attempting to avoid the pain of responsibility, millions and even billions daily attempt to escape from freedom.

- Our view of reality is like a map with which to negotiate the terrain of life. If the map is true and accurate, we will generally know where we are, and if we have decided where we want to go, we will generally  know who to get there. If the map is false and inaccurate, we generally will be lost.

- The more honest one is, the easier it is to continue being honest, just as the more lies one has told, the more necessary it is to lie again. **By their opens, people dedicated to the truth live in the open, and through the exercise of their courage to live in the open, they become free from fear. **[一个人越是诚实，保持诚实就越容易，而谎言说的越多，则越要编造更过的谎言自圆其说。敢于面对事实的人能够心胸坦荡地生活，不必面临良心的折磨和恐惧的威胁。]

- Balancing is the discipline that gives us flexibility

- Mature mental health demands, then, an extraordinary capacity to flexibly strike and continually restrict a delicate balance between conflicting needs, goals, duties, responsibilities, directions etc. The essence of this discipline of balancing is **“giving up”**…Balancing is a discipline precisely because the act of giving something up is painful.

- The discipline of bracketing illustrates the most consequential fact of giving up and of discipline in general: namely that fro all that is given up even more is gained. **Self-discipline is a self-enlarging process.**

- Buddhists tend to ignore the Buddha’s suffering and Christians forget Christ’s joy. Buddha and Christ were not different men. The suffering of Christ letting go on the cross and the joy of Buddha letting go under the bo tree are one.

- One measure—and perhaps the best measure—of a person’s greatness is the capacity for suffering. Yet the great are also joyful. This then is the paradox. [一个人是否杰出和伟大，视其承受痛苦的能力决定，而杰出伟大本身，则会给人带来快乐和幸福－－－表面是悖论，其实不然。]

- A final word on this discipline of balancing and its essence of giving up: you must have something in order to give it up.

- It is the difference between the peak experience, typified by falling in love, and what Abraham Maslow has referred to as the “plateau /ˈplætəʊ/ experience”. The heights are not suddenly glimpsed and lost again; they are attained forever.

- **Seneca** said two millennia ago “Throughout the whole of life one must continue to learn to live and what will amaze you even more, throughout life one must learn to die.”

- The child’s speech patterns are uneven—occasional rushes of words interspersed with pauses and repetitions—which makes concentration difficult.

- Courage is not the absence of fear; it is the making of action in spite of fear, the moving out against the resistance engendered by fear into the unknown and into the future. 

- The highest forms of love are inevitably totally free choices and not acts of conformity. [放弃真正的自我，我们就无法进入爱的至高境界。至高境界的爱，必然是自由状态下的自主选择，而不是墨守成规，被动而消极地抗拒心灵的状态]

- Problems of commitment are a major, inherent part of most psychiatric disorders and issues of commitment are crucial in the course of psychotherapy. Character-disordered individuals tend to form only shallow commitments, and when their disorders are severe /səˈvɪr/ these individuals seems to lack totally the capacity to form commitments at all. 

- The fact that a feeling is uncontrolled is no indication whatsoever that it is any deeper than a feeling that is disciplined. To the contrary, psychiatrists know well the truth of the old proverb:”Shallow brooks  are noisy and still waters run deep.” We must not assume that someone whose feelings are modulated and controlled is not a passionate person. [恣意放纵，漫无节制的情感，绝不会自制的情感更为深刻。俗语说：“静水流深”。真正掌握和控制情感的人，不仅不缺少激情和活力，而且能使情感更为深刻和成熟。] 

- While one should not be a slave to one’s feelings, self-discipline does not mean the squashing of one’s feelings into non-existence. I frequently tell my patients that their feelings are their salves and that the art of self-discipline is like the art of slave-owning.

- One set of such questions derives rather logically from the material thus far discussed. It has been made clear, for instance, that self-discipline develops from the foundation of love. But this leaves unanswered question of where love itself comes from. And if we ask that, we must also ask what are the sources of the absence of love. It has been further suggested that **the absence of love is the major cause of mental illness** and that the absence of love is consequently the essential healing element in psychotherapy. This being so, who is it that certain individuals, born and raised in an environment of non love, of unremitting neglect and casual brutality, somehow manage to transcend their childhood, sometimes even without the loving assistance of psychotherapy, and become mature, healthy and perhaps even saintly people? Conversely, how is it that some patients, apparently no more ill than others, fail partially or totally to respond to psychotherapeutic treatment by even the most wise and loving therapist? 

- I believe that an understanding of the phenomenon of grace is essential to complete understanding of the process of growth in human being. 

- As human beings grow in discipline and love and life experience, their understanding of the world and their place in it naturally grows apace. Conversely, as people fail to grow in discipline, love and life experience, so does their understanding fail to grow. Consequently, **among the members of the human race there exists an extraordinary variability in the breadth and sophistication of our understanding of what life is all about.  This understanding is our religion.** Since everyone has some understanding—some world view, no matter how limited or primitive or inaccurate— everyone has a religion. This face, not widely recognized, is of the utmost importance: **everyone has a religion**.  
We suffer from a tendency to define religion too narrowly. We tend to think that religion must include a belief in God or some ritualistic practice or membership in worshiping group……We are puzzled as to how two very different people can both call themselves Christians. or Jews, or how an atheist might have a more highly developed sense of Christian morality than a Catholic who routinely attends mass. [随着爱和人生经验的增长，我们会越来越了解周围的世界，以及自己在世界中的位置。由于天赋以及成长环境的不同，每个人认识的广度和深度常常有着天壤之别。  
我们对于人生都有各自的认识，有着或广阔或狭隘的人生观和世界观，可以说，人人都有自己的信仰，对人生的认识和了解就属于信仰的范畴…两个完全不同的人，为什么都以基督徒自居？为什么和某些经常做弥撒的天主教徒相比，某些无神论者更能遵守宗教的道德规范？]

- We tend to believe what the people around us believe, and we tend to accept as truth what these people tell us of the nature of  the world as we listen to them during our formative year.[我们通常很容易接纳周围人的信仰，把口耳相传的东西视为真理]

- To some extent the religion of most adults is a product of transference [移情].Most of us operate from a narrower frame of reference than that of which we are capable, failing to transcend the influence of our particular culture, our particular set of parents and our particular childhood experience upon our understanding. **It is no wonder that the world of humanity is so full of conflict. We have a situation in which human being, who must deal with each other, have vastly different views as to the nature of reality, yet  each one believes his/her own view to be the correct one since it is based on the microcosm of personal experience. And to make matters worse, most of us are not even fully aware of our own world views, much less the uniqueness of the experience from which they are derived.**  
[许多成年人的信仰其实是移情的产物。我们毕竟不是超人，无法超越文化，父母和童年经验的影响，只能根据狭窄的人生参照系来待人处事。人们的感受和观点起源于过去的经验，却很少意识到经验并不是放之四海皆准的法则，他们对自己的世界观并没有完整而深入的认识。]

> <span style="color:blue">Hui:  Here is a short conversation with my best friend:  
Q: What is wrong with the world?  
A: There are people.  </span>

- 最有活力，最适合我们的信仰，理应从我们对现实的经验和认识中产生。经由质疑，挑战，检验的信仰，才是属于我们的信仰。...我想要真正地活着，就必须有自己的语言，拥有独一无二的怀疑与挑战的意识。我们有了自己的信仰，才能有成熟的心灵。[To be vital, to be best of which we are capable, our religion must be a wholly personal one, forged entirely through the fire of our questioning and doubting in the crucible of our own experience of reality…So for mental health and spiritual growth we must develop our own personal religion and not rely on that of our parents.]

- We see dogmatism and proceeding from dogmatism, we see wars and inquisitions and persecutions. We see hypocrisy behind faith.[过分信仰上帝，容易使我们更加教条。正是从这样的教条主义中，曾产生过无数战争，宗教裁判所乃至各种迫害。在信仰的背后，曾隐藏着无数伪善的嘴脸。]

- There is clearly a lot of dirty bath water surrounding the reality of God [不夸张地说，在真实的上帝周围，其实流淌着大量肮脏的洗澡水]： Holy wars [残酷的圣战], Inquisitions [宗教审判], Animal sacrifice [动物牺牲], Human sacrifice [活人献祭], Superstition [极度的迷信], Stultification [愚民政策], Dogmatism [教条主义], Ignorance [极端无知], Hypocrisy [伪装虔诚], Self-righteousness [自以为是], Rigidity [顽固不化], Cruelty, Book-buring [焚书坑儒], Witch burning [把女巫处以火刑], Inhibition, Fear, Conformity, Morbid guilt, Insanity [阻碍人类思维进步，制造恐惧，强迫服从，病态的原罪，疯狂的朝拜等等]. The list is almost endless. But is all this what God has done to humans or what humans have done to God? It is abundantly evident that belief in God is often destructively dogmatic. Is the problem, then, that humans tend to believe in God, or is the problem that human tend to be dogmatic? [可谓不可胜数。追根溯源，这一切究竟是上帝有负于人类，还是人类对不起上帝呢？无数宗教信仰都是以毁灭性的教条主义为特征，那么，问题出在我们过于信仰上帝，还是我们天生就容易流于教条主义呢?] Anyone who has known a died-in-the-wool  atheist will know that such an individual can be dogmatic about unbelief we need to get  rid of, or is it dogmatism? [熟悉顽固无神论者的人都知道，他们从不信仰神灵，以打破神灵崇拜为荣，乃至到了独断专行的程度。他们实际上并不比狂热的宗教信徒好到哪里。那么我们该屏蔽的是信仰本身还是教条主义呢？]

- Another reason that scientists are so prone to throw the baby out with the bath water is that science itself, as I have suggested, is a religion. [科学家容易把婴儿和洗澡水一道泼掉的原因，还在于科学本身就是一种宗教。] The neophyte scientist, recently come or converted to the world view of science, can be every bit as fanatical \fə’nætɪkəl\ as Christian crusader or a soldier of Allah. [刚刚接受科学启蒙的新生科学家，其狂妄和偏执的程度，可能丝毫不逊于基督教的十字军，或者真主安拉的圣战勇士。
] This is particularly the case when we have come to science from a culture and home in which belief in God is firmly hypocrisy. The we have emotional as well as intellectual motives to smash the idols of primitive faith. A mark of maturity in scientist, however, is their awareness that science may be as subject to dogmatism as any other religion.  [如果他们的家庭或文化背景原本就带有宗教的无知，迷信，顽固与伪善成分，他们的狂妄和偏执就可能更严重。在破除原有的信仰崇拜方面，我们的动机不仅有知性因素，也含有情感成分。科学家成熟的标志之一就是能够意识到，像其他任何宗教一样，科学也可能流于教条主义。]

- I have firmly stated that it is essential to our spiritual growth for us to become scientists who are skeptical of what we have been taught—that is , the common notions and assumptions of our culture idols, and it is necessary that we become skeptical of these as well. [我坚定地认为，对于别人教给我们的一切，包括通常的文化观念以及一切陈规旧习，采取冷静和怀疑的态度，才是心智成熟不可或缺的元素。科学本身很容易成为一种文化偶像，我们亦应该保持怀疑态度。]

- A third way in which the unconscious manifests itself and speaks to us if we care to listen is through our behavior. I am referring to slips of the tongue and other “mistakes” in behavior or "freudian slips”, which Freud, in his “Psychopathology of everyday life”, initially  demonstrated to be manifestations of the unconscious [虽然常常对潜意识不予理会，但它仍时刻渴望与我们对话。我们的言行足以暴露一切。我们经常说错话，也就是弗洛伊德所说的“说漏嘴”。我们在个人行为上所犯的可笑“错误”也会揭示出潜意识与我们沟通的渴望]……Not all slips express hostility or denied “negative” feelings. They express all denied feelings, negative or positive. They express the truth, the way things really are as opposed to the way we like to think they are.[人们不经意间说出某些奇怪的话，做出异于平常的举动，原因各种各样，但往往是受到压抑的东西的一种自然流露，其中既包括消极的东西，也包括积极的东西。它们是客观而真实的，尽管我们可能不想公之于众。] The fact of the matter is that our unconscious is wiser than we are about everything. 

- Jung’s theory of the collective unconscious suggests that our wisdom is inherited. Recent scientific experiments with genetic material in conjunction with the phenomenon of memory suggest that it is indeed possible to inherit knowledge, which is stored in the form of nucleic acid codes within cells. [荣格的“集体无意识”理论暗示出，我们的智慧来自于对全人类智慧的继承。最近的科学实验把遗传物质痛记忆现象结合起来进行研究，结论证明我们的基因很可能继承了某些知识，并在细胞里以核酸遗传密码的形式储存。]

- Decline of physical competence in old age is an inevitability. Within an individual lifetime, however, the human spirit may evolve dramatically…One of the basic natural laws is the second law of thermodynamics, which states that every naturally flows from a state of greater organization to a state of lesser organization, from a state of higher differentiation to a state of lower differentiation. In other words, the universe is in a process of winding down…Some other energy system has to be depleted if this one is to be maintained. Ultimately, according to the second law of thermodynamics, in billions and billions of years, the universe will completely wind down until it reaches the lowest point as as amorphous, totally disorganized, totally undifferentiated “blob” in which nothing happens any more. This state of total disorganization and undifferentiation is  termed entropy. [随着年龄的增长，肉体的衰老是不可避免的结果，但在人的一生中，心灵却可以不断进化，乃至发生根本性的改变......按照热力学第二定律，能量会自然地从有序状态流向混乱状态，从分化状态流向均一状态。换句话说，宇宙的秩序处于持续不断的崩解之中…为维持某处的秩序保持不变，必须以其他地方的秩序崩解为代价。这样下去，经过数十亿年，整个宇宙会完全分解，其秩序降至最低点，成为没有任何形状和结构，不再发生分化的死寂状态，我们称之为“熵”。]

- The process of spiritual growth is an effortful and difficult one. This is because it is conducted against a natural resistance, against a natural inclination to keep things the way they were, to cling to the old maps and old ways of doing things, to take the easy path……But as in the case of physical evolution, the miracle is that this resistance is overcome. We do grow. [心灵的成长，心智的成熟需要不断努力，而且必然是艰苦的过程。它必须与自然法则对抗，必须跟循规蹈矩的自然倾向背道而驰...我们习惯于走平坦的道路，害怕道路熵荆棘遍布。在反抗自然法则的过程中，心灵需要同熵的力量对抗，就如同生物进化一样，我们的心灵克服了熵的力量，才一直成长到今天。]

- But what is this force that pushed us as individuals and as a whole species to grow against the natural resistance of our own lethargy? We have already labeled it. It is love. Love was defined as “the will to extend one’s self for the purpose of nurturing one’s own or another’s spiritual growth”. When we grow, it is because we are working at it, and we are working at it because we love ourselves. It is  through love that we elevate ourselves. And it is through our love for others that we assist others to elevate themselves. Love, the extension of the self, is the very act of evolution. It is evolution in progress. The exclusionary  force, present in all of life, manifest itself in mankind as human love. Among humanity love is the miraculous force that defies the natural law of entropy. [归根结底，推动个人乃至整个物种克服懒惰和其它自然阻力的力量究竟是什么？其实我们已经给它取了名字，那就是“爱”。我们之所以能够成长，在于持续的努力，我们之所以能够付出努力，是因为懂得自尊自爱。对自己的爱是我们愿意遵循规矩去生活，对别人的爱让我们帮助他们去自我完善。自我完善的爱是一种典型的进化行为，具有生生不息的特征。在生物世界中存在着永久儿普遍的进化力量，体现在人类身上，就是具有人性的爱。它违反熵增的自然规律，是一种永远走向进步的神奇力量。]

- **We are stuck with this childlike notion of a loving God or else with a theoretical vacuum.** 

- **Our failure to conduct — or to conduct fully and whole heartedly —this internal debate between good and evil is the cause of those evil actions that constitute sin** ... It is work to hold these internal debates. They require time and energy just to conduct them...For laziness takes forms other than that related to the bare number of hours spent on the job or devoted to one’s responsibilities to others. A major form that laziness takes is fear ... **Each of us represents the whole human race; within each of us is the instinct for godhood and the hope for mankind, and within each of us is the original sin of laziness**. [**我们回避内心的善恶辩论，就产生了许多构成原罪的邪恶行为。**...完成心灵的辩论需要努力，需要时间，需要坚强的意志。...懒惰与你花多少时间工作，如何对待别人尽职尽责没有多少关系。懒惰的一个主要特征就是恐惧感。... 在每一个人的身体中都拥有向往神性的本能，都有达到完美境界的欲望，同时也都有懒惰的原罪。]

> <span style="color:blue">Hui: 不仅仅是行为上的懒惰，更是思想上的懒惰。如La Rochefoucauld在Maxims中说的：“We have more idleness in the mind than in the body.” 我们觉得累了，不想进行善恶的争辩，于是就听之任之。</span>

- First, I have come to conclude that evil is real. It is not the figment of the imagination of a primitive religious mind feebly attempting to explain the unknown…My second conclusion then is that **evil is laziness carried to its ultimate, extraordinary extreme**…I define evil, then, as the exercise of political power—that is, the position of one’s will upon others by overt or covert coercion—in order to avoid extending one’s self for the purpose of nurturing spiritual growth…My third conclusion is that the existence of evil is inevitable, at least at this stage in human evolution…Last, I have come to conclude that while entropy is an enormous force, in its most extreme force of human evil. It is strangely ineffective as a social force. [首先，我相信邪恶是真实存在的，它并非原始宗教为解释某些不可知现象而凭空捏造的一种概念。...第二，所谓邪恶就是为所欲为，横行霸道式的懒惰。...关于“邪恶”，我们可以给出这样的定义：邪恶式运用一切影响力阻止他人心智成熟与自我完善的行为。...第三，至少到目前人类进化的这一阶段，邪恶式不可避免的。...最后，熵是一种强大的力量，是人性极恶的体现。]

- There is another problem with power: aloneness

- Through bracketing and the attention of love we grow more aware of our beloved and of the world ...The word “conscious” is derived from the Latin prefix “con” means “to know with”. But how are we to understand this “with”? To know with what? We have spoken of the fact that the unconscious part of our mind is the possessor of extraordinary knowledge. It knows more than we know, “we” being defined as our conscious self. And when we become aware of a new truth, it is because we recognize it to be true; we re-know that which we knew all along. Therefore, might we not conclude that to become conscious is to know with unconscious? The development of consciousness is the development of awareness in our conscious mind of knowledge along with our unconscious mind, which already possess that knowledge. It is a process of the conscious mind coming into synchrony with the unconscious ...To put it plainly, our unconscious is God, God within us. We were part of God all the time. God has been with us all along, is now and always will be…I have said that the ultimate goal of spiritual growth is for the individual to become as one with God.[要使心智成熟，必须认清自己的偏见和局限。我们经由爱、包容和关怀，可以渐渐了解自己，了解所爱的人和整个世界。...“意识”这个词来源于拉丁文，本意是“共同认识与了解”。那么意识的对立面是什么呢？我认为就是潜意识，潜意识知道的事情永远比意识多得多。我们获得一项真理，得到一种启示，不过是重新认识潜意识里原本存在的事情。获得新的真理和启示，其实是意识和潜意识同步。...我们的潜意识就是上帝，我们内心的上帝。我们是上帝的一部分，上帝一直与我们同在，无论现在还是未来。...心智成熟的终极目标是天人合一。]



## People of the lie [M Scott Peck]

### Introduction: Handle with care

- Remember Saint Augustine's advice to hate the sin but love the sinner. [憎恨罪恶，但要爱有罪的人]
- Great evil has been committed throughout the centuries--and is still committed--by nominal Christians, often in the name of Christ.
- There are hundreds of thousands who go to Christian churches every Sunday who are not the least bit willing to be displeasing to themselves, serenely or otherwise, and who are not, therefore, for Jesus a pleasant place of shelter. Conversely, there are millions of Hindus, Buddhists, Muslims, Jews, atheists and agnostics who are willing to bear that trial. 

### The man who made a pact with the devil
- obsessive-compulsive neurosis （强迫妄想型精神官能症）
- the pattern of unwanted thoughts and the taking of undesired actions

### Toward A Psychology of Evil

- While some seek in religion an escape from mystery, for others religion is a way to approach mystery. The latter are not loath to employ the **reductionistic（还原论，简化论）** methods of science, but they are also not reluctant to use more integrative "right brain" means of exploration: meditation, intuition, feeling, faith, and revelation. For them bigger the mystery, the better.
- The problem of evil can hardly be separated from the problem of goodness. Were there no goodness in the world, we would not even be considering the problem of evil.
- It is as if we automatically assume this is a naturally good world that has somehow been contaminated by evil......If we seriously think about it, it probably makes more sense to assume this is a naturally evil world that has somehow been mysteriously "contaminated" by goodness, rather than the other way around. The mystery of goodness is even greater than the mystery of evil.
- Thus we may "break" a horse or even a child without harming a hair on its head. Erich Fromm was acutely sensitive to this fact when he broadened the definition of **necrophilia （恋尸癖）**to include the desire of certain people to control others-----to make them controllable, to foster their dependency, to discourage their capacity to think for themselves, to diminish their unpredictability and originality, to keep them in line. Distinguishing it from a **"biophilic" person（具有生物自卫本能的人）**, one who appreciates and fosters the variety of life forms and the uniqueness of the individual, he demonstrated a "necrophilic character type" whose aim is to avoid the inconvenience of life by transforming others into obedient automatons, robbing them of their humanity.....Evil is that force, residing either inside or outside of human beings, that seeks to kill life or liveliness. Goodness is that which promotes life and liveliness.（弗洛姆广义的界定“恋尸癖”时，增列了某些人对他人的控制欲：使他人受控制，增强依赖度，削弱其主动性，接受管束。弗洛姆将“恋尸癖性格的人”和“具有生物自卫本能的人”加以区分：前者将他人改变为顺从的机器人，剥夺他们的人性，借以回避人生的艰难；而后者则承认并鼓励生命的多样变化，以及“人”独有的特性。）
- A psychology of evil must be a religious psychology......it must not only embrace valid insights from all religious traditions but must also recognize the reality of the "supernatural".
- Having fled the **Jewish persecution** of the Hitler regime, the psychoanalyst **Erich Fromm** spent much of the rest of his life studying the evil of **Naziism**. He （_原书中讲他是第一个也是唯一一个确定邪恶人格类型的科学家，此书写与1983年，这个说法已经不正确了_）.......to identify an evil personality type, to attempt to examine evil people in depth, and to suggest that they be studied still further.
- The great Jewish theologian **Martin Buber** distinguished between two types of myths about evil. One type conerns people in the process of "sliding" into evil. The other concerns those who have already slid, "fallen victim" to and been taken over by "radical" evil.

- The case of Bobby and his parents
     - To children--even adolescents--their parents are like Gods. The way their parents do things seems the way they **should** be done. Children are seldom able to objectively compare their parents to other parents. They are not able to make realistic assessments of their parents' behavior. Treated badly by its parents, a child will usually assume that it is bad. If treated as an ugly, stupid second-class citizen, it will grow up with an image of itself as ugly, stupid and second-class. **Raised without love, children come to believe themselves unlovable.** We may express this as a general law of child development: **Whenever there is a major deficit in parental love, the child will, in all likelihood, respond to that defict by assuming itself to be the cause of the deficit, thereby developing an unrealisticlly negative self-image.**
     - People have feelings about each other. When psychotherapists have feelings about their patients, they label those feelings _**"countertransference"**_. Countertransference can run the whole gamut of human emotions from the most intense love to the most intense hatred.
     - Reactions evil frequently engender: 1. revulsion 2. confusion
     - But what would make revulsion a healthy response? Why might it be an appropriate countertransference for an emotionally healthy therapist? **Revulsion is a powerful emotion that causes us to immediately want to avoid, to escape, the revolting presence.**
     - Evil, then, is most often committed in order to scapegoat, and the people I label as evil are _chronic scapegoaters_. In _The Road Less Traveled_ I defined evil "as the exercise of political power--that is, the imposition of one's will upon others by overt or covert coercion--in order to avoid...spiritual growth [运用一切手段拒绝性灵成长，而恶性扩张自我的行为]". 
     - There are people, both in and out of jail, who seem utterly lacking in conscience or super-ego. Pyschiatrists call them **psychopaths**[精神病患者] or **sociopaths**[社会病患者]...This is hardly the case with those I call evil. **Utterly dedicated to preserving their self-image of perfection, they are unceasingly engaged in the effort to maintain the appearance of moral purity. They worry about this a great deal. They are acutely sensitive to social norms and what others might think of them. Like Bobby's parents, they dress well, go to work on time, pay their taxes, and outwardly seem to live lives that are above reproach.**[我所谓的恶人，是那些为了保护“完美”自我形象，而处心积虑维护道德完美假象的那类人。他们重视自己的道德形象，对于社会及别人对他们的看法，保持高度的敏感。这类人像Babby的父母一样，衣着体面，上班循规蹈矩，不逃税漏税，很难从他们表面的为人处事上挑出毛病。]
     - A leading theory of the genesis of pathological narcissism is that it is a defensive phenomenon...If the parents are cruel and unloving, however, or the childhood otherwise traumatic, it is believed that the infantile narcissism will be preserved as a kind of psychological fortress to protect the child against the vicissitudes[n. 变迁，盛衰，变化无常] of its intolerable life.
　
### The encounter with evil in everyday life

## The paradox of choice [选择的悖论, Barry Schwartz]
 
> <span style="color:blue">Hui:作者Barry Schwartz主要讨论的悖论是：更多的选择和自由并不能带来更大的幸福。那些总是想要做出最优选择的人可能拥有更大的世俗眼中的成功，但那些满足于“足够好”的选择的人更快乐。其中涉及到人们做出选择时受到的锚定效应，框架效应，易得性偏差等的影响。在身份的焦虑中，阿兰.德波顿也有提到更多的自由其实也是产生焦虑的原因之一。</span>

### 自由的重担

- 大名鼎鼎的政治哲学家Isaiah Berlin提出一个重要观点，他把自由划分为消极自由（negative liberty）和积极自由（positive liberty）。消极自由是一种“不做”（liberty from）的自由，人们有免受他人强制的自由，不按他人意愿来做事的自由。而积极自由是一种“去做”（liberty to）的自由，做自己生活的主人，让自己的生活变得更有意义、更有分量。

- 如果人类是理性的，那么增加选项就会让社会更美好。那些在意自己有没有选择权的人会从中获益，而那些不在乎选择权的人可以自觉忽略这些多余的选项。这种观点在理论上很有说服力，不过在现实中却行不通。

- 选择过多不仅使人们做决定的过程更艰难，因而感到更沮丧，还会让最终被选中的“幸运儿”魅力大减，导致满足感更低。

- 在这个缺乏监督的时代，如果你持续使用某个产品而不考虑其他选择，结果可能是，你将会长期支付更高昂的价格来买一样的服务。

### 是什么在操控你的行为

- peak-end-rule: 我们对过去体验的记忆由两种因素决定，事情达到极限（最好或最坏）时我们的感受，以及事情结束后我们的感受。

- 逻辑和记忆的鸿沟说明，我们实际上没有想象中那么了解自己。

- availability heuristic: 人们的判断推理过程常常受到可获得的记忆的影响，倾向于认为容易想起的事件比不容易想起的事件更常见。

- framing effect: 同一个问题的两种逻辑意义相似的说法会导致不同的决策判断，当消费者认为某一价格带来的是“损失”而非“收益”时，他们对价格就非常敏感。

- 当决定自己的收益时，人们倾向于规避风险，都有风险厌恶症。而当人们面对损失时，一个个都变得极具冒险精神，都是寻求风险的冒险家。

- psychological accounts：人的头脑中存在一种心理账户，会讲现实中客观等价的支出或收益在心理上划分到不同的账户中，做出不同的决策。

- law of diminish marginal utility：当人们连续消费同一种物品或服务时，其总效用虽然在增加，但边际效应，既每单位物品或服务带来的效用增加量却在递减。

- endowment effect: 人们更愿意持有自己已经拥有的东西，而不愿意用它交换另一个可能更好的替代物。

- 即便只需要考虑有限几个选项，人们也就容易犯错。而随着选择的数量和复杂度的上升，人们犯错的可能性就会不断增大。没有人有时间和精力对每个选项仔细琢磨、全面推敲，随着需要做的决定和选择的数量越来越大，决策难度会大大增加。

- 选项越多，付出越多，犯错就会让人更痛苦。选项增加会产生3个相互关联的不幸后果：
     1. 需要付出更多努力来做选择；
     1. 犯错的可能性更大
     1. 犯错会造成更大的负面影响

- 满足者最终会为很不错的选择感到满意，而最大化者追求的是绝对的最佳选择。我相信最大化者追求的目标正是导致他们不满的根源，尤其是在一个方方面面选择都多如牛毛的社会。虽然最大化者总是朝着“最好”努力，但几乎永远无法对最终的选择感到满意，因此，最大化者可能更容易成功，但满足者更容易幸福。
     1. 最大化者对好事的感觉没满足者那么强烈，对坏事的应对能力也没有满足者那么强。
     1. 坏事发生后，最大化者要经历较长的时间才能恢复。
     1. 最大化者比满足者花更多的时间深思熟虑。
     
- 所谓的最佳选择根本不存在。

### 行为经济学背后的心理奥秘

- learned helplessness: 当人或者动物接连不断地遭受挫折，就会丧失控制感，感到自己对一切都无能为力，陷入一种无助的心理状态。

- 可以毫不夸张地说，我们最基本的幸福感在很大程度上正是基于我们对环境的控制能力，以及是否知道自己拥有这种能力。

看来更多的选择机会并没有让人们感觉更好，有两种可能：

    1. 随着选择和控制的体验越发广泛而深入，人们对选择和控制的期望也在增加。对控制的渴望和期待也总是跑在现实的前面，无论有多大的自由都无法完全满足。
    2. 更多的选择并不意味着更多的控制。当选择增加到某个临界点时，我们反而会感到无力应对。
     
- 要在选择自由与承诺忠诚之间获得平衡简直是不可能的任务。... 那些热爱选择和行动自由的人就应该远离错综复杂的关系；那些看重稳定和忠诚的人就应该努力追求它。

- 如果“限制”可以接纳有限的自由，“自由”也可以受到一定的“限制”，人们就会逐渐变聪明，懂得衡量什么才是适度的限制。

- “需要”和“喜欢”其实是由两个完全不同的大脑系统掌管的，两个系统之间可以写作，但大部分时间是单独运作的。

- 最终决定决策质量的是人们做选择时的主观感受。如果选项数目多到会让主观满意度降低，我们的感觉往往更加糟糕。

- 消极情绪导致注意力范围缩小，无法全面考虑影响选择的各个因素。相反，心情越好，思维就越灵活，能考虑到更多的可能性。

- 如果选项增加，被拒选项的优点就会强化，导致最终选定的选项带来的满意度降低。

- 考虑机会成本时作出明智选择的必经之路。

- 最容易说出来的原因并不一定是真正重要的。但是话一旦说出口，它的重要性就会陡然增加。

- 想说明分析过后再做决定很容易犯错。随着选择数目的增加，做决定时要做的价值判断也增多了。尽管千方百计挤出的理由可能让你的决定在当下显得十分正确，但长远看来没什么特别大的好处。

- 作出重大选择之所以困难，可能就是因为它们时不可逆转的。婚姻没有退货保证，职业亦然。任何改变都意味着巨大的代价——时间、经历、情感和金钱。

- postdecision regret V.S. anticipated regret: 决定后懊悔是做了某个决定后，因为结果不理想而产生的后悔。预期性懊悔是指做选择之前，因为预计到结果不好或者还有更好的选择而感到后悔。

- omission bias: 人们更容易接受由于自己的忽略或不作为导致的损失，而不愿意接受自己的行为导致的同等损失。



## Psychobabble [Stephen Briers]
### What's so wrong with popular psychology?

The author pointed out that more of us turn to self-help books for answers to lives that feel in need of fixing. The phenomenon indicates our rising levels of _insecurity_ and _self-doubt_ and the stealthy(悄然的，秘密的) psychologising of American culture as a whole. Self-help industry is meme of popular psychology. **Meme** is defined by **Richard Dawkins** in his _The Selfish Gene_ as "an idea, behaviour or style that spreads from person to person within a culture". It is like today's "Big Data" or "Data Science"......The major selling points of self-help book is to keep things simple and manageable. The social environment is complex. There are innumerable variables contribute to even a simple human activity. According to **"chaos theory"**, even small local variations can produce a truly bewildering variety of outcomes--so great in fact as to render prediction virtually impossible, even in a closed, deterministic system. 

> <span style="color:blue">Hui: In the era of "Internet of Things", everything is connected. A slight move in one part may affect the situation as a whole. The consequence can be amplified/changed through the network. It is getting harder to predict and control. We badly need recipe to simplify this complicating world. At least, myself always wonder. The principle of **Occam's razor** advocates the virtue of parsimony. In statistical world, it means when two models provide similar results, always choose the simpler one. However, for our current situation, I agree with the author that even the most economical explanations at our disposal may still be too complicate. </span>

> Oscar Wilde: The truth is rarely pure and never simple

- In the mysterious world of particle physics, Superstring Theory remains the most promising candidate to provide us with a workable "Theory of Everything". This is the Grail of modern physics, the theoretical framework that will finally allow physicists to reconcile the uneasy bedfellows of quantum physics and general relativity. However as Brian Greene points out in _The Elegant Universe_, although the theory looks sound, the maths involved is proving so complex that even the best mathematical brains in the world are currently struggling to make the highly convoluted sums add up.

> <span style="color:blue">Hui: I don't think it is a good example here. The general relativity also looks elegant but is mathematically hard to prove. An example on how the increasing information availability complicates people's decision making may fit better here. </span>
 
> <span style="color:blue">Hui: I agree that the world is complicated. But what can we do?</span>

### Myth 1: The root of all your problems is low self-esteem
### Myth 2: Let your feelings out!
### Myth 3: Emotional intelligence is what really counts
### Myth 4: Let your goals power you towards success!
### Myth 5: No one can make you feel anything

- The degree to which we are affected and influenced by other people is actually quite terrifying.
- There is evidence that just the very process of thinking things through can turn down the intensity of our emotional responses......**prefrontal cortex(前额皮质) helps us regulate our emotional reactions**. Keeping a cool head, thinking things through, trying to be objective -- all of these things can genuinely help us to some degree.
- We have the tendency to conform instinctively to the roles that others create for us (Stanley Milgram的著名电击实验)
- People are reluctant to recognise how much of their everyday experience 'is determined not by their conscious intentions and deliberate choices, but by mental processed put into motion by their environment'. [John Bargh, Psychologist from Yale]......we may think we're calling the shots, but most of the time we are not even aware of the extent to which we are being unconsciously cued into particular roles by the actions and behaviour of those around us. How we experience the world, and even how we experience ourselves, is largely determined by others.
- Various studies have confirmed that people tend to copy each other's body language, facial expressions, speech patterns and vocal tones. The reason this automatic mimicry is crucial in understanding social influence is because psychologists believe it may be one of the mechanisms that underlie emotional contagion.
- It seems likely that by unconsciously copying the behaviour and micro-expressions of people around us we consequently end up replicating their emotions. In fact, research has established that even feelings like loneliness can be catching.
- It is not only through the subconscious power of imitation that we are exposed to the emotions of those around us. It turns out that we are neurologically configured to connect up with what others around us are experiencing. In recnet years scientist have discovered specialised mirror neurones in the brain that effectively put us into the other person's shoes.
- We should recognise just how vulnerable and open we are to the invisible and unconscious influence of those around us.
- Our spontaneous internal reactions to the people around us and the things that happen to us are an important part of being fully alive.

### Myth 6: Think positive ans be a winner!

- Independent studies have shown that while for non-depressed people positive affirmations do appear to dampen down levels of responsiveness in the amygdala (_effectively the 'fear center' of the brain_), for depressed people the opposite effect is produced: the amygdala becomes more rather than less active while the affirmations are being rehearsed. 
- Whereas positive mood seems to **promote creativity, flexibility, cooperation and reliance on mental shortcuts**, negative mood trigger more attentive, careful thinking, paying greater attention to the external world [Joseph Forgas, professor of social psychology]

> <span style="color:blue">Hui: There is a reason for everything's existence. We need both sides and the key is to keep balance as in a million other situations.</span>

- Depressed people are also better at sequential decision-making. they accept options less readily which led to longer search and better choices. Depression, by fostering greater persistence many improve performance in certain task.

> <span style="color:blue">Hui: I doubt it. 1) how to define better choice? 2) does longer search lead to better choice or increase the likelihood of making better choice? I think the ability of making choice is developed overtime. 3) persistence is personality which is relative stable across time and situation. I can’t imagine depressed people are more persistent or being depressed will make you hold on longer. How they collected the data and do analysis? How they choose samples? Are those samples representative?</span>

### Myth 7: We need to talk......
### Myth 8: Whatever your problem, CBT is the answer
### Myth 9: You can never be too assertive
### Myth 10: Men and women live on different planets
### Myth 11: Your inner child needs a hug
### Myth 12: You can learn to do anything you want
### Myth 13: You'd better get yourself sorted
### Myth 14: You are stronger than you know
### Myth 15: You are a master of the universe!
### Myth 16: There is no failure, only feedback
### Myth 17: It's all your parents' fault
### Myth 18: You can heal your body
### Myth 19: You are in control of your life
### Myth 20: Married bliss: a matter of give and take
### Myth 21: Discover the real you!
### Myth 22: Make every second count
### Myth 23: We must all strive to be happy
## The Optimism Bias [Tali Sharot]

> <span style="color:blue">Hui: 作者Tali Sharot提出其实人类的大脑习惯于乐观的看待事物，这种乐观有利于人类生存，比如我们有着“优势错觉”。我们信心十足地认为自己比一般人更有趣，更有魅力，更友好，更成功。当人问起时，我们表面不会承认，但是内心却对自己的判断笃信不疑。作者指出大部分人都过度乐观（抑郁症患者除外），而那些我们认为悲观的人同样过度乐观，只是偏离程度低些。书中同样谈到了之前推荐的几本书中提到的一些认知偏差，如聚焦错觉，享乐适应，控制错觉等等。 </span>

### Illusions of the Human Brain

- During spatial disorientation, also known as vertigo, a pilot is unable to detect the position of the aircraft relative to the ground. [空间定向障碍，又称“晕眩”，飞行员无法正确判断飞机对地面的位置。]

- During a rapid deceleration, a pilot sometimes feels the plane is facing downward. To rectify this illusion, the pilot may then pull up the nose of the plane, which often leads the aircraft to fall into a catastrophic spin known as the “graveyard spin”. [在急剧减速时，飞行员有时会觉得飞机正机头向下飞行。为了纠正这一错觉，飞行员可能会拉升机头，这常常会导致飞机灾难地旋转，也叫做“死亡螺旋”。]

- The human brain’s navigational system has evolved to detect our movement on earth, not in the sky. It calculates our position by comparing signals from the inner ear (which has tubes of liquid that shift when we move) to the fixed sensation of gravity that points down to the center of the earth. [人类大脑进化后的导航系统适用于地面上的行动，而非空中。它通过比较内耳中的信号（内耳里的小管含有液体，会随着我们的行动而变化），可以判断我们相对指向地心的重力感受。]

- Our brain interprets irregular signals, such as angular accelerations or centrifugal force, as the normal force of gravity.[一个人的大脑会把不合常规的信号（例如角加速度或离心力）]

- Like our navigation system, our visual system was developed to interpret the world it would encounter most frequently. To do so, it developed some shortcuts, some assumptions about the world, which it uses to function. These allow our brain to work efficiently in almost all situations. However it does leave room for errors when those assumptions are not met.[和导航系统一样，视觉系统发展到企图识别熟悉的万事万物。为了做到这一点，视觉系统发展出了一条捷径，那就是先入为主的假设这个世界是什么样的，然后基于这一点展开工作。这让大脑在几乎所有的情况下都能有效运作。]

- Thatcher illusion, as it was first demonstrated in 1980 on a photo of former British prime minister Margaret Thatcher.

- To get along in this world, we need to remember and distinguish thousands of faces. Luckily, most of us do so with ease, thanks to the part of the brain known as the **Fusiform Face Area** (FFA), which is located in a region of the brain called the fusiform gyrus. The FFA is the part of our visual system that allows us to recognize that a face is a face, and to distinguish between the many faces we encounter on a daily basis.  Without a functioning FFA, we may all become prosopagnosic, which means we will be face-blind. People who suffer from lesions to their fusiform gyrus have difficulty identifying faces and may even be unable to recognize their own face. 

- Humans are very good at perceiving the emotional state of others. We do so unconsciously all the time. [人类很擅长察言观色，我们毫无意识地重复这一技能。]

- We can do so for familiar faces, faces we have not previously encountered, faces from our own culture or a foreign one, because emotional expressions are universal. [所有人体现情绪的表情是一样的] The capability to convey and detect emotion is critical to our existence. [表现和体察情绪的能力对我们的生存至关重要。]

- The brain is used to detect upright faces and expressions. It processes the parts of  the face in unison, as this is the most efficient way to do so. In other words, rather than identifying each part separately, the brain processed the face and its expression as a whole. [大脑习惯观察端正的面孔和表情，并且能同时分辨脸庞的各个部分，因为这是最有效率的方式。大脑并不是逐一区分，而是把脸庞和表情当作整体进行处理。]

- As in most illusion, learning of the illusion and its roots does not erase the illusion....Cognitive  illusion, rather than sensory ones, are much harder to accept. **As in any complex system, the brain has built-in defects. These defects are overpowering; we live with them every day without being aware of them. We rarely doubt that our perception is accurate reflection of the world, when, in fact, our brains can often provide us with a distorted sense of reality.** 

- This illusion is known as the superiority illusion (or the superiority bias). We are quite confident that we are more interesting, attractive, friendly, and successful than the average person. We are quite confident that we are more interesting, attractive, friendly, and successful than the average person. We may not admit it openly when questioned, but we have a strong sense that this is correct. [这种错觉称为“优势错觉”。我们信心十足地认为自己比一般人更有趣，更有魅力，更友好，更成功。当人问起时，我们表面不会承认，但是内心却对自己的判断笃信不疑。]

- While we do not recognize our own biases, we can often detect biases in others.[我们并不知道这是自己的错觉，不过虽然我们意识不到自己的偏见，但却能发现别人的偏见。]

- **Most of us believe we are superior in many ways to other individuals. This means we see ourselves as better, not everyone else as better. Therefore, (a) we all have a slightly different views the world, and (b) we are able to detect cognitive illusions, such as the superiority illusion, in others. Because we can identify these illusion and biases in others but not in ourselves, we conclude that we are less susceptible to bias than most other people. In essence, this means we hold the illusion that we are immune to illusions. This is the irony of cognitive illusions. Our tendency to perceive ourselves as less susceptible to bias than the rest of the human race was termed the bias blind spot** by the psychologist Emily Pronin of Princeton University. [大多数人相信自己在很多方面比其他人优秀，这意味着我们认为自己优于别人。这揭示了1）我们对世界的看法会稍有不同；2）我们还能够发现他人的认知错觉，如优势错觉。因为我们能够分辨出别人的错觉和偏见，却发现不了自己的，所以我们认定自己比大多数人更少出现错觉和偏见。我们实际上有这样的错觉，并对这样的错觉是免疫的。这正是认知错觉的讽刺之处。我们自认为比别人有更少的偏见，这称为“偏向盲点”。]

- People tend to judge the extent of other people’s bias according to their behavior but judge their own biases according to their internal  feelings, thoughts, and motivations.[大家根据别人的行为来判断其偏见程度，却根据内心感受，想法和动机来判断自己的偏见。]
Scalia seems to have experienced an **introspection illusion**. An introspection illusion is the strong sense people have that they can directly access the processes underlying their mental states. Most mental processes, however, are largely unavailable for conscious interpretation. The catch is that people are unaware of their unawareness.[内省错觉是指人们的一种强烈感觉，认为自己能够了解决定心理状态的心理过程。大多数心理过程是无法用理性解释的，潜在的不利因素是大家不知道自己的无知。]

- We can unknowingly create verbal rationalizations for preferences and intentions that we do not actually possess.[我们会无意识地口头解释未曾有过的偏好和动机。]
Often, we are wasting valuable time. Studies show that **thinking too much can lead to suboptimal judgments. **


- Our capacity to envision a different time and place is critical for our survival. It allows us to plan ahead, greatly increasing our odds of sticking around this planet. It motivates us to save food and resources for a time when we expect them to be less available. It enables us to endure hard work in the present in anticipation of a future reward, or to search for an appropriate long-term partner. Our voyage is hardly limited to the recent past and future. It can expand to a time before and after out own existence. This allows us to forecast how our current behavior may influence future generations. [畅想不同的时空对我们的生存至关重要，让我们能够未雨绸缪，大大提高我们在这个星球的生存机会。这种能力促使我们储备食物和资源，应对可能出现的短缺。这种能力让我们能够承受眼前的工作压力，因为内心期待着未来的犒赏，或者也会让我们去寻找一个合适的长期合作伙伴。这种能力会超越我们自身存在的时段，让我们能够预见当下的行为怎样影响后世。]

- Are we the only ones with a capacity for prospection? Do we share this ability with other species? ...  Certain animal behaviors, such as storing food or seasonal migration, do not necessarily involve an understanding of future need. These tendencies can simply reflect an evolved **genetic predisposition**. [储备食物或者季节性迁徙，并不一定是考虑未来的需求。这些行为只不过体现了进化后的遗传易感性。] 

### The Evolution of Prospection

- Mental time travel—going back and forth through time and space in one’s mind—may be the most extraordinary of human talents. It is also one that seems necessary for optimism. If we are unable to imagine ourselves in the future, we may not be able to be positive about our prospects, either. [思想上的时间旅行，让思维穿梭于时间和空间，这可能是人类最卓越的才能。对于乐观而言，这个才能必不可少。如果我们无法想象未来的自己，或许也就无法想象美好的前景。]

- The posterior part of the cabdrivers’ hippocampi was larger than average. The hippocampus (there is one on each side of the brain) is a region that is crucial for memory. The posterior bit is particularly important for spatial memory. [出租车司机大脑海马体的后部比一般人大。海马体是有关记忆的重要区域，对空间记忆来说尤其重要。]


- The term mental time travel was first coined by the Canadian psychologist Endel Tulving to refer to **our capacity for revisiting the past and imaging the future. ** K.C had suffered damage to his frontal and temporal lobes [大脑额叶和颞叶都遭到了损伤], including a lesion in his hippocampus. Two decades laters, Eleanor Maguire examined amnesiac patients with brain damage confined to their hippocampi. She found that those patients, just like K.C,. were not able to construct detailed images of future scenarios. Without working hippocampi, the patients appeared to be stuck in time— unable to revisit the past or mentally explore the future. 

- The vital difference in the level of sophistication of future thinking between humans and birds lies in our frontal lobes [额叶]…The rapid development of human frontal lobes allowed for the ability to make tools, find novel solutions to old problems, plan steps that would make goals more achievable, see far into the future, and possess self-awareness. [额叶的快速发展，让人类能够制作工具，能够为旧问题寻找新的解决方式，能够制定步骤实现目标，能够用长远眼光看待未来，能够有自知之明。]

- The only way conscious mental time travel could have been selected for over the course of evolution is if it had merged at the same time as false beliefs. In other words,** an ability to imagine the future had to develop side by side with positive biases. The knowledge of death had to emerge at the same time as its irrational denial.** [在进化过程中，思维时光穿梭的能力想要发展，必须满足一个条件才行，那就是这种能力必须和错误的信念共存。换句话说，想象未来的能力必须与乐观偏见并驾齐驱。对死亡的认识必须与不理智的否认态度同时出现。]

- Optimism does not exist without at least an elementary ability to consider the future, as optimism is by definition a positive belief about what is yet to come, and without optimism, prospection would be devastating. [如果缺少思考未来的基本能力，乐观将不复存在，因为从定义上讲，乐观就是对尚未发生的事情持积极态度；而如果没有乐观，展望未来的能力就会毁灭一切。] 

- The term _self-fulfilling prophecy_ was coined by the sociologist Robert Merton in 1948… Self-fulfilling prophecy is, in the beginning, a false definition of the situation evoking a new behavior which makes the originally false conception come true. [“自证预言” 一词由社会学家罗伯特.默顿在1948年首次提出。自证预言指一开始对形势的错误见解激发的行为，而这一行为却让原本错误的见解成真。]

- Pygmalion effect, after George Bernard Shaw’s play. Shaw’s Pygmalion is a classic makeover tale— the story of a professor who transforms a working-class girl into an upper-class lady. [“皮格马利翁”效应一词源于萧伯纳的戏剧《皮格马利翁》，讲述一个教授把工人阶级的女孩改造成了上流社会的贵妇。]

- In real life, however, educators, as well as the rest of us, hold relatively stable preconceptions that are, in general, not based on real evidence. Teachers have been shown to form predictions regarding new students’ achievements based on race, gender, ethnicity, socio-economic level, and even physical attractiveness. This can be dangerous. Expectations are likely to influence a child’s performance, ultimately altering his future. In fact, the Pygmalion effect is thought to be a significant factor in producing and maintaining gender and racial gaps in IQ testing, GPAs, and college success. [在现实生活中，教育者会和其他人一样持有一定的成见，而这些看法往往不是由真实的证据得出的。研究显示，老师会根据新学生的种族、性别、民族、社会阶层，甚至外貌形成预期。这么做很危险。预期可能会影响孩子的表现，最后改变他们的未来。皮格马利翁效应是导致智商测试、学业平均成绩、大学成就中性别和种族差异的重要因素。]

> <span style="color:blue">Hui: 怎么衡量哪个因素重要？</span>

- When individuals are reminded of their membership in a group (such as gender or race), the stereotype associated with that group is more likely to influence their behavior.

- What Sara Bengtsson’s study shows, as well as Jane Elliott’s field experiment, is that the influence of stereotypes is surprisingly fluid.  New expectations can rapidly take over old ones quickly substituting one behavior for another. This fluidity is encouraging. It means that with guided intervention, we may be able to reverse the negative effects of stereotypes on an individual’s performance.[成见具有惊人的灵活性。新的预期可以很快取代旧的，迅速用一种行为替代另一种。这种灵活性无疑是鼓舞人心的，意味着只要采取加以指导的干预，我们或许可以扭转成见对个人表现带来的负面影响。]

- When neurons in a specific part of the brain are active, their consumption of oxygen is increased. In response, blood flow will be enhanced to that region, supplying hemoglobin. This leads to local changes in the concentration of deoxyhemoglobin and oxyhemoglobin, which alters the MRI (Magnetic Resonance Imaging) signal that is recorded by the scanner. [大脑某个具体不稳的神经元活动时，耗氧量就会上升。相应区域的血液流量也会增大，提供血红蛋白。这改变了该区域脱氧血红蛋白和氧合血红蛋白的浓度，改变了扫描仪器记录下来的磁共振成像信号。]

- The frontal cortex is a large area of the brain and includes anatomically and functionally distinct subregions. It is the most recently developed part of the brain, and it is not found in animals at the lower end of the evolutionary scale. [额叶皮质时大脑中很大的区域，包括了结构和功能迥然不同的分区，是大脑最后才得以进化的部分，而位于进化链低端的动物甚至没有这个部位。] 

- The frontal cortex has enlarged disproportionately in human evolution relative to the rest of the brain. Its physical development is the main reason why we have a relatively larger brain than most other animals. The frontal lobes are critical for functions that are uniquely human, such as language and theory of mind. Theory of mind is our ability to think about what other people are thinking. [相比于大脑的其它部分，额叶皮质在进化过程中发展得有些不成比例。额叶皮质体积变大也是人类大脑比其它多数动物更大的主要原因。]

- The frontal lobes are critical for functions that are uniquely human, such as language and theory of mind. Theory of mind is our ability to think about what other people are thinking. …Frontal lobes are involved in executive functions. Executive functions are those that enable us to identify future goals and recognize the actions that will move us toward achieving those goals. The ability to predict which behaviors will lead to which outcomes, differentiate desired outcomes from unwanted outcomes and promote actions that lead to the sought-after (追求，探索) results.

- When the brain doesn’t get what it expects, it frantically tries to figure out what went awry. The signal in the frontal cortex may have been modulating attention...The importance of this signal is that it can facilitate learning. As learning from errors is critical for directing our behavior toward optimal functioning, enhanced attention to errors would lead to better performance on the next trial. 

- Defensive pessimism: holding low expectations will protect us from disappointment 

- Why would a bleak outlook result in such tragic deaths? It seems that a pessimistic outlook promoted risk-taking behavior because the pessimists believed they did not have much to lose.  Optimists envision a glorious future and are reluctant to disappear into oblivion. 

### When Private Optimism Meets Public Despair

- The people’s urgent need for good news most likely drove positive expectations well above the baseline. It is **during hard times that people rely on optimism the most**. 

- Jonsthan Haidt, a psychologist at the University of Virginia who studies the **feeling of elevation**, describes such instances as **erasing cynicism and generating hope and optimism**. According  to Haidt, such occurrences stimulate the **vague nerve [迷走神经]**, which triggers the release of **oxytocin**. The **vague nerve** is one of the twelve cranial nerves. Its course starts in the **brain stem** [脑干], which is an evolutionarily old part of the brain that plays a key role in regulating vital functions. The nerve extends all the way from the **brain stem** through the neck to the chest and abdomen. It conveys sensory information to the brain that reflects the body’s internal state, as well as sends information from the brain to the rest of the body. **Oxytocin** is produced in the **hypothalamus** [下丘脑] and stored in the **pituitary [垂体]**, which is situated just beneath the **hypothalamus** and secretes hormones. When triggered, oxytocin is discharged into the bloodstream, and it also binds to receptors in the brain, particularly in regions involved in emotional and social processing. **High levels of oxytocin reduce our uncertainty about social stimuli [stimulus的复数]**. 

- Amygdala [杏仁核] engages in processing social signals, especially ambiguous ones. 

- Reduced social stress and uncertainty, along with an increase in approach behavior, should enhance trust among individuals. [社交压力和不确定性减少，亲近行为增多，这些会加强人与人之间的信任。]

- Why do we see such a disconnect? Why is it that people continually underestimate their own risks while overestimating the severity of the situation for the rest of society? **People tend to feel more optimistic about things they believe they can control.** 

> <span style="color:blue">Hui: 这就是哪些公司高层对公司未来总是那么乐观的原因么？与其说有远见，不如说是局内人的偏见，控制的幻觉。好的一方面是，可能他们不是在撒谎忽悠，他们真心积极向上。但是形式不会因为不经过分析的主观积极就有改善，那要如何纠正这样的偏差呢？数据分析。</span>

- There is one additional factor that comes into play—the power of relativity. Our brain plays a little trick that boosts positive illusions. Not only do people hold optimism bias about their personal future; in addition, they hold a pessimistic bias about everyone else’s.  


### The Unexpected Ingredient for Well-being

- Studies show that just taking care of a plant is positively related to well-being. 

- What else is related to happiness? According to the survey, of you hold a PhD, go to church (or another religious center), and play sports, you are seven times more likely to be happy-go-lucky than someone who does not have a PhD, never goes to church, and shuns physical activity. 

- The notion that raising children is negatively related to happiness was supported by a study conducted by Daniel Kahneman. Kahneman (prospect theory: how people make decision under uncertainty). What really matters is when, and how often, we feel irritated, anxious, satisfied. Our happiness is thus not affected to a large extent by reflecting on our lives, but by the flood of feelings that are constantly generated within us. However, most of questionnaires of subjective well-being ask us to reflect and assess our general satisfaction with life rather than our daily experienced happiness…The consistent conclusion across studies that children do not necessarily bring us joy conflicts with conventional wisdom in a striking manner. Why do individuals insist and often strongly believe, that their happiness is rooted in the existence of their offsprings? One explanation is that happiness, whether experienced or reflected, is not necessarily the most significant factor for the continuation of humankind. Passing on our genes, on the other hand, is. 

- A higher income may indeed influence reflected satisfaction with life without significantly enhancing our experienced happiness.

- **Focusing illusion**: exaggerated importance we attribute to specific aspects of our lives when we are asked about them.

- The importance of relative wealth to our well-being explains counterintuitive findings in the literature, such as why an increase in a nation’s GDP over time is not accompanied by in increase in general subjective well-being. While the country may be getting wealthier, the individual’s relative economic status remains the same, and thus happiness stays constant. Relativity is a crucial aspect of human psychology. Consider the way we perceive our physical environment. The extent of change that needs to occur in the sat of our surroundings in order for us to notice a difference is dependent on preliminary states… Therefore the more you have the more you need to increase your wealth in order to even notice a difference that would affect your happiness.

- Andrew Yonelinas, a psychologist renowned for his dual-process theory of recognition: memory retrieval includes two distinct processed **familiarity** and **recollection**. These two memory processes have been shown to be functionally and neuro-anatomically distinct. They rely on different brain regions within the medial part of the temporal lobes.[两个记忆过程（熟悉感和回忆）在功能和神经解剖方面都有不同。两者依赖大脑额叶中部的不同区域。] While a region called the hippocampus [海马体] is crucial for **recollection** but not for **familiarity**, the adjacent perirhinal cortex [鼻周皮层] signals familiarity. Amnesiacs [健忘症患者] who have sustained damage to the hippocampus but whose surrounding cortex is intact usually suffer impaired recollection, but they know when something is familiar. They may know they have met you before, but they will have no memory of the episodic context of the encounter. 

- Having extremely vivid memories of past emotional experiences and only weak memories of past everyday events means we maintain a biased perception of the past. The two other principal factors that lead us to mis-predict what will make us happy are the same ones that make us mis-predict what will devastate us: 
    1. our tendency to underestimate our rapid adaptation to almost any new circumstance; 
    1. when we think about how a higher income, more vacation time, or better health will affect our happiness, we tend to focus on that one factor and disregard everything else which will stay the same. [聚焦幻觉] 

- While severely depressed patients are pessimistic, mildly depressed people are actually pretty good at predicting what may happen to them in the near future—a phenomenon known as _depressive realism_. [抑郁现实主义] 

- The optimism bias is crucial ingredient for keeping us happy. When people perceive the future accurately, when they are well aware that none of the things people assume will make them happy is likely to have any lasting significance on their well-being, when they take off their rose-tinted glasses and see things more clearly, them become depressed—clinically depressed.

> <span style="color:blue">Hui: We need to keep the optimism bias to be happy?? Why can’t we just accept who we are? </span>

### When things go wrong: depression, interpretation, and genes

- The notion of optimistic and pessimistic explanatory styles was put forward by the psychologist **Martin Seligman**. He came up “_learned helplessness_".

- The most commonly prescribed antidepressants are drugs that enhance the function of the neurotransmitter serotonin. A neurotransmitter is a chemical that enables communication between neurons in the brain...The majority of antidepressants, such as Prozac, are selective **serotonin** reuptake inhibitors (SSRIs)…gene coding for **serotonin** function predicts a person’s likelihood of suffering depression.  

- The amygdala is a structure deep in the brain that processes emotional stimuli. It is also involved in generating physiological responses to these stimuli. Amygdala activity is regulated by parts of the frontal cortex, in particular the anterior cingulate cortex (ACC). In individuals with a short allele of the serotonin-transporter gene, there is reduced connectivity between the ACC and the amygdala. This means that the two structures are not as good at communicating with each other. [杏仁核是大脑深处处理情绪刺激的结构，同时人对刺激的心理反应也少不了它。额叶皮层的一部分负责管理杏仁核的活动，尤其是ACC。如果一个人的serotonin-transporter gene等位基因是短的，那么前扣带皮层ACC和杏仁核的关联性就会降低，也就是说这两个结构的沟通能力就没那么好。]

> <span style="color:blue">Hui: 有几个专业名词反复出现[单词]，serotonin——5-羟色胺，allele——等位基因，amygdala——杏仁核，anterior cingulate cortex——前扣带皮层，frontal cortex——额叶皮层</span>

- This is known as fear extinction—the process of learning that something that was previously threatening no longer is. Fear extinction involves the regulation of amygdala activity by the ACC. As the connectivity between these structures is relatively impaired in carries of the short allele, these individuals will be less capable of extinguishing their fear. They will be more likely to maintain high levels of anxiety and be prone to depression and other mood disorders. [“恐惧消退”指的是明白以前具有威胁性的事情不再构成威胁这一过程。恐惧消退需要前扣带皮层管理杏仁核的活动。由于等位基因较短的人这两个结构的联系有所削弱，这样的人就很难驱散自己的恐惧。因此他们更可能保持高度紧张核焦虑，并且容易出现抑郁核其它情绪紊乱的状况。]

- hippocampus (which has an important role in memory) and the striatum (which is involved in motor function, reward processing, and generating expectations of pleasure and pain), as well as other brain regions I focus on to a lesser degree, such as the thalamus and the habitual. 

> <span style="color:blue">Hui: 这里几个专业名词[单词] hippocampus——海马体——记忆，striatum——纹状体——运动、奖赏、快乐痛苦的预期，amygdala——杏仁核，thalamus——丘脑，habitual.——缰核</span>


### The Value of Anticipation and the Cost of Dread 

- When it comes to adverse events, most of us choose to get it over with as soon as possible. The reason is simple: We want to avoid the dread that comes with anticipating pain. Instead of spending out time worrying and fearing, we would rather face the pain immediately and be done with it. [一旦遇到糟糕的事情，大多数人都会选择尽快搞定。原因很简单：我们不想因为未来的痛苦而畏惧。]

## Art of Thinking Clearly [Rolf Dobelli,清醒思考的艺术]

1. 幸存偏差：由于日常生活中更容易看到成功而非失败，使得人们高估成功的希望（创业）
1. 游泳选手的身材错觉：混淆选择标准与结果（模特因为漂亮才选来拍化妆品广告，而非因为用了这些产品才漂亮）
1. 过度自信效应：1）不存在不够自信效应；2）男性更加严重；3）悲观者只是高估幅度少些。
1. 从众心理
1. 纠缠沉没成本：all pay auction的困局
1. 互惠偏误：互惠古来有之，是出色的生存智慧。没有互惠人类早灭绝了。但注意不要被互惠道德绑架。
1. 确认偏误：所有思维错误之父......过滤与我们观点相矛盾的信息。宗教和哲学信念是杰出的例子。
1. 权威偏误：对权威批判性越强，你就越自由。
1. 对比效应/框架效应/锚定效应：这几个都类似
1. 现成偏误：依据现成的例子来想象世界。某种东西反复出现我们的大脑就很容易重新提取（接受）它，尽管不一定是真的。
1. 事后诸葛亮(Hindsight Bias)
1. 司机的知识：播音员是话筒不是专家。芒格认为知识有两种：1）真知识，来自那些投入大量时间和思考获得知识的人们；2）司机的知识，装的好像知道的人，他们会模仿别人的表演，也可能有动听的声音或具有说服力的形象。但他们传播的知识是空洞的，他们高谈阔论地挥霍华丽词汇。企业越大，人们越期望它的CEO具有表演才能——交际能力。
1. 控制错觉：你对你生活的控制比你以为的要少。(电梯上的安慰按钮。公司温度控制的按钮。)
1. 激励过敏：激励机制能够解释90%的个人或者组织行为。
      1. 一旦有激励加入游戏或改变了激励，人们就会迅速而剧烈地改变自己的行为
      1. 人们是对激励做出反应，而非激励背后的目的（1947悬赏羊皮纸手稿，为了增加数量而将手稿撕碎；19世纪，中国悬赏征购恐龙骨，恐龙骨被敲碎。）
1. 回归均值：避免错误归因，恢复正常可能只是回归均值在起作用
1. 公地悲剧：凡好处归个人而成本由集体承担的地方就潜伏着公地悲剧。在小范围群体里，道德的制裁至今有效，因为人们相互认识，如果有人只考虑自己的好处，滥用公共利益，就会被发觉，并遭到最严厉的惩罚——失去名誉。但在一个匿名社会里道德就没那么管用了。解决方法有两个：1）私有化；2）加强管理。
1. 结果偏误：100万只猴子在股市投机，20年后有1只猴子每次都赚钱，媒体会阐述其“成功原理”。不要完全用结果判断决定，结果差并不意味着决定不对，反之亦然。
1. 选择的悖论：在无限选择的年代，适合自己的局部最优选择更好。
      1. 选择范围太大会导致无所适从
      1. 选择范围太大会导致更糟决定
      1. 选择范围太大会导致不满
1. 讨喜偏误：我们会觉得一个人讨喜，若此人 1）颜值高；2）和我们相似；3）喜欢我们。不要被一时感情冲昏头脑。
1. 禀赋效应：我们对自己拥有的东西估值更高。让我们放弃要比让我们囤积难。这解释了我们为什么会在房子里堆满废物，也说明了为什么邮票、手表或者艺术品收藏者很少交换出售藏品。禀赋效应不仅神话了我们已有的财产，甚至神话了可能会拥有的财产。在拍卖中有“赢家的诅咒”：拍卖的赢家反而是经济上的输家，因为他出价过高。......结论：勿过于执著于某物，理解来去无常。

  > <span style="color:blue">Hui: 这让我想起focusing illusion</span>

1. 奇迹：小概率事件可以发生，不要过度解释。
1. 团体迷思：一群智慧的人做出愚蠢的决定，因为每个人都误以为自己的意见是正确的共识，从而作出他们每个人在正常情况下都会拒绝的决定。这是从众心理的一种特殊情况。（Pig bay evation）
1. 忽视概率偏误：我们对一件事的强度做出反应而非概率，我们缺少对概率的直觉理解。（一定会遭受电击，和有50%／20%／10%／5%的概率会遭到电击，两种情况下受试者一样紧张。预期电击强度增大时，两组紧张感同时增大。概率降为0才会有不同。）我们不能区分理解风险。
1. 零风险偏误：我们只信任0风险。我们常愿意投资过多的钱，就为了彻底消除微小的剩余风险。（俄罗斯轮盘赌：共可装6发子弹，假设装有4发，发愿意付多少钱拿走2发？假设装有2发，你愿意付多少钱将这2发都拿走？）......结论：学会怀着“没有什么是绝对安全的”想法生活——无论你的积蓄，健康，婚姻，友谊。满足于至少有东西让你保持相对稳定并体验自身快乐。研究表明，无论是中百万彩票还是半身瘫痪都不会长期改变你的满意度。不管发生什么，快乐的人照样快乐，不快乐的人总是不快乐。
1. 稀少性谬误：物以稀为贵
1. 忽视基本概率：创业的成功率就是那么低，无论你多努力，多聪明，你都更可能失败。意识到基本概率。
1. 赌徒谬误：连续出现红球，下一个更可能是黑球么？注意是否是独立事件。现实生活中的事件大多数有相互联系。

   > <span style="color:blue">Hui:总觉得这个和均值回归有冲突啊</span>
  
1. 锚定效应（Anchor effect）

   > <span style="color:blue">Hui: 这个简直家喻户晓。之后在Predictable Irrational会讲到。</span>
       
1. 归纳法（induction）：generalize results from small sample.我们自欺欺人。很少生病的人觉得自己不会死。连续几个季度利润增长CEO觉得自己不可缺少。人类一直成功因此我们可以征服未来的挑战（只有那些幸存到现在的物种才能这么说。）**以我们存在的事实来说明将来我们也会存在，是一个严重的思维错误——估计是最严重的**。 
1. 损失规避：人们害怕失去某种东西的想法要比获得某种同等价值的东西的想法强烈。我们无法改变：恶比善更有影响力。我们对不利的东西反应要比对有利东西反应敏感。一张凶恶的脸要比一张友善的脸更容易引起我们注意。**恶行要比善行更永久地留存在我们的记忆里。当然也有例外：事关我们自己的时候。**
1. 社会性倦怠：责任扩散，个人效率无法直接看到，导致尸位素餐，群体效率下降（都指望别人嘛： ））。这是一种我们让自己亏欠所有人的欺骗形式。这一欺骗大多不是故意的，而是不知不觉的发生的。为什么不完全懈怠？因为0效率会引起注意——继而会带来后果，如被逐出群体或损坏名誉，我们能细腻地感觉到，懈怠到什么程度不会被看出来。出于同样的原因，团队有甘冒比个人更大风险的倾向。人们称这一效应为风险分摊。可以通过尽量彰显个人效率来缓和团队的弊病。
1. 指数增长
1. 赢家的诅咒：拍卖的赢家大多是事实上的输家。1）一种货物的真实价值是不确定的。出价方越多，报价过高的概率就越大。2）我们想排挤竞争对手。
1. 基本特征谬误：系统性地高估人的影响，在解释某些东西时低估情境因素。领导才能对经济成功的影响程度要远远小于普遍的经济形势和行业的影响力。在一个存在危机的行业里，首席执行官们常被撤换。.....极度关注他人源自我们过去的进化史，隶属于一个群体是生存所必需的，被排斥意味着死亡。繁殖、自卫和狩猎，大多是个体做不到的。我们需要别人协助。特立独行的人早就从基因池里消失了。因此我们才会这样过度地关注人。我们将90%的精力都用来关注人，只用10%的精力关注情境。不管戏剧多么让我们着迷，舞台上的人绝非孤立的，他们的表演离不开一个个情境。你若真想理解正在表演的戏剧，就请你不要只注重表演者，而是多关注他们的表演或舞蹈。
1. 错误归因
1. 光环效应
1. 替代途径：风险从来不是一眼就能看到的。因此，请你时刻考虑你有什么样的替代途径。比起你通过无惊险的平凡途径获得的成功，别拿通过冒险的替代途径获得的成功太当真。蒙田怎么说来着：“我的生命充满不幸——这些不幸大多没有发生。”
1. 预测错觉：什么可以预测，什么不可以预测？一件事情越复杂，时间跨度越长，其未来的发展变化就越多。
1. 关联谬误：大脑的系统1会自动把线索连起来编故事。
1. 框架效应：同样的内容，换个不同的说法，效果不同。
1. 行动偏误：为什么不行动光等待是中痛苦？源自远古基因。在一个狩猎采野果的环境中，行动比思考价值大得多。在古时，闪电式反应关乎生死存亡，思考则可能会致命。如果情况不明，不要采取任何行动，直到你能更好地分析形势，你要克制自己。
1. 不作为偏误：其出现在无论放弃还是行动都会带来损害地地方。在这种情况下大多数人都会选择放弃，因为这样引起地损害主观看来更无害。“如果你不是答案地一部分，就是问题地一部分[1968欧洲学生运动口号]”
1. 自利偏误：成功归于自己，失败归于外因。
1. 享乐适应：
      1. 请避免很长时间也不会习惯地负面效应，如交通，噪音，慢性疲劳等。
      1. 对物质的东西只期待短期效果，例如汽车，房屋，分红等。
      1. 持续正面效应主要与你如何利用时间有关。设法让自己得到尽可能多的自由时间和自主权。请你做最爱做的事情——哪怕你要付出部分收入。请为友谊投资。
1. 自我选择偏误：当我们本身是样品的一部分时，我们必须注意，不要掉进一种以自我选择偏误著称的思维错误陷阱中。
1. 联想偏误：影响我们决定的质量。我们倾向于不喜欢送坏消息的人（Shoot the Messenger Syndrome）
1. 新手的运气：如果你长期比其他人成功，你可以认为自己的才华可能起作用，但绝不能过于自信、自满。参与的人越多，出于纯粹运气长期成功的概率越大，也许你就是这个某人。
1. 认知失调(Cognitive Dissonance)：酸狐狸
1. 双曲贴现：一个决定离现在越近，我们的“情感利息”就越多。这是及时享乐对我们的控制，我们过去动物性的残留。动物不愿意为在将来得到更多的奖励而放弃今天的奖励。

> 在群体里容易按照他人的想法生活，在孤独中容易按照自己的想法生活，但值得记住的只是那些在群体中保持独立的人。—— 爱默生


## Thinking Fast and Slow [Daniel Kahneman]

> <span style="color:blue">Hui: 作者Daniel Kahneman因为前景理论（prospect theory）获得诺贝尔奖，主要研究人们在不确定的情况下做出决策。他是研究之前推荐的这几本书中提到的所有认知偏差的鼻祖。对人类决策感兴趣的小伙伴不能不读这本书。</span>

belladona: 一种使人瞳孔变大的物质

这是Dan Kahneman关于他对判断和决策研究结果的书。

### Ch1: 一张愤怒的脸和一道乘法题

系统1: 毫不费力的直觉性思考，如识别一张愤怒的脸
系统2: 需要自我控制，如做乘法题目（自我控制的典型实验是延迟性满足，小孩和糖果的实验）

> 系统1是自主运行的，我们无法随意使其停止，因此认知错觉无法避免。时刻启动系统2保持警醒并不是一种好的思维方式，会让我们的生活非常枯燥乏味，也不现实。最好的方法是学会妥协：用系统1进行日常抉择，区别常会出现重大错误的情境，在风险很高的时候，尽力避免这些错误。

> <span style="color:blue">Hui: 自我控制需要能量，系统2使用过度会消耗过多的能量而无法自控。区分在什么事情上使用系统2非常重要。</span>

### Ch2: 电影的主角与配角

在实际生活中，系统1是主角，系统2是配角。大部分情况下是由系统1接管我们的思维，系统2默认系统1的决策，在系统1遇到麻烦系统2才会出面解决。系统2是很懒的，奉行最省力原则——能不接管思维就不接管思维。当它接管思维的时候，人的注意力会集中，瞳孔放大，需要努力才能够维持注意力的集中。

### Ch3: 惰性思维与延迟满足的矛盾

- 自我控制和仔细思考会抢夺努力的有限预算。大多数人保持连贯的思维或时不时积极思考都需要自我控制力。
- 心流：一种将大脑注意力毫不费力集中起来的状态，这种状态可以使人忘却时间的概念，忘掉自己，也忘掉自身问题。心流状态下，集中注意力关注吸引人的事并不要求自我控制。
- 人若既有认知任务在手，又同时受到诱惑的影响，就容易屈从于诱惑，更有可能作出自私的选择，会用带有性别歧视的字眼，并在社交场合作出肤浅的评判。喝几杯酒，或者一夜没睡会产生同样的结果。过度关注自己完成一项任务的结果，就会给其短时记忆增加毫无意义的思想负担，进而影响其整体表现。
- Ego depletion: 如果你必须强迫自己去做某件事，而此时这件事又面临一个新的挑战，你就会很不情愿或是根本无法自我控制。如果有强大动力抑制Ego depletion，是可以做到的。
- 神经系统消耗的葡萄糖比身体其他部位消耗的都要多。
- 聪明不仅是指推理能力，也指在记忆中搜寻相关信息和在必要时调动注意力的能力。



## Predictable Irrational

- Goal: what makes you and people around you tick?

behavior economics, judgment and decision making (JDM)
Generalized Axiom of Revealed Preference (GARF)

We are irrational
Our irrationality is predictable

### The fallacy of supply and demand
James Assael, Salvador Assael (peark king, James' son), black pearl from black-lipped oysters, put them in the window of Harry Winston's store on Fifth Avenue, Tahitian black pearls glowed

> Mark Twain in Tom Sawyer: "Tom had discovered a great law of human action, namely, that in order to make a man covet a thing, it is only necessary to make the thing difficult to attain."

- Anchor effect: last two digits of social security number, how much would you pay for the product?  
      - Anchor effect witll exist for long time even we set new anchor later, we will still be affected by the origional anchor. (anchors in the experiment: 10 v.s. 90, 50, 90 v.s.10 )  
      - Assael anchored his pearls to the finest gems in the world and the prices followed forever

> Mark Twain: 英国一些阔绰的绅士夏季每天驾着四套马车沿大路跑上二三十英里,因为这样做可以花掉不少钱;可如果付钱雇他们驾车载客,消遣变成了 工作,他们是不愿干的。

我们所做的许多决定，不论是不经意的，还是经过深思熟虑的，锚都在其中起作用......你做一切事情都应该进行自我训练，置疑自己一再重复的行为。我们还应该特别关注我们的首次决定，它日后能形成一长串的其它决定（比如衣服、食品等）。  

传统经济学假定产品的市场价格取决于两股力量的平衡：供给和需求。......
1. 但是如我们的实验所证明，消费者的购买意愿可以很容易地被操纵，也就是说消费者实际上并不能很好地把握自己的偏好以及他们愿意为不同商品和体验付出的价格。
1. 传统经济学架构假设供需独立，上面提到的锚定效应暗示它们是相互依存的。在现实世界中，锚来自厂家的建议零售价格、广告价格、促销、产品推荐等因素——所有这一切都来自供给方。

我料想,如果人们记得住从前的价格并且注意到它的涨价幅度,价格变化就会对需求产生巨大影响;如果人们记不住过去的价格,价格的变化对需求的影响,即使有也会很小。换言之,我们对价格变化的敏感度事实上很大程度上可能是两种因素共同 作用的结果—— **1) 我们对过去价格的记忆; 2) 我们想与过去决定保持一致的欲望。而根本不是我们的真正偏好或需求大小的反映。**

### The cost of free
   - 免费使人拿一大堆不要的东西？为什么？多数交易都有有利的一面和不利的一面,但免费使我们忘记了不 利的一面。免费给我们造成一种情绪冲动,让我们误认为免费物品大大高于它的真正价值。为什么?我认为是由于人类本能地惧怕损失。免费的真正诱惑力是与这种惧怕心理联系在一 起的。我们选择某一免费的物品不会有显而易见的损失。但是假如我们选择的物品是不免费 的,那就有会有风险,可能做出错误决定,可能蒙受损失。于是,如果让我们选择,我们就尽量朝免费的方向去找。
  - 我们同时生活在两个不同的世界里——其中一个世界由社会规范主导,另一个则由市场规范来制定法则。
  - 日托所罚金案例： 一旦社会规范与市场规范发生碰撞,社会规范就会退出。换言之,社会规范很难重建。一旦这朵盛开的玫瑰从枝头落下——一旦社会规范被市 场规范打败——它很难发挥任何效力。
  - 强调雇佣关系中社会性的一面所能营造出的亲善氛围。社会规范(例如共同创业的兴奋)强于市场规范(例如薪金随晋升而增加)时,员工能为公司(特 别是那些刚起步的公司)创造的价值的确令人瞩目。如果企业开始从社会规范角度思考,实际上,它们会认识到社会规范可以建立忠诚,更重要的是,它使人们自我发展,达到如今企业的要求:实行弹性工作制,关心公司,并且积 极参与公司事务。这正是社会性关系带来的。......多一些社会规范,少一些市场规范,我们的生活会变得更惬意,更有创造力,更充实,而且更有乐趣。
  
> <span style="color:blue">Hui: 这和《经济学通识》中提倡的让市场决定一切的观点相反。</span>

### Procrastination and Self-control
- Procrastination:无法延迟满足导致的结果
- Experiment: 
     - 12 weeks, require 3 papers
     - Plan 1: Set deadline for the 3 papers yourself by the end of this week. If you miss the deadline, you will get 1% off your final score for each day you miss.
     - Plan 2: everyone will have the same deadline which is the end of the semester
     - Plan 3: The professor set deadlines to be week4, week8 and week12
     - Result: Plan3 > Plan1 > Plan2
     
### The Price of Proprietorship

> <span style="color:blue">Hui: 这就是之间《清醒思考的艺术》中讲的禀赋效应：我们对自己拥有的东西估值更高</span>

- 为什么多种选择使我们迷失主要目标？
     - 例子：项羽破釜沉舟，饿死在草堆间的驴
     - 知道这些可预测的非理性并不保证你做出理性的选择。依旧在各种选择中纠结。
- 为什么期待什么就会得到什么?
- 可口可乐凭什么战胜了百事可乐?
- 为什么球迷不承认自己拥护的球队犯规?为什么会产生这么多暴力冲突?是历史、民族、政治方面的原因,还是 我们本性中就存在某些非理性的东西,鼓励我们对抗,引导我们对同一事件,根据自己的立 场而采取完全不同的观察角度呢?

- 为什么加了醋的啤酒贴上“特酿”标签就会大受欢迎?人们的预期是否影响他们对后来 事物的观点——说得更具体一点,酒吧的客人对某种啤酒的预期是否能形成他们对啤酒口 味的评判标准。

预期能够形成成见，成见为我们理解周围环境提供了捷径，但成见给我们提供了对某一群体的特定预期，它也可能对我们的认识与行为有不利影响。

### Magic Price

主要讲了安慰的作用。价格贵，就以为是好东西，这和设定我们的预期有关。

### Good or Evil

- 有关《圣经》十 诫的实验给我印象最深的是那些十条中只能记得一两条的学生和那些十条差不多全记得的 都会受到影响。这就是说鼓励人们诚实的并不是十诫的条文本身,而是出于对某种道德准则的深思。

- 英文“职业”一词来源于拉丁文“professus”,意思是“为公众认可”。高级职业很久 以前起源于宗教后来又传播、扩大到了医学和法律方面。据说,掌握了秘不外传的高深知识 的人,不仅仅垄断了该知识的应用,同时还负有明智地、诚实地使用该种知识的责任。

- 我们擅长于把自己细微的不诚实想法和做法合理化,所以我们 _**通常很难清楚地确定非金钱事物对作弊的影响**_。
- 只要有机会,人们就会作弊。但奇怪的是我们多数人对此并无察觉。当偷取的是非货币，无形的物品时，不会有道德负担，比如网络盗窃通话时间。

- 点酒顺序对点的酒有影响，大家都想点和之前人不同的。那些注重表现自己独特性的人们更可能点别人没点过的酒,以此来证明自己确实与众不同。人们选择食品和饮料时好像有两个目标:或者给自己带来最大享受,或者在朋友心目中炫耀自己某 些正面的人格特质。 _**说到底,人们,特别是那些独特需求旺盛的人们,可能牺牲个人需求去换取名声需求**_。 在标新立异不被视为正面人格特质的文化背景下,人们在大庭广众之下点菜点酒时,有可能表现与群体的归属感,着意刻画与别人选择一致的 印象。我们在香港做的实验证明,事实果真如此。在香港,人们常常也不喜欢在公开场合当众点的酒菜,而是喜欢自己私下点的。但是这些参与者点酒点菜时,都跟着群体中的头一个照葫芦画瓢——这样他们就同样犯了使他们后悔的错误。

### Free Lunch: an behavior economics explanation

- 传统经济学假定我们都是理性的——我们了解与决定一切有关的信息,我们能够计算所面 临的各种选择的价值,我们能够正确权衡每一种选择中错综复杂的因素,我们对事物的认知 不会遇到阻碍。

- 免费午餐的基本概念就在这里——让有关各方都能获益,做到“共赢”。要注意的是, 这些免费午餐并不一定是没有成本(使用自我控制信用卡和实施“明天多储蓄”不可避免牵 涉到成本)。但只要这些机制换来的利益大于成本,我们应该把它们当做免费午餐——给各 方都带来净效益的机制。

### Summary
1. 我们的知觉和决策环境是通过眼、耳、味觉和触觉, 还有主宰一切思想的大脑,经过过滤才形成的。等到我们对信息作了理解和消化,它已经不 一定是现实的真实反映了。相反,它只是我们对现实的诠释,而它就是我们形成决策的基础。 从本质上来说,我们被自然赋予的工具所限制,我们决策的方式又受限于这些工具的质量与 精确程度。
1. 尽管非理性司空见惯,但并不是说我们都不可救药了。一旦我们明 白了自己的错误决定会发生在什么时间,起源自什么地方,就可以提高警惕,强制自己从不 同角度、用不同方式重新考虑这些决定,或者用科技手段来克服与生俱来的缺点。企业决策 者们也可以在这些方面改变他们的思维方式,考虑怎样制定政策,设计产品,创造免费午餐。
 
## Quirkology [怪诞心理学，Richard Wiseman]

本书是关于日常生活中稀奇古怪的事情的研究，揭示了不同层面的秘密心理，包括欺骗、决策、自私和迷信等。

### Ch1 时间心理学

## The Art of War [孙子兵法, Sun Tzu]
## 幸福之路 [罗素]
## Bushido [武士道, Jnazo Nitobe]                        
## 博伽梵歌 [印度经典]                               

## 南怀瑾谈心兵难防 [南怀瑾]

- 所谓“喜怒哀乐之未发谓之中”，是指“情绪”没有发动的境界。
- “当断不断，反受其乱。”任何一个人，随时在心中脑里，有理性和情绪上的斗争，随时自己和自己在争论，打官司。除了能“自净其意”以外，“自讼”是随生命并存，永无停止的。所以道家的庄子，也形容这种“心、意、识”自讼的状态，叫做“新兵”，就是说平常的人们意识心中，随时都在内战。如果心兵不动，自心的天下就太平了。人们假如能够学养到自净其意，不生妄念，心兵永兮，更不自讼了，那才真是“知本”。
- 道家的老祖宗老子便说：“吾所以有大患者，为吾有身；及吾无身，吾有何患。”...“百年三万六千日，不在愁中即病中。”
- 你真能做到使意识，意念返还到明诚，明净的境界，那才叫做真正的“自谦”，这完全是靠自己的反观省察，才能得到的境界。谦，并不是消极的退缩，它是崇高的平实。谦，在《易经》是一个卦名，叫做“地山谦”。
- 八八六十四卦，没有一卦是大吉大利，都是半凶半吉，或者全凶，或是小吉，只有谦卦才是平平吉吉。古人有一副对联：“海到无边天作岸，山登绝顶我为峰。”
- **所谓“真正的静”，要有高度的修养，如前所述，一面批改公文，一面听取报告，处理急务，日理万机的情形下而心境始终是宁静的。**
- 它还没有来，何必去怕？它来了，怕也没用，又何必去怕？现在还乐得享受，清静一点。
- “人心惟危”，人的思想是非常危险的。
- 佛学对于本性，比方成大海。我们现在的思想——包括了感觉，知觉，是海面上的浪头。一个浪头一个浪头过去了，不会永恒存在的。佛学在这一方面就告诉人们，这是“空”的。宇宙间一切现象，包括了人类心理上生命的现象，一切都会过去的，没有一个停留着。这在佛学上有个名词叫“无常”。...就好比一个浪头过去，又一个浪头过去一样。虽然这个浪头是无常的，断续的，但是，有一点要注意，能起这个浪头的，是整个的海水。等到风平浪静，海水还是海水，没有变。这一切变化中间，又一个不变的。
- 《易经》告诉我们，变是对立的变，任何一件事，都是相对立的，有正面必有反面，有好必有坏，你说对的，同时也就产生了不对的。一切都是相对的，在这个相对的中间，有一个中和的道理。
- 所以我们判断一个人的好坏，不要随便被外在的态度左右，尽量要客观。外形礼貌固然重要，如果内在没有礼的精神，碰到人一味地礼貌则很辛苦，很不安详。
- 老子说“上善若水”。一个人如要效法自然之道的无私善行，便要做到如水一样至柔之中的至刚、至净、能容、能大的胸襟和器度。
- 明代的陈眉公说：“如何是独乐乐？曰：无事此静坐，一日是两日。如何是与人乐乐？曰：与君一席话，胜读十年书。如何是众乐乐？曰：此中空洞原无物，何止客卿数百人。”
- **小富由勤，大富由命。**
- 子曰：关雎，乐而不谣，哀而不伤。
- 性的本质并不是罪恶，饮食男女，人之大欲有焉。
- 贤贤易色： 我们看原文“贤贤易色”，两个贤字，第一个贤字作动词用，因为中国文字有时候是假借的。第二个贤字是名词，指贤人--学问修养好的人。易，改变。在春秋的时候，易的改变暗含着持续的，不间断的改变。色：态度，对人对事对社会的态度。贤贤易色换个说法就是：见贤思齐。
－ 司马迁所谓“君子疾没世而名不称焉”。“天下熙熙，皆为利来，天下攘攘，皆为利往。”“名利本为浮世重，古今能有几人抛”。
- 老子：“揣而棁[zhuō]之，不可长保。金玉满堂，莫之能守。富贵而骄，自遗其咎。”“矢上加尖”。

> 如果已有聪慧而不知谦虚涵融，已有权势而不知肥遁退让，已有财富而不知适可而止，最后终归不能长保而自取毁灭。

-  学了《易经》做人做事，不要过头，过头就是亢；大家都是平等的，只直到进不知道退，只知道存不知道亡，只知道得不知道失，就是亢；人很容易犯这个毛病，知道进退存亡得失得关键，就是圣人。

## 南怀瑾选集（第二卷） [南怀瑾]
## 老子他说 [南怀瑾]
## 南怀瑾选集第三卷易经杂说易经系传别讲 [南怀瑾]
##  庄子諵譁.上 [南怀瑾]
## An Insight of Chung-yung [中庸洞见,Tu Wei-ming]                     
## 欲望之源                                 
## 论雄辩 [François Fénelon]
## 亡灵对话录 [François Fénelon]
## 天使的传言                                 
## 百喻经(一部古老的佛教寓言经典)                                 
## 图解心理学                                 
## Science of Logic [逻辑学, Hegel]                           
## Book Of Changes I [我读《易经》(上)]                                
## Confucius Said [Tom Te-wu Ma]
## 漫画中国思想（蔡志忠漫画经典精选）                                 
## 中国佛学经典文库——禅诗精选（高僧卷）                                 
## 北大哲学门经典文萃——冯友兰选集 [冯友兰]
## 谢尔顿作品集——众神的风车 [谢尔顿]
## 了凡四训 [袁了凡]
## 欲望心理学  

> <span style="color:blue">Hui: 作者休.麦凯。这本书是一篇篇文章的集结，试图解读驱使人行为背后的欲望。书中探讨了10种欲望，它们在本质上并无好坏之分，而只是人性中的一部分。作者在前言中说：“我们所有人都会受到一连串诸如欲望、激情、期许和需求的驱使，它们对谁而言都是很难权衡的，更不用说控制它们了。我们需要太多不同的东西，甚至有时想同时占有它们，这也就是我们经常会感到纠结的原因。” 欲望激励我们前进，但当欲望得不到满足时，很可能会产生恶意的想法。理解学习人性的欲望，有助于我们更好的控制它们，选择生活而不是被生活选择。</span>

### 涂鸦、发表言论、恶霸行为的目的——渴望重视的心理



## 社会心理学                                 
## Social Physics [智慧社会, Pentland, Alex]
## Going Solo: The Extraordinary Rise and Surprising Appeal of Living Alone [Klinenberg, Eric]
## Antifragile [反脆弱, Taleb, Nassim Nicholas]       
## Black Swan [黑天鹅, Taleb, Nassim Nicholas]  

> Hui: 我觉得对这本书的评价和你从事的职业很有关系。我的主要工作是分析，其中很大一部分是预测，所以我特别喜欢Nassim的作品。他主要是研究生活中的随机性，什么事件可以预测，什么事件不可预测。如果不是对随机性特别感兴趣的人会觉得他的书有些无厘头。他的书帮助你思考从过去、已知和已观察到的东西中学习的困难。他指出了一个我们很容易犯的逻辑错误，我们很容易认为无证据拒绝某零假设意味着零假设是正确的。这也是传统统计推断中存在的问题。学了这么多年统计，不仅仅对p值的意义，我对整个统计假设检验的意义是什么也有疑问，除了发论文和得到FDA批准以外到底还能干什么？

### Prologue

- The inability to predict outliers implies the inability to predict the course of history. 

- I disagree with the followers of Marx and Adam Smith: the reason free markets work is because they allow people to be lucky, thanks to aggressive trial and error, not by giving rewards or “incentives” for skill.

> <span style="color:blue">Hui: what doesn’t allow people to be lucky?</span>

- We do not spontaneously learn that we don’t learn what we don’t learn.

> <span style="color:blue">Hui: Similar as “we don’t know that we don’t know”.</span> 

- We humans are not just a superficial race (this may be curable to some extent); we are a very unfair one.

- Platonicity is what makes us think that we understand more than we actually do. 

> <span style="color:blue">Hui: what you know << what you think you know (I agree). Even I so clearly know that I AM STUPID, still what I know << what I think I know......I wish I could learn more. The feeling of ignorance bothered me so much but now I consider it as my life-time friend. Because I don’t see any hope I can not being ignorant, I think it is a better idea just be friend with it. My goal now change to be less ignorant today than yesterday. </span>

### The apprenticeship of an empirical skeptic

apprenticeship /ə'prɛntɪʃɪp /

- The human mind suffers from 3 ailments as it comes into contact with history (_triplet of opacity_):
    1. the illusion of understanding, or how everyone thinks he knows what is going on in a world that is more complicated (or random) than they realize [了解世界的幻觉]
    
         > <span style="color:blue">Hui: 我们以为我们生活的世界比它实际上更加可理解，可解释，可预测。</span>
         
    1. the retrospective distortion, or how we can assess matters only after the fact, as if they were in a rearview mirror (history seems clearer and more organized in history books than in empirical reality) [马后炮偏差]
    
         > <span style="color:blue">Hui: 我们太容易马后炮了。很多发生过的事情尽管当时感觉很疯狂，但是回过头看就没有那么疯狂。我们总能够将历史事件通过某种因果关系串联起来。作者认为这种事后合理性在表面上降低了事件的稀有性，并使事件看上去具有可理解性。之后作者提出：“历史不会爬行，只会跳跃[History does not crawl, it jumps]”。 作者认为我们的头脑是超强解释机器，介乎可以从任何事物中分析出道理，还不愿意接受不可预测的事实。“Our minds are wonderful explanation machines, capable of making sense out of almost anything, capable of mounting explanations for all manner of phenomena, and generally incapable of accepting the idea of unpredictability”</span>
         
    1. the overvaluation of factual information and the handicap of authoritative and learned people, particularly when they create categories—when they “Platonify” [高估事实实际信息的价值]
    

>  <span style="color:blue"> Hui: The retrospective distortion reminds me a quote from Mark Twain: “Get your facts first, then you can distort them as you please." : )</span>

>  <span style="color:blue">Hui: 我们倾向于简化事物，难以避免叙述谬误，这点我同意。但这无法改变？这是一个物种的局限。因为我们的脑子能够处理的信息非常有限。假设我们接受这种现状，那么下一个问题就是，该怎么办？我目前的答案是：首先需要认识到这一点。不可避免无知是一回事，对自己无知的无知是另外一回事。我们需要意识到很多事情我们不知道，这听起来好像没有任何新意，谁不知道世界很大未知很多，知道是一回事，理解是另外一回事。很多概念看上去相似，实际上有本质的区别，这些区别的影响很大，但却难以察觉，理解它们需要时间，努力和勇气。认识到这一点之后，我们需要最大限度的探明有哪些事情是我们不知道，哪些我们无法估计，哪些我们无法控制，这样我们对自己的叙述在多大程度上简化了真相会有更好的了解，虽然我们永远无法完美估计自己的无知，但我们可以不断的加深自己的认识。这会帮助我们避免很多因为过于天真的认为简化版的故事就是事实而导致的灾难。  
从另外一个角度，在现实生活中我们需要做出决策，我们需要简化的易于理解的充分照顾人类愚蠢这一事实的故事，否则很多事情无法进行，生活将举步维艰。该怎么办呢？守住一个底线，尽力确保这个故事的传播带来的负面影响不会超过正面影响。这也是一件模糊的事情，但我相信，你对未知探索的越深入，就能够与好的守住这个底线。  
这个世界一如既往的充满了悖论，我总是在想有没有可能找到复杂表象背后的几个基本点？类似圣经中指出的人类的原罪一样。这几个原罪可以解释很多人类行为。从人类行为背后的的欲望来理解行为就是一个非常好的简化方式。但是当这些行为开始相互影响时，随机性开始火箭上升。事情开始变得非常复杂，不可控，难以预测。该怎么办？孜孜不倦的理解自己的无知，达人事，听天命。  
如果你在他的位置上会是什么感觉？会喜欢那样的生活么？目前看来，答案是否定的。回到那个老旧的问题：我要什么？这个问题有的时候真让我恶心，因为我一直难以回答，而它又貌似无比重要。无论被恶心多久，我还是要试图去回答这个问题，如果我一生都不知道自己要什么，那也是个答案，答案就是其实我没有什么确定想要的，虽然有些悲哀，但谁保证一定是喜剧呢？答案当然可以说是想要神的肯定。这个答案看似具体，实则模糊的不能称之为答案。如何让神肯定？这是一个很难回答的问题。回到现实生活当中，一切都需要具体细化到每天的生活，分分秒秒的时候，在尘世中想要坚持的信仰，最后还得落实到每个行动中，体现在你如何使用自己的生命。  
那回到生活上。我知道我不喜欢那样的生活，很好，知道自己不喜欢什么也是在认识自己上的进步。那自己到底想要什么样的生活呢？我喜欢的是数学、统计和分析本身么？不太像。我喜欢的是自已之前认为的通过工作能给周围世界带来价值么？再仔细想想，也不完全。因为价值这个东西本身就是模糊的。你认为有价值的事情实际上价值是多少本就无法定义，所以这是一个自我满足的伪答案。现在我能想到的最好的答案实际上是好奇心，是为了缓解对自身无知的恐惧，为了更好的回答这样一个问题：“What is real?”数据分析是个人能够了解世界的一种最好的方式，这种技能使我可以尽量自己收集一手信息，通过分析判断，更加客观的了解世界真实的样子。而不是盲目的，甚至被迫的接受他人的观点。我很感激计算机技术的发展和网络时代的来临，使得很多数据的收集成为可能，这增加了我们了解世界的能力，给了我一种自由，精神上的自由。但同时这又挖了一个更大的坑：信息太多了太多了，良莠不齐，怎么办？我的人生好像永远没有拨开云雾见青天的那一天，充满着疑问。只是那又如何？我无法摆脱这样的现状，但我可以和这些疑问和平共处，而我想要的，是不断解开一个又一个的疑问，尽管过程中会产生新的问题。这或许就是信仰，即便无法具体的定义神，即便无法理智上彻底证明神的存在，但还是相信那个存在，相信存在有着某种意义，相信爱；还是能够坚定不移的充满希望的走下去，通过回答一个又一个问题，更加深入的了解自己，理解世界，好好做人。</span>

- History and societies do not crawl. They make jumps. They go from fracture to fracture, with a few vibrations in between…These kinds of discontinuities in the chronology of events did not make the historian’s profession too easy: the studious examination of the past in the greatest of detail does not teach you much about the mind of History; it only gives you the illusion of understanding it….We are just a great machine for looking backward, and that humans are great at self-delusion. 

> <span style="color:blue">Hui:  作者指出历史不是连续的而是跳跃的，而人类的解释性思维将这些事件自行用因果关系连接起来，造成了理解历史的幻觉。作者使用了黎凡特（Levant）基督教传播的例子。罗马编年史学家（chronicler）对基督教在这一区域的传播的历史记录有断层。</span>

- Of the millions of small facts that prevail before an event occurs, only a few will turn out to be relevant later to your understanding of what happened. Because your memory is limited and filtered, you will be inclined to remember those data that subsequently match the facts [在一个历史事件发生之前存在无数个事实，其中只有很少一部分会在后来你对历史事件的理解中有帮助。因为你的记忆有限且是被过滤的，所以你会倾向于记住那些事后看来与事实相符的信息。]


## 反直觉思考                                 
## 直面内心的恐惧  

> <span style="color:blue">Hui: 作者弗里兹.李曼通过他行医多年的经历，归纳出四种恐惧的原型：害怕把自己交出去（分裂），害怕做自己（忧郁），害怕改变（强迫），害怕既定规律（歇斯底里）。大部分人都是四种原型的混合，极度偏向任何一种都是病态的。因此我们可能经历过每种基本的恐惧，但是没有哪一个在我们身上独霸一方，因此我们能够克服这些恐惧，每战胜一次恐惧，我们就淬炼的更加坚韧。了解自己心中不安和恐惧的来源，或许能够帮助我们更好的克服它们取得心智的成长。</span>

## Predictably Irrational2 [Ariely, Dan]
## 三十六计                                 
## 心理学与生活  

## Outliers [异类]   

- 在斯腾伯格看来,“为了达到最佳效果,知道自己应该在什么时候,应该怎样和他人说出自己应该说的话”,是实用智商的一个方面。 这更像是一个程序上的概念:它指的是你应该怎样去做一件事情,和你是否清楚自己为什么要这样做或者能否提供这种行为的合理解释并无必然联系。它的本质是实践性的:它不是解 释自我的能力,它是一种让你正确认识自身处境,并且达到自己目的的能力。并且,更为关键的是,它是一种有别于IQ测试中,一个人的分析能力之外的智商。在运用这个术语的时 候,一个人的一般智商和实用智商常常是“两两不相交”的:一种智商的存在并不意味着另一种智商就必定存在。你也许拥有很高的分析推理智商,但实用智商却可能比较低;或者你 拥有高的实用智商,但分析推理智商却偏低;或者——就像罗伯特·奥本海默这样的幸运儿 一样——你两个方面的智商都很高。

- 拉里奥把中产阶层父母的教育方式称为“协同培养”,其目的是积极地“培养并评估一个孩子的才能、观念和技能”。相反,穷人们遵循的是“自然成长”的策略,他们虽然认为自己的责任是照看孩子,但是应该让孩子自由自在地发育成长。

- 我一直认为一个人越是接近事物的本质,他就越是生活得更好。

> <span style="color:blue">Hui: 生活的本质是什么？</span>

- 智慧是一码事,精通世故又是一码事,较低的智力却可能精通世故。成就事情少不了智商之外的其他能力。

## 叙事疗法                                 
## 正义之心                                 
## 做一名优秀的心理咨询师                                 
## 亲密的陌生人                                 
## 洗脑术：怎样有逻辑地说服他人                                 
## 天才在左疯子在右 [高铭]
## The Crowd [乌合之众, Gustave Le Bon]                
## Status Anxiety [身份的焦虑, Alain de Botton]

> <span style="color:blue">Hui: 作者阿兰.德波顿并没有从学术的角度（他也不是个心理学家），而是从历史，文化艺术的角度分析这种焦虑的由来，以及可能的缓解途径。我们为什么需要他人的认同？从什么时候起有“势利”这个词？哲学、艺术、政治和宗教如何帮助我们舒缓这种焦虑。我个人认为作者并没有批判这种焦虑，而是避开了道德判断，就事论事的讨论身份的焦虑。</span>

## Being Mortal 

> <span style="color:blue">Hui: 作者Atul Gawande是个医生，我在这本书中第一次知道美国有专门的“临终关怀”机构。我们总想着怎么好好的活着，之前提到的《乐观的偏见》的作者说，如果没有乐观，展望未来的能力就会毁灭一切。因为我们很早就知道最后的结局一定是死亡。可是我们大多数人都会自动屏蔽在这个充满不确定的世界中唯一确定的事实。随着科技、医疗的发展，我们越来越笃信人类的力量，我们开始有这样的幻觉：一切事物都是可以解决的，可以改变的。这本书让人正视而非逃避这个不可改变的结局，告诉我们尽己所能好好活到最后一刻。更重要的事，作者提出我们在努力发展医学技术延长人类生命的同时，也要花精力帮助接近生命终点的人更好的度过最后的旅程，平静的离开人世。并不是所有人都希望通过各种医疗器械维持活着的状态，在生命的末尾的人有权说我不需要这些医疗监控仅仅为了延长自己的生命，我想要离开病床，回到自己的家中，像平常一样吃喜欢的食物，看想看的书，度过最后的日子。紧紧抓住生命没有错，选择在何时放手也没有错。请being mortal，因为这就是我们原本的样子。</span>

## PSY:心理操纵术 
### Ch 1 赢家不会告诉你的
- 保证自己成功的工具并不是执行力，而是明智的态度，冷静的判断和别具一格的思维
- 把你看到的人变成“你的人”，让更多的人想成为“你的人”， 这就是优秀领导者的魅力
- “成功可以复制”是谎言
- 表演的是狗熊，收钱的是驯兽师。成为“善舞的狗熊”是一个悲剧的目标
- 黑色人种为何散漫，漠视规则，难以形成高度的组织和纪律性？
- 白人基因有哪些与众不同的优点，又有哪些明显弱于东亚黄色人种的缺陷，从而导致了基督教文明与儒家文明的区别？
- 基因在很大程度上决定一个人的抗洗脑能力有致命影响。相较而言，华人总是很难被洗脑，他们既依赖权威，同时又不相信权力，也从不迷信鬼神的力量，并对任何单一和极端的“信仰”敬而远之。

   > <span style="color:blue">Hui: I totally can't buy this point......</span>

- 金钱总是在底层群体的手中进进出出，而永远在上层少数人的口袋里驻扎。富人的智慧：
      1. 他们不相信任何已经成功的人，从不迷信和追随某种经验。
      1. 从不制定宏观计划，而是注重于沿着趋势去推动事情。
      1. 他们深知金钱的用途，在滚雪球的过程中，懂得集中力量、聚成一团和重点使用的价值，不会将钱分散开来，而是能够抓住孤注一掷的时机。
- 洗脑金字塔： 1）洗脑源；2）传教士；3）中产；4）洗脑受体。

  > <span style="color:blue">Hui: 信息!= 真实信息  <----- 阶层，信息源，目的，判断力</span>

- 整部人类历史的发展背后，这一洗脑原则始终被牢固地贯彻下来，每一种文明都是如此，这就是世界各地优秀文化思想全部诞生在公元前，之后就一直裹足不前的原因。

  > <span style="color:blue">Hui: “各地优秀文化思想都诞生在公元前”这个观点有趣，仔细想想还真是那么一回事......>_< </span>

- 一个人只有站得高才能看得远，与他是否足够努力并没有必然关系。时间未必可以换来金钱。

> <span style="color:blue">Hui: 上层能够获取-----> (信息，资源，人脉)------>通过资本运作致富</span>

- 专注于提升自己的生活而不是去过量入为出的日子。
- 赢家法则 （Hui: 看到这样的标题感觉是传销，之前都说了成功不可复制不是么？怎么又来这么多法则？）
     - **在改变规则前遵循规则，重要的是前者**
     - 不要重复任何一件事情，即使是必要的（Hui: 太武断了）
     - **主动收集信息，尽可能去的一手资料，而非经由他人** （Hui: 有时间精力是该尽量要一手资料的）
     - **简练，直接，命中要害**
     - 结盟而非敌对
     - 看到问题是开始，解决问题是目的
     - 善于谈判，和每个人保持互相理解的心态
     - **如果一开始就看到的方案，自动跨越所有步骤**

- 弱者（没有精气神，不敢竞争，羞于展示才华）  
强者（耐心，恒心，勇气）
- 人们进行判断的原则常带有浓厚主观色彩

### Ch2 苹果的滋味
- 任何行为和思维，通过不断重复都会得到加强，并最终成为本能。
- 每件事情都有联系，把它们联系起来，就成了一张符合逻辑的大网
- 打造一个让人深度信任的平台环境，对方深信在你这儿他可以赢（Hui: 如何做？）


