# Society and Culture  

## Much Depends on Dinner [Margaret Visser]

### Introduction
- We prefer, as De Quincey's essay says, "to throw the grace of intellectual enjoyment over an animal necessity." （正如De Quincey在文章中说的，我们喜欢“用优雅的精神享受来掩盖动物性的需要”。）
- Again, we should be aware that our meal is almost totally **female in connotation**. _Corn_ is the American Indian "mother and nourisher"; _chicken_ (pale meat, no red blood, and little fat in evidence) is for us a typically "female" choice; _rice_, a delicate grain-----especially when it is "fluffy", as we like it-----white like chicken, and in its **mythical origins** a girl-child; _lettuce_ is light and unfattening, but also cold, milky, and female; _lemons_ nippled, _olive oil_ virgin, _ice cream_ cold milky, and served in definitely womanly, rounded shapes; _salt_ is the on exception, but even it is neuter and not masculine; _butter_ from cream is again female.

### Corn
- 玉米片(Corn Flakes)
凯洛格所用的**“谷物回火”**方法在**1894**年取得专利。(The **Kellogg** "grain-tempering" process was patented in 1894.)
－ 玉米和遗传学(Corn and Genetics)
在美洲殖民地无所不在的玉米，除了食用之外又发展出上千种用途，其中一个用途就是用玉米穗轴制成的烟斗。(The ubiquity of the corn plant in **Colonial America** had made it standard material for a thousand uses which had nothing to do with food. One devive was the corncob smoking pipe.)
- 玉米植株兼具雄性（穗）与雌性（须）两种性别，杂交玉米通过摘除自身的穗来完成，这样以来，玉米植株就不会自身授粉，而是必须接受来自其它植株的花粉。......通过受制遗传，培育出雄花不育的植株。(A corn plant is both male (its tassels) and female (its silks). Hybrid corn seed is to bear the grain, so that the plant cannot seed itself but will receive pollen from the other inbred parent chosen to be planted in the same field......by genetic manipulation, to produce no pollen.)
- 同一性是一个现代社会特有的诅咒，它伪装着自己，以多样化的形式装在超市的罐头里，盒子里，瓶子里和纸板箱中。每一件摆在架子上的东西里都含有玉米，因此我们依赖着玉米，玉米也依赖着我们。我们自己证明出来的无能为力，却让我们承担起越来越多不可逃避的责任。(Uniformity, disguise itself as it may behind the multiplicity of cans, boxes, bottles, and cartons in our supermarkets, is a peculiarly modern curse. Everything on the shelves contains corn. We therefore depend on corn. But corn depends increasingly, because of our wanton（荒唐的） wastefulness, on us. Our own demonstrations of our incapacity to manage have placed us more exclusively and inescapably in charge.)

### Salt

- 盐税，中国从公元前7世纪开始由政府垄断了盐。(China had a salt monopoly from the 7th century BC. Salt was also one of the first commodities to be taxed. "The art of taxation consists of plucking the goose so as to obtain the most feathers with the least hissing.)
- 1825年，经过了400年的怨恨与诅咒，英国废除了盐税，是第一个废除盐税的国家。(In 1825, after four hundred years of resentment, England abolished her salt tax. She was the first country to do so.)
- 为夺回印度的盐并在不加税的情况下进行买卖，印度人民的非暴力不合作运动开始了。(Non-violent activities undertook to get India's salt and sell it free of tax.) 
- 盐，明亮，干燥，愉快，强悍，在许多种语言中，都是聪明与睿智的同义词。(Salt, bright, dry, titillating, and dynamic, is synonymous in several languages with wit and wisdom.)

### Ice-cream
- 至少在1100BC，中国人就知道如何在地下建造冰库。

> <span style="color:blue">Hui: 有种说法是，唐朝的《酉阳杂俎（yǒu yáng zá zǔ）》[是笔记小说集]里头，已经提到过冰与奶制品混一的玩意，叫做“酪饮”。宋朝时，大家也习惯类似东西叫冰酪，可能那就是冰淇淋的雏形。但法国人相信，冰淇淋是美第奇嫁到法国之后，才真正进入文明世界的——那就天晓得了。[“美第奇家族”（Medici Family）是佛罗伦萨13世纪至17世纪时期在欧洲拥有强大势力的名门望族。Maria de' Medici于1600年嫁给亨利四世，成为其第二任妻子，法国王后，路易十三的母亲。她是意大利豪门美第奇家族的重要成员。]</span>

- 第一个影响深远并且享有声望(influential and lasting fame)的咖啡馆(Cafe)，是巴黎的Cafe Procope。Francesco Procopio dei Coltelli在1686年开办了这座咖啡馆，他是意大利人(Italian)，可能经由弗洛伦萨(Florence)从西西里岛(Sicily)而来。
- The first automatic cane-rolling machine（蛋筒制造机）was invented in 1909.
- 1932年，冰激凌工业进入岛一个全新的阶段(entirely new phase)，这是Clarence W. Vogt 发明了连续冰激凌冷冻制造机(continuous ice-cream freezer)。

### Sugar (from an article)

东汉明帝驾崩，马皇后成了马太后，大臣疑心她要专权，太后就说，咱以后，含饴弄孙——含着麦芽糖逗逗孙子，这就能过日子了。罗马帝国时期，甜品单里大多是新鲜或干透的水果，以此取甜。  

用蔗糖最早的，应该是印度人。公元前三世纪，亚历山大东征，在印度发现有人嚼甘蔗取甜味，觉得有趣，便想法子移种。蔗糖提取不易，所以人类历史上大多数时候，砂糖的供应不顺畅。甜味曾经是个政治问题。跟英国人有关的糖危机，发生过两次。一次是19世纪初，英国人跟拿破仑打仗，拿破仑打不过英吉利海峡，便搞经济封锁，英国人一生气，也不给欧洲大陆供蔗糖。拿破仑御下的大陆诸国要哭了：一口甜的都吃不上！德国人这时跳出来：咱有甜菜，可以榨糖，让蔗糖去死吧！结果德国经济靠此崛起，实在是意料之外。另一次是20世纪初，《泰晤士报》连篇累牍，说只有下等阶级的人才爱吃甜喝甜，嗜糖如命。上流社会都要修身养性，减少食物含糖量还来不及呢。结果英国人对茶里放糖，依然故我。到二战时，人民需要营养和热量，支持抗击纳粹事业，实行配给制，糖不够用，怎么办？答：往茶里加牛奶，“多加些牛奶，茶就甜了。”

葡萄酒发酵，酒精度和糖分此消彼长，所以爱喝偏甜葡萄酒的，就会被资深好酒者小看。南欧惯例，像葡萄牙、西班牙和南法酿葡萄酒，都喜欢加酒精强化，提前终止发酵，导致葡萄酒甜浓醉人。但这种喝法，法国北部的人就不大喜欢。德国人喝啤酒，嫌麦酒太甜，加了啤酒花，得了其中的清爽苦味才过瘾，反过来还要嘲笑：波兰这群胖子，就是爱喝甜烧酒，个个都是大冬天长个酒糟鼻子！

如此，口味甜不甜，在欧洲像个阶级问题。

福塞尔(Paul Fussell, American cultural and literary historian, author and university professor)《格调(Class)》里认为，现代社会，下等人才会迷恋甜味。上流社会也因此摇旗鼓吹，认为懂得品茶与咖啡的苦味，才能谏果回甘，体会到深层的味道云云……大概可以这么说：上等人觉得，甜味经常显得女性化、脆弱、下等、世俗、不够高雅，能尝得苦味才显得品味非凡、耐得住寂寞等等，但抛去一切形而上的想象，我们普通人类本性的DNA里，还就是喜欢甜的东西。

> <span style="color:blue">Hui: 《格调》是一本精确而刺痛人的社会等级指南。等级是什么？它不是你的职业，不是你居住的地方，不是你的餐桌举止，不是你有多少钱或者你能挣多少钱。**等级是一系列细微事物的组合**，你很难说清楚。正是这些细微的品质确立了你在这个世界上的位置。作者通过敏锐的观察、独特的视角、鞭辟入里的分析和机智幽默的文笔，把美国社会中的社会等级现象和三六九等人的品味做了细致入微的对比。 </span>


## The European Coffeehouse Culture [咖啡馆里的欧洲文化，克劳士.提勒多曼]

- 根据一个有趣而且听起来可信的说法，咖啡不是由人，而是由动物发现的。大概在500年前，衣索比亚的牧羊人注意到他们的山羊吃了灌木丛中一种红色的莓子之后，突然兴奋的跳起来；牧羊人也好奇地尝尝这种看起来像樱桃的果子，结果也感受到类似的兴奋感。于是咖啡在世界各地的流传便开始了。

### Venice [威尼斯]

- 弗洛里安咖啡馆：19世纪巴尔扎克用文字表达出他对弗洛里安咖啡馆的偏好

### Zurich [苏黎世]
欧笛翁咖啡馆

### Vienna [维也纳]
- 维也纳的咖啡馆是咖啡馆中**独一无二**的......其独特性就如同匈牙利骑兵有其无法模仿的特色一样。[奥地利作家Johann Braun Von Braunthal]
- 据说维也纳在**1684**年拥有第一家咖啡馆。
- 在维也纳最早的几家咖啡馆中，**塔罗纳咖啡馆(Cafe Tarone)** 最常出现在人们话题中，它由烈酒商Johann Jacob Tarone于**1784**年成立。
- 格林史戴德咖啡馆(Hugo von Hofmannsthal)

### Hungray [匈牙利]
- 布达佩斯的 Cafe Pilvax  
诗人Sandor Petofi，尝试衔接存在于高尚文学与普通百姓之间的鸿沟，他将许多民间传说及神话写成诗句，这些诗句一方面保持其艺术本质，另一方面也十分浅显易懂。
- Cafe New York  
1894, 坐落于Erzsebet Korut 街的新巴洛克式咖啡馆
- Roland Mischkl: "大部分的侍者都是有美丽外表的女性，她们穿着可爱的围裙，白色或蓝色，及踝的绑带高筒鞋，上了浆的衬衣及深色短裙。那种装扮引起的性感遐想，虽然没有科学解释，却人人都能感受得到。安详闲散的气氛似乎能让人的性感遐想完全释放出来。"

### Germany [德国]
- 狂想咖啡馆(Cafe Grosenwahn)：柏林艺术家聚会的主要地方，主人Rocco, 1914.7第一次世界大战
- 罗曼咖啡馆(Das Romanische Cafe): 主人Karl Fiering， 1916年创立
- 若要以最优雅的方式喝咖啡，在柏林就该造访温特丹林登大道上的Hotel Adlon，这家饭店是招待国宾及外交官员的所在，也是许多国际知名的经济，科学及文化界名人的住所。

### Czech Republic [捷克]
- 在布拉格，饮用咖啡从18世纪初起形成为一种时兴的习惯。1714，Johannes Diodato在哈尔广场(Haarmarkt)开了维也纳第一家咖啡馆，卡维纳咖啡馆(Kavarna)。咖啡馆成为具激发性的艺术家聚会所的全盛时期是20世纪初的事。即使时光流逝，其中有三家咖啡馆至今仍保持它的音乐盛名：

     1. 联合咖啡馆(Cafe Union)：捷克艺术家在此聚会，佩斯提那街(Na Perstyne)，Jaroslav Hasek《好兵帅克》的作者
     1. 雅可咖啡馆(Cafe Arco)
     1. 斯拉维亚咖啡馆(Cafe Slavia)

- “巴黎有它的丁香园，园亭咖啡馆(Cafe La Rotonde)；柏林有它的狂想咖啡馆，而布拉格则有它的联合咖啡馆”[Karel Capek]

### Rome [罗马]
- 希腊人咖啡馆(Antico Cafe Creco)
    - 门德尔松(Felix Mendelssolm)
    - 叔本华(Schopenhauer)
         - 《意志和表象的世界》：“这是一本完全崭新的哲学系统，拥有极高度的思想连结，而这种观点尚未在人类的头脑中出现过......这本书将会成为日后千百本书的资料来源，也将成为许多创作的动机。”
         - "所有东西都是不幸福的"
         - "即使有时候我们真正面临幸福，我们也不会觉察，而让这一切就这样轻易，温柔地与我们擦身而过；一直到幸福不再，空虚的感觉凸显消逝的幸福时，我们才会发现，我们把一切都搞砸了，最后只留下深深的追悔。"
         - "博学多闻的人是那些学了很多东西的人；而天才可以让人类学到他们到现在都还不知道的事。"
    - 卡尔.维特(Karl Witte)，哥廷根，停留罗马期间和叔本华一样是希腊人咖啡馆的常客。十岁时进入大学研读数学和法律，十六岁取得博士学位，当时政府批准乐一项奖学金给这位天赋异禀的年轻人。
    - 也有法国和英国的艺术家造访这家咖啡馆，英国的拜伦，雪莱，济慈(A thing of beauty is a joy forever)

### France [法国]

##  不顾诸神：现代印度的奇怪崛起                                                          
##  你如此需要安慰——关于爱的对话  [李银河]                                                   
##  The Chrysanthemum and the Sword  [Pauling Kent]                                       
##  FBI教你破解身体语言                                                                  
##  男人其实很忧郁                                                                        
##  揭秘美国医疗制度及其相关行业                                                          
##  中国人的精神 [辜鸿铭]                                                                    
##  文人谈饮食                                                                             
##  诸神的争吵:国际冲突中的宗教根源                                                        
##  书写的神话：西方文化中的文学                                                         
##  图解中国茶经                                                                        
##  知道点：世界文化 (World Culture)                                                     
##  图说天下·国家地理系列-全球最美的100个地方 (The top 100 beautiful places in the world ) 
##  酱缸——搅动看真相 [柏杨]                                                                 
##  性学十三讲                                                                             
##  美国政府概况(Introduction to American Government)                                   
##  话说中国大风一曲振河山                                                               
##  客厅文库休闲读物——礼品事典                                                         
##  实学简史（经典插图本）                                                                    
##  What Technology Wants [科技想要什么, Kevin Kelly]"                                      
##  Out of Control [失控, Kevin Kelly]"                                                      
##  Connected [大连接, Christakis, Nicholas A.,Fowler, James H ]                             
##  潜规则：中国历史中的真实游戏                                                         
##  隐蔽的秩序                                                                            
##  与机器赛跑                                                                          
##  The age of the unthinkable [不可思议的年代, Joshua Ramo ]"                                 
##  组织行为学 [边一民&徐力 etc ]                                                            
##  Uncertainty [不确定性, Mitchell Small ]"                                                   
##  文明是副产品 [郑也夫 ]

