# Novels and Plays 

> <span style="color:blue">Hui: Milan Kundera is my favorite novelist!</span>

## Immortality [不朽，Milan Kundera]

- 我们身上有一部分东西始终生活在时间之外；也许我们只有在某些特定时刻——大部分是没有年龄的时刻——才会意识到自己的年龄。

- 编制电子计算机的程序并不意味着未来的细节都得详细规划，也并不意味着一切都被写进“上天”这个程序里。譬如说，程序并未规定1815年要发生滑铁卢战役，也没有注定法国人要遭败绩，只是规定了人类的进攻本性。有人就有战争，技术进步将使战争日益残酷。从造物主的观点看，所有其他一切都是无足轻重的，只不过规定了可能性的范围。在这些范围内，它完全然偶然性来七作用。
> <span style="color:blue">Hui: Kundera would be a good statistician......</span>

- 这些谈话现在只记得一些零星的片段了，就像一些摔碎的盘子的碎片。在他成年以后，她想把这些碎片粘补起来。

- 她的裸露着的白色腿肚，就像一只农村里用的瓦罐，上面装饰着一些凸出的、淡紫色的、像纠缠在一起的小蛇。......这些人不想在人群中显得美丽也就罢了，他们甚至不像掩盖自己的丑态！她心里想：当她有一天丑得使人不能忍受时，她要到花店里去买一株勿忘我。只要一株，细细的茎上一朵小花。她要把这株草举在前面走到街上去，眼睛紧盯着它，除了这点美丽得蓝色以外什么也看不到。

- 仇恨得圈套，就在于它把我们和我们得敌手拴得太紧了，这就是战争得下流之处。...她突然想，我不能恨他们，因为没有任何东西把我和他们连在一起，我们毫无共同之处。

- 自有地生活，愿意怎样就怎样生活，愿意到哪儿去就到哪儿去。而他，他却从来也未曾有过这样得胆量，所以他把所有得资财都给了他的女儿，让她，让她敢于去做她想做得事情。

- 清静就是不被人注视得那种温馨感觉。

- 最近以来，她总是被一个念头纠缠着，她对保罗得爱情仅仅是建立在一种意愿之上，一种爱他的意愿之上，一种需要有一个幸福的家庭的意愿之上。如果这种意愿稍许有所松懈，她这种爱情就会像看到笼子打开了的小鸟一样飞走。

- 人们指望不朽，可是忽视了不朽只有与死亡在一起才有意义。

- 人在做了什么蠢事或者在失意的时候，风度会大受损害。

- 他在20岁时曾庄严地向他的姓名许诺要终生为善而奋斗；可是他很快便认识到要区别善恶是很困难的。

## Slowness [慢，Milan Kundera]

- The source of  fear is in the future, and a person freed of the future has nothing to fear.</li>
- A person with nothing to do is frustrated, bored, is constantly searching for the activity he lacks.
- In such a world, where everything gets told, the weapon that is both most readily available and most deadly is disclosure.
- Nothing in this novel stays a secret exclusive to two persons; everyone seems to live inside an enormous resonating seashell where every whispered word reverberates, swells, into multiple and unending echoes. When I was small, people would tell me that if I set a shell against my ear I would hear the immemorial murmur of the sea.
- Has mankind always lived inside such a resonating shell, without realizing it?
- As is often the case with glory, his was instigated by a defeat.
- And indeed, I wondered, what did become of the kiss that Sublime Planetary Historic News Event  had planted on his brow?
- This is where the courtiers of the News Event make their mistake. They don't know that the situations history stages are floodlit only for the first first few minutes. No event remains news over its whole duration, merely for a quite brief span of time, at the very beginning, The dying children of Somalia whom millions of spectators used to watch avidly, aren't they dying anymore? What has become of them? Does Somalia still exist? And in fact did it ever exist? Could it be only the name of a mirage?
- The way contemporary history is told is like a huge concert where they present all of Beethoven's one hundred thirty-eight opuses one after the other, but actually play just  the first note of each piece would be played, thus one hundred third-eight notes for the whole concert, presented as one continuous melody. And in twenty years, the whole of Beethoven's music would be summed up in a single very long buzzing tone, like the endless sound he heard the first of his deafness.

## Laughable loves [好笑的爱，Milan Kundera]

- She was lounging almost naked on my couch occupying herself with an examination of the ceiling.
- An ugly woman hopes to gain something from the luster of her pretty friend; a pretty woman for her part, hopes that she will stand out more lustrously against the background of the ugly woman. [丑女人往往希望借助她漂亮女友的光彩，而那个漂亮的朋友则希望在丑陋的对照下放射出更艳丽的光彩。]

  > <span style="color:blue">Hui:  想起《清醒思考的艺术》中说的对比效应，这样看来，丑女人的策略不对啊......和漂亮朋友在一起只会显得更丑不是么......</span>

- At birth every human being received one out of the millions of available bodies, as one would receive an allotted room out of the millions of rooms in an enormous hotel; that consequently, the body was fortuitous and impersonal, only a ready-made, borrowed thing. [任何一个人在生下来时，都在几百万可供使用的肉体中获得了一个肉体，就仿佛人们分配给了她一套住所，它就像一座巨大的大厦中其他几百万套住所一样；她对自己说，肉体是一种纯属偶然的非个体的东西；只不过是一件借用的和现成的物品。]
- Of course it was a quite naive desire, but there it was childish desires withstand all the snares of the adult mind and often survive into ripe old age. And this childish desire quickly took advantage of the opportunity to embody itself in the proffered role. [这无疑是一个相当幼稚的愿望，但这有什么办法：童稚的渴望摆脱了成人精神的一切樊笼，继续存在下去，有时候甚至在遥远的老年期依然还要冒出来。]
- The more the girl withdrew from him psychically, the more he longed for her physically; the alienation of her soul drew attention to her body. [她在道德上越是于他陌生，他就越是在肉体上渴望她；灵魂的陌生使她作为女人的肉体更为奇特。]

  > <span style="color:blue">Hui:如何概括这种心理？贱！</span>

- The alien life in which she had become involved was a life without shame, without biographical specifications, without past or future, without obligations; it was a life that was extraordinary free. The girl, as a hitchhiker, could do anything: everything was permitted to her; she could say, do, and feel whatever she liked. 
- It had always seemed to him that her inward nature was real only within the bounds of fidelity and purity, and that beyond these bounds it simply didn't exist.
- And it was futile to evoke good sense and warn her dazed soul that she must keep her  distance from the game and not take it seriously. Just because it was only a game her soul was not afraid, didn't oppose the game, and narcotically sank deeper into it.
- These two images showing through each other were telling him that everything was in the girl, that her soul was terrifyingly amorphous, that it held faithfulness and unfaithfulness, treachery and innocence, flirtatiousness and chastity. This disorderly jumble seemed disgusting to him, like the variety to be found in a  pile of garbage. 
- **Perhaps I want to resist necessity. To trip up causality. To throw off the predictability of the world's course through the whimsicality of caprice.**
- How can you be a conqueror in a domain where no one refused you, where everything is possible and everything is permitted?
- In them he saw the callousness of  aging men and women, the cruelty of their mature years, which rose before his youth like a hostile barrier.
- It was not a question of suicide but of a demonstration of suicide set up in such a way that a disaster would not occur.
- She saw herself without her own head. So to herself she was completely beautiful.
- He was seeking a comforting embrace, never-ending and vast, which would redeem him from the infernal relativity of the freshly discovered world.
- Only at the last moment, when they had almost passed each other, that smile rang a bell in his memory and snapped him out of his drowsy state.
- Women became for him the one legitimate criterion of life's density.
- He said to himself that there was a curious malice in the fact that he had met this woman, with whom he'd been head over heels in love and whom in those days he'd let escape, precisely when he found himself in this state of mind and at a time when it was no longer possible to rectify anything
- Havel, beneath the many glances, felt how once more he was regaining his lost visibility.
- The interlocking conjunction of all these forces eventually dumped him (as a crane drops a sack onto a truck) from secondary school into teacher's college...... He understood, however, that his occupation would be among the fortuitous aspects of his life.
- But this is the way life goes: a man imagines that he is playing his role in a particular play, and does not suspect that in the meantime they have changed the scenery without his noticing and he unknowingly finds himself in the middle of a rather different performance.
- Now, however, the unpremeditated snare of false news caused a split in the coherence of her being and it seemed to Edward that her convictions were in fact only something extraneous to her fate, in fact only something extraneous to her body; he saw her as an accidental conjunction of a body, thoughts, and a life's course, an inorganic conjunction, arbitrary and unstable. He visualized Alice and he saw her body separately from her thoughts; he liked this body but the thoughts struck him as ridiculous, and together they did not form a whole being; he saw her as an ink line spreading on blotting paper, without contours without shape.
- If you told him the whole truth and nothing but the truth, only what you really thought, you would enter into a serious conversation with a madman and you yourself would become mad. And it is the same way with the world that surrounds us. If I obstinately told the truth to its face, it would mean that I was taking it seriously. And to take seriously something so unserious means to lose all one's own seriousness.
- It occurred to him that these were signs devoid of meaning, currency without funds, weights made of paper.
- And that is why Edward longed for God, for God alone is relieved of the distracting obligation of (he himself, unique and nonexistent) the essential opposite of this unessential (but so much more existent) world.

## The Lover [情人, Marguerite Duras]

> <span style="color:blue">Hui: Finished this book in 2010.6. Marguerite Duras is a controversial writer:  cold, cranky and so egocentric. You may not like Marguerite Duras herself, but you can't reject her words: sharp and bold. She dares to say anything. You can let her die but can't make her shut up. She persist in writing all her life. If she wants to do something, she will do it and that's the woman. She said: "If I were not a writer, I would be a hooker." But I think if she hadn't been a writer, she would suicide.   
When reading her words, your heart may skip a beat from time to time. As I said before. "being happy" is like "playing piano", it's a skill rather than human nature. You need to learn and practice. However, she doesn't own the skill. She lost in her world and her desperation. She was brave and honest. She talked about naked sex, desperation, fornication without disguise. She is not my favorite. BTW, I am so sorry about her Chinese lover. And I have to state that not every Chinese is like him. </span>

- Dreamer

She is such a dreamer that there is noway to wake her up. See the beginning and ending of the novel:

> Beginning: One day, I was already old, in the entrance of a public place a man came up to me, He introduced himself and said, "I've known you for years. Everyone says you were beautiful when you were young, but I want to tell you I think you're more beautiful now than then. Rather than your face as a young woman, I prefer your face as it is now. Ravaged.

> Ending: And then he told her. Told her that it was as before, that he still loved her, he could never stop loving her, that he'd love her until death.

The paradox lies between her belief in love and her fear to break it. Duras was highly influenced by the difficult life that her family experienced during the period in Indochina. There was no love in the family and she said:

> It's a family of stone, petrified so deeply it's impenetrable. Every day we try to kill one another, to kill...... the face that all three of us are our mother's children of a candid creature murdered by society. We're on the side of the society which has reduced her to despair. Because of what's been done to our mother, so amiable, so trusting, we hate life, we hate ourselves.

That's why she was eager for love . She kept the love with her Chinese lover by ending it. So she could tell herself: "he loves me forever". It was over because she had to leave but not the problem of the love itself. However, if she hadn't left, their love might still be over one day but because he wouldn't love her anymore which was unacceptable. I think she knew it. That's a very good trick. She left when they still loved each other so their love was not destroyed and couldn't be.  Moreover, for her Chinese lover and his new wife, she assured:

> It must have been a long time before he was able to be with her, to give her the hair to their fortunes. The memory of the little white girl must have been there, lying there, the body, across the bed. For a long time she must have remained the queen of his desire, his personal link with emotion, with the immensity of tenderness, the dark and terrible depths of the flesh.

Such a dreamer! He might forget her not long after her leave and started a new life. Who knows? Similarly, she also considered that her little brother's death made him immortality.

- Distance

She kept a distance to world around. There were two things kept the distance not too big so that make her alive: writing and drinking. She said: "I drink because I know God does not exist".  I like her courage to face her life and say the truth in humanity out.

- More quotations

> Departures. They are always the same.

> The thing that's between us is fascination, and the fascination resides in our being alike. Whether you're a man or a woman, the fascination resides in finding out that we're alike.


## Plays of Marguerite Duras

> <span style="color:blue">Hui:Here are some quotations of her plays. I won't read anymore works of this writer. </span>

- It's agony. Being so near to you and yet so far.
- It's a gram-phone. I'm like that. I keep my word. I hope you'll get to know me.
- I mean nothing to you, less than nothing.
- Another time, I took Mr. Jo's presents, the blue dress, the compact, the nail polish, and threw them in the river. That meant there was nothing left to sell.
- Cleaving the sea with her body. Disappearing in an eddy. The water closed up over her. 
- Cries out that her skin is burning, scorching against his.
- A love...A love belonging to every moment without a past, without a future. Changeless. A crime.
- Because...I forgot what I'm weeping for.
- She belongs to whoever wants her. Gives her to whoever will have her.

## L'Assommoir [小酒店，Émile Zola]

- 她头越来越低，双手捂住了双眼，仿佛要让自己消失在遗忘的黑暗之中。
- 那些留下来的则伸长脖子，眼神中露出残忍的凶光。
- 酒足饭饱，张开双手拍着大腿，安详缓步地走进嘈杂拥挤的人流中去了。
- 热尔维斯渐渐感到累了，头伏在枕头上，微笑着发呆；她看得见，听得见，但却无力做动作或开口：她觉得似乎自己已经死去，十分适意的死去，看到别人活着，她感到欣慰。
- 当她梦想到她的店子时，常常面对时钟发呆，眼睛死盯着时针转动，恍若在等待着某一个特殊隆重的时刻来临，以便最后下决心。
- 她只好躲躲闪闪，仿佛一个大人做了孩子气的事而见不得人。
- 她流落到街头时的理想：工作，有面包吃，有一个自己的小窝，抚养孩子们，不挨男人打，能死在自己的床上。
- 她眼前始终浮现着那个四岁女孩的目光，那么庄重，那样勇敢，只有一个成年女人才会有的目光。
- 男人们很喜欢捏她，因为他们可以捏遍她的全身而不碰到骨头。
- 他们走了进去，要喝一杯李子酒，惟一目的是在一起饮酒，庆贺一下改邪归正的决心。
- 她的神情十分专注，那双邪气十足的孩子的大眼睛，因被淫荡的好奇心驱使而闪闪发光。
- 他们把她当作蜡烛，从两头点燃......他所受的教育像不爱干净的人们穿着一件下面带有污垢的白衬衫。
- 起初他们转来转去，找不到东西，犹如玩乐过度的第二天疲惫不堪。
- 当一个人不再哭泣时，悲伤即转化为厌烦。
- 库波躺下了，他说不是为了睡觉，而是为了思考。

> <span style="color:blue">Hui: 哈哈，这个经典！</span>

- 拉丽仅仅保持着沉默的目光，一双黑色顺从的大眼睛，让人感到眼底深处蕴含无穷无尽的悲哀和痛苦。她始终默默无语，只有一双黑色的大眼睛睁得很大。
- 习惯如同别的东西一样可以消磨正直感。
- 当他站在窗前时，人们可以透过他得身子骨见到阳光，他实在是太瘦了。
- 她的死正是因为她小小年纪便有了一个真正的母亲的理智，她的心胸还太嫩，太狭小，容不下这么宽厚的母爱。
- 当然，这是不干净的，但是这时干净与不干净在她的脑子里混淆了，人在饿得要死得时候不会谈这么多得哲理，只会吃能到手的面包。
- 她看着他，仿佛要寻找那条她抛弃过尊严的沟渠。
- 这是一场真正的风雪，在广阔无垠的天空中，细雪飞旋着，仿佛从天空的四个角同时吹来。
- 她停下来，踌躇不定，转回头，猜想着在这雪帘子后有开阔的大街，有一排排望不到头的煤气路灯。还有沉睡的巴黎无限的黑暗与荒凉。

## Arch of Triumph [凯旋门，Erich Maria Remarque]

- 他从口袋里掏出那张写着那个女人名字的纸，把它撕成碎片，扔掉了。忘记。这是一个什么样的字眼儿，他想。充满着恐惧、安慰和幽灵鬼怪！要是不能忘记，谁还生活得下去？然而，又有谁能够忘记得一干二净呢？记忆的灰烬，碾碎了一个人的心。人只有在再也没有什么可以留恋的时候，他才是自由的。

## The Little Prince
## White Death
## Mark Twain: Pudd' nhead Wilson 
## Selected Short Stories of O Henry
## NovCN: 动物凶猛
## NovCN: 水岸

## NovCN:女记

- 女人永远都无力抗拒任何呼唤着她受惊灵魂的声音，而男人则无力阻挡任何灵魂正在相应呼唤的女人。

> <span style="color:blue">Hui:上半句和下半句结合起来不就是在说：只要男人呼唤，女人一定回应，男人一定无法阻挡。换句话说，我们都是毫无自制力的动物......</span>

- 一个女人，而且是一个漂着的离婚女人，在这个陌生的城市里带着一个烧残的孩子，生存都是一个问题。

> <span style="color:blue">Hui: 这句话没有出彩的地方，摘抄下来只是因为它太没有艺术性，很多时候，生活让你感觉就是这样，现实的毫无艺术可言。</span>

- 千家万户新桃换旧符时，刘心香和胡闹闹就这样在病房中度过。
- 发生的事情就发生了，不要想着任何事情都会有补偿，没有，损失的永远就是损失，伤害的永远就是伤害，你不可能修复，你不可能回到从前。只能是徒劳地浪费时间和精力。
- 她知道一旦一个女人没有秘密的站在一个男人面前时，女人就没有味了。
- 刘心香就感到自己似乎真的是那罂粟花正在风中疯长，让陈丽害怕，让陈丽不得不拔掉迎风而长的花儿，否则安达就没有命了。
- 人说女人出水如芙蓉，水使女人水灵，水使女人美丽漂亮，女人离不开水就如鱼儿离不开水。在水里女人才有了生命，同样，在水里，女人的优点和缺点都无可隐藏，美的更美，丑的更丑。
- 刘心香看着自己后面孤零零的脚印一个一个深陷在雪地里，有泪水咸咸地流进嘴里，她搞到后腰隐隐的疼，想想今天是24日，唉，那个老朋友又要来了。抬头看着满天的雪花，刘心香狠狠地擦了擦脸上的泪水，骂道：妈的，怎么这么多的贱泪！

## Selected Short Stories of Washington Irving
## NovEU History:安格思首部曲:传奇初现

> <span style="color:blue">Hui: 不是太喜欢这本书，只记录了这两句。</span>

- 那是一种奇妙的祥和，就像在风中飞翔，在海面上走路，在云端驰骋，在面对威胁毫不犹豫。
- 在风云变色的战场里要精心算计根本是不可能的事。战场上真正的计算就是求生存。


## NovCN:小人得志

- 在官场上，你一旦得势，你的权势周围很快就会形成一个生态圈，衍生各类的物种。趋炎附势就像初生的婴儿走出母体时的第一声啼哭一样，在许多人而言时与生具来的。当你走了霉运，不再拥有了权势时，衍生在你周围的那许多物种也就很快地变种甚至绝迹了。官场的丑恶是多种多样的，而趋炎附势，人走茶凉只是其中的一种，自古皆然，生生不息。 

## Nov: 世事如烟
## Nov: 灵魂饭
## Nov: 琴声如诉
## Nov: 美国佬

