# History 
## 总统是靠不住的 [林达]

- P30 回顾殖民时期的北美历史，几乎是一部充满了各种理想实验又同时充满了妥协、退让、放弃和变通的历史。
- P33 **1912**年才算是真正统一了国旗；   
     **1931**年确定国歌
- P46 立法、行政、司法这三大权力的分割，对三大分支又一层层继续切割。联邦、州、市、县，直至鸡毛小镇都有自己一套完整的权力构架。它们之间没有条条结构的上下级关系，它们都是独立的，各自为政的，各由当地的选民直接选出的。例如在美国的司法系统中，联邦法院对地方法院并不存在领导关系，各个州有他们自己的州宪法，州一级最高法院大法官和联邦最高法院的大法官之间也没有什么关系。
- P50 在原定只讨论政府结构的宪法中，补充确定了人民自由权力的十条宪法修正案。这十条修正案从正面看是以法律的形式保障公民权力，而从另一个角度去看，它是在政府权力结构之外，在限制政府权力的同时，又以民间制约的方式再加了套监督机制。
- P50 宪法只是一个契约，美国宪法的前后两个部分的性质是不同的。前者虽然有对于权力的约束限定，但是，它的性质是美国人民向政府“授权”而作为“权利法案”的十条宪法修正案，它的性质完全是人民对美国政府“限权”。分权和制衡。 
- P51 **1789**: 宪法正式被宣布为美国的基本大法
- P54 **1951**: 宪法第22条修正案中，规定了一个人在总统的职位上只能任职两次。

## 一边走一边读 [林达]
## 历史深处的忧虑 [林达]                                      
## 我也有一个梦想 [林达]                                     
## 如彗星划过夜空 [林达]                                     
## 春秋大义 [熊毅]
## The Rational Optimist [理性乐观派]
## War Made New [战争改变历史]
## Egypt History: 木乃伊——法老时代的生与死
## The Rise and Fall of the Third Reich
## A Brief History of Religion [宗教简史]
## 大国崛起 [日本] 
## 大国崛起 [美国] 
## 大国崛起 [俄罗斯] 
## 大国崛起 [德国] 
## 百家讲坛 [说雍正]                                                     
## 历史的胭脂痕迹 [触摸历史上命运多舛的红颜背后]                         
## 武则天正传 [林语堂]                                                       
## 人类的故事 (the history of mankind) [Hendrik Willem Van Loon]            
## 何苦生在帝王家[大清公主命运实录]                                    
## 世界简史  [Brief History]"                                                              
## 上帝之鞭阿提拉 [挑战罗马帝国的匈人王]                               
## 美国无法忘却的罪恶 [美利坚风雨二百年]                                
## 探索古文明系列 —— 木乃伊 [  ]"                                               
##  传说时代 · 夏 · 商 · 西周                                            
##  美国人民 —— 创建一个国家和一种社会（上卷 1492-1877 年第六版）        
##  木乃伊：法老时代的生与死 [覃东]                                           
##  忽必烈大帝                                                           
##  邓小平时代 [傅高义]                                                       
##  论中国(On China) [基辛格]                        
## 人类简史——从动物到上帝 [尤瓦尔·赫拉利 ]


