# Proses, Essays and Poems

## The Thoughts of An Idle Fellow [Jerome K.Jerome]

- There are plenty of lazy people and plenty of slow-coaches, but a genuine idler is a rarity. He is not a man who slouches about with his hands in his pockets. On the contrary, his most startling characteristic is that he is always intensely busy......**Idleness, like kisses, to be sweet must be stolen.** [Haha : )]
- Love is like the measles; we all have to go through it.
- No, we never sicken with love twice. Cupid spends no second arrow on the same heart. 
- Love is too pure a light to burn long among noisome gases that we breathe, but before it is choked out we may use it as a torch to ignite the cozy fire of affection. [爱情之火太纯洁了，它无法在我们呼吸的污浊空气里长久燃烧。但在它熄灭之前，我们可以用它为火种点燃温暖的情爱之火。]

- That warming glow is more suited to our cold little back parlor of a world than is the burning spirit love. Love should be the vestal fire of some mighty temple—some vast dim fane whose organ music is the rolling of the spheres. [这样的温和之光比起热烈燃烧的爱情之火，也许更适合世俗间寒冷仄狭的小客厅，爱情是那些非同寻常的高庙大殿里的贞洁之火，宏大幽暗的穹顶上，回荡着管风琴的音乐声]

- We take all things in a minor key as we grow older. There are few majestic passages in the later acts of life’s opera. Ambition takes a less ambitious aim. Honer becomes more reasonable and conveniently adapts itself to circumstances. And love-love dies. [到了这个岁数，我们已经学会低姿态处事。在生活这场戏剧的后半场再难寻觅雄奇壮丽的篇章。追求远大目标的壮志雄心也日渐消沉。时过境迁，对待荣誉能以理性也能合乎环境生存了。至于爱情——爱情已经死去。]

- This blase old beau loves with an hysterical [hɪ'stɛrɪkl]  fervor that requires four adjective to every noun to properly describe. [那些耽于享乐的花花公子的爱情是如此狂热炽烈，需要在每个名词前加上四个形容词，才能恰如其分地加以描述。]

- Its affect  on you is somewhat similar to what would probably be produced by a combined attach of toothache, indigestion, and cold in the head. You become stupid, restless, and irritable; rude to strangers and dangerous toward your friends; dummy, maudlin [‘mɔdlɪn], and quarrelsome; a nuisance ['nusns]
  to yourself and everybody about you. [它对你的影响，有点像牙疼、消化不良以及头疼脑热之类对你突然进行的一次联合袭击，你变得愚蠢、烦躁、易怒、对陌生人粗鲁无礼，也让朋友感到不安。举止粗鲁、感情脆弱、寻衅滋事。变成了一个自己和周围人都不喜欢的家伙。]

- When a man or woman loves to brood over a sorrow and takes care to keep it green in their memory, you may be sure it is no longer a pain to them. However they may have suffered from it at first, the recollection has become by then a pleasure.[当一个男人或女人喜欢咀嚼悲伤，沉思默想，不时刷新自己的记忆，使往昔的悲伤在记忆里新鲜如初，你就可以肯定这一切对他已不再是一种伤痛。最初的悲恸已经渐渐消退，这个时候的回忆已经变成了一种虐恋式的愉悦。]

- Why assume that a doubled-up body, a contorted purple face, and a gaping mouth emitting a series of ear-splitting shrieks point to a state of more intelligent happiness than a pensive face reposing upon a little white hand, and a pain of gentle tear-dimmed eyes looking back through time’s dark avenue upon a fading past? [一双白嫩的小手托腮凝思，一双温情脉脉的泪眼穿越时间的黑暗隧道追忆着那过去的岁月，也算得是一种幸福吧。]

- 当我们回忆起曾经的伤痛带给我们的衰弱无助，而时间之手早已抚平我们滴血的伤口，抹去我们心头的酸楚和绝望；当我们从过去的烦恼中品尝出悲喜参半的甜蜜感受时，我们心头负担已不再沉重；当骑士襟怀的纽康姆上校面对死神的点名，大声回答“到”的时候，当汤姆和塔莉维尔冲开分隔他们的浓重迷雾紧紧地握着手，拥着对方走向汹涌的弗洛斯河的时候，内心也必定是同样的感受。[Time has laid his healing hand upon the wound when we can look back upon the pain we once fainted under and no bitterness or despair rises in our hearts.]

- 忧郁女神是一位沉思的，眼睛深陷的少女，直到“夜色渐浓，乌鸦的翅膀掠过摇曳的树梢”，她才偷偷地走出自己的小树林。她不喜欢白天耀眼的阳光。她的宫殿坐落于朦胧的国度，她就是在那里跟我相会的。[The wound belongs to Melancholy [['mɛlənkɑli],忧郁的，忧郁] then, a thoughtful deep-eyed maiden who loves not the glare day. It is not fill “light thickens and the crow wings to the rocky wood” that she steals forth from her groves [[grəuvz]小树林]. Her palace is in twilight land. It is there she meets us.]

## Essay 送你一颗子弹（刘瑜）
- 检验友谊的唯一标准就是两个人能否凑在一起说别人坏话
- 被梦想俘虏的人就是在追逐他的厄运。
- 人的每一种身份都是一种自我绑架，唯有失去是通向自由之路。
- 梦想多么妖治，多么锋利，人们在惊慌中四处逃窜，逃向功名或者利禄，或追求功名利禄而不得的怨恨。
- 好吧，疯子并不是一个政治正确的词汇，政治正确的说法应该是：那些在另一个层次实现均衡的人。均衡，我喜欢这个词，它表明一切上升或者坠落或者旋转或者破碎都有一个优雅的优点。
- 这个定居几乎是像高速列车一样向他驶过来，要把他铲进历史的垃圾堆了。事实上他已经死了，已经在腐烂了，只是生活在以倒叙的方式回放而已。
- 孤独，微渺，疯狂，无所事事，不被需要。青春的浓雾散尽以后裸露出时间的荒原。人一辈子的奋斗，不就是为了挣脱这丧心病狂的自然？

## Essay 谢谢收看（刘瑜）

- 当然有时候我也看看新闻联播，我主要是想研究我国的“领导排坐学”，“领导表情学”，“领导视察学”等领域近年有没有实现理论上的重大突破。
- 在他们怀疑人生的时候通过什么方式来找到更倒霉的人重新树立生活信心呢

## Essay 老张，亦文和蚊来（刘瑜）

- 总而言之，老张对“老张”这个词去其糟粕，取其精华地进行了发挥，使老张这个词中的社会责任感得到了充分的演绎。“亦文”最好还是滚回琼瑶阿姨的小说里去。
- 焦虑地在“喂”，“哎”，“嗨”之间颠沛流离。
- 既可去中国城扛东西，又可在地平线上诗情画意地升起。

## Essay 我爱“饭扫光”（刘瑜）

- 每到吃饭的时间，就端着空空的饭碗，遥望祖国的方向，脑子里翻滚着水煮鱼，麻辣烫，香辣蟹，等等美丽的名词，喉咙里却不断地咽着痛苦的口水，完全可以说是饮食界的文天祥。如果说阿香婆的辣是一个大老粗站在一栋居民楼下大喊；饭扫光的辣，则是张靓颖小姐的海豚音，在往上提升的过程中还有那么一点摄人心魂的震颤。

## Essay 我爱崔健（刘瑜）
- 像我这样从小到大被迫害成三好学生的人，体内得积压多少无家可归的荷尔蒙啊。
- 某个片刻一个人被表达欲击中，那个表达欲新鲜，强烈，浓郁，像一只红光满面的苹果，非常挑逗地坐在那里，让人忍不住伸出手去。
- 每个人都变成了一个纸团，被拾起来，被展开，文字凸显出来，被一个低音给念出来。贱贱地，那些高的，矮的，胖的，瘦的，老的，少的陌生人都变的有声有色，明明什么都不是，却显得像那么回事。
- 你知道吗，美好的秘诀就是速朽。

## Essay 电器（刘瑜）
- 它知道我需要它，不能把它怎么样，所以就像个妓院偷拍似的越发摆谱。
- 我的愤慨终于上升到了一种存在主义的厌世感。
- 生活就是一个手段不断淹没目的的过程，比如说吃饭问题不断淹没精神问题。
- 男人长相的几个档次：丧权辱国，闭关自守，韬光养晦，为国争光，精忠报国。
- 他就随便那么一帅，我就随便那么一赖，然后岁月流逝，我们磨磨蹭蹭的变老。
- 如果这些女孩把她们得不到的痛苦，失去的痛苦，不得其所的痛苦，统统转化成为创造性活动中的生产力，这该是生产力多么大的解放啊。
- 如果没有感情的风云变幻，我这艘快艇得在知识的海洋里飕飕地跑地多快啊！想不牛都难。
- 有时候我真的搞不清女人是真的被上帝陷害成这样，还是在用爱情来逃避更大的责任和自由。
- 如果我们不用斤来衡量芭蕾舞，用米来描述莫扎特，又怎能用一生半生，九又三分之一生来衡量爱的质地？
- 不值得书写的人生值得度过么？
- “反熵”是热力学中的一个术语，王小波同志不止一次的提起这个词，这个词的意思简而言之就是说投入的多单是释放出来的能量少，也就是“费力不讨好”的现象在物理学中表现的一种形式。
- 亚里士多德说：“人是天生的政治动物。”
- 享乐主义得以存在是又一系列公共制度的前提的，而这些前提是政治斗争的结果。以为私人生活与政治没有关系的人忘记了私人领域从边界的界定到秩序的维护都是政治问题。
- 好像唇红齿白的笑容间一颗虫牙突兀在那里。
- 人们摒弃了门外的灿烂阳光和星巴克里的资产阶级光明，趴在匈牙利咖啡馆昏暗的灯光下如同捉虱子一样费力地辨认自己书上的文字。
- 越大的自由意味着越大的责任，因为一个自由的人注定是一个精神上的孤儿，他无依无靠，除了自己的头脑和心灵。
- 空洞洞的友谊，在里面喊一声都有回音。
- 她很健忘，尤其是对自己曾经刻骨铭心的东西——好像一个小孩吃什么东西“吃伤了”。
- Tiramisu= Pick Me Up
- 一平脸上的微笑像用杆秤称过一样得体，而如意挥手的幅度也像用尺子量过一样又分寸。就是月亮也亮得很严肃，一点柔情蜜意都没有，冷冰冰，像一枚图钉。
- 任何一种关系，就像孤独，都可以上瘾。上瘾了要戒掉就很困难，但这与你爱不爱一个人没有关系。
- 好像一个日子是另一个日子在镜子里得投影。无限的镜子，无限得投影。
- 生活的属性和死亡一样，就是寂静。
- 他的脚下是纽约，一个繁华的岛屿。这个岛屿下面是地球，一颗孤独的星球。
- 这点温情，对于相爱太少，对于分手太多。她觉得自己这些年来就卡在柔软的温情和坚硬的梦想之间，飞不起来，也掉不下去。
- 没有恐惧的爱情，就像没有牙齿的鲨鱼一样，什么都不是。
- 我，这个历史的小数点后面遥不可及一个数而已。
- 优雅，骄傲，娇憨，贤惠，活泼......各种凶器，信手拈来，无所不用其极，但是她们找不到爱情。青春的汽笛已经拉响，手上的另一张车票还是无人认领。
- 你们在一起，像头驴子，转啊转，把时间磨成粉末，然后用粉末揉面，做包子，饺子，面条，吃下去，饱了，心满意足。
- 这历史的死胡同，一路都是被揪掉的头发，踩落的球鞋，和打掉的牙齿。
- 她的想象力很发达，很像是高速公路，密密麻麻，四通八达。
- 这场辩论已经变得机械，双方所有的论点都早已深情并茂地列举完毕，现在比的就是重复的此书和音量而已。
- 又一根火柴灭了，一根一根的火柴都灭了，她在这边努力地划着火柴，他那边根本没有一根蜡烛来接应。
- 她不需要安慰，安慰太重了，她现在需要一些更轻的东西。轻的像一个摇篮曲，这样她就可以静静地睡去。
- 时间走着走着就会迷路，卡在一扇旋转门里，转来转去还在原地。
- 我对你的爱情，超出了结构功能主义的解释，存在主义的解释，阶级分析的解释，唯美主义的解释。

## Essay 其它（刘瑜）
- 仿佛一个12岁的小姑娘，偷出了妈妈的化妆品，把脸蛋涂抹的惊心动魄，对着镜子里陌生的自己，却觉得异样的熟悉。
- 它更像是一个邀请你加入舞池跳舞的女郎，要体会她的激情，你必须学会跳舞。
- 也许虚无主义只是笨蛋故作聪明的姿态。
- 我很想把这些事与人分享，但我的老公，儿子及狗都还在火星赶往地球的路上。
- 过去隆重？我还觉得这个充满规则和潜规则的世界过于啰嗦了呢。
- 总觉得那些“试验性”小说写作里，作者的自我意识太强烈了，总是要丛文字里伸出一只手来，使劲摇晃着一面旗帜，上面飘扬着两个大字——“个性”，与其说我们在读一个故事，不如说在欣赏一场行为艺术。
- 他写一个人在异域文化中的脆弱感，及从异域返回本土时同样强烈的隔阂感。
- 他紧张地盯着她的脸，看它从暮色中一点一点浮现出来，仿佛在赌场里看着抛到空中的骰子一点一点落下来。
- 她要一个现成的男人，事业是现成的，心态是现成的，可以拿着行李登上甲板就起航的轮船。

##  Essay 在平淡和奢华之间摇摆（南妮）
- 我们既希望自己享乐，又希望自己深刻。
- 在这个纷扰的时代，爱像恐龙一样难以寻觅，所以有那么多人做了工作狂
- 疲劳，产生于对需要做出反应的事物做出反应，对不想做出反应的必须反应。
- 离婚成了平庸生活的润滑剂。成了麻僵婚姻的强心针。在幻想的拒绝与悲壮里，想来一点电影女主角般的皇后况味，再来一点爱情回光返照的挣扎。
- 对于女人来说，爱情的唯美性应该是内涵与形式的高度统一。
- 上海，1000多万常住人口，几百万流动人口的远东不夜城，突然在它著名的拥挤与喧嚣中出现一个休止节拍。
- 是的是的，生前再辉煌再有名再成功再多金，死了也终于不如你乐——你至少活着，吃得动甜甜咸咸，将八卦小报看得津津有味，即使牢骚满腹，也是瓜拉松脆。因为日常生活的平静寡淡，疾病与死亡成为异常而令人注目的话题。一个人得了恶疾，在他亲戚朋友熟人同事间传播的速度之快会超出你的想象。在已经被显示出异常的人面前，自己的正常便变得格外宝贵。咀嚼这种正常带来的幸福，又更加恐惧对于不正常的恐惧。我们在面对别人的不幸时多少感到乐自己的庆幸。庆幸终究是狭隘自私浅俗市井。他们淡定空漠沉稳内倾，沉默而坚实地从事自己的工作，关注这个世界却并不轻易发表言论。**因为得懂所以慈悲。**
- 你真弄不懂骄傲与自卑是如何地铸造出了一个人的磊落风格。
- 一切先锋的实验与探讨都终有滞涩与停止吧。这是人类的可悲。令人眼花缭乱的生活观念归结起来也不过就是：结婚或者不结，生子或者不生，同居或者不同，跟旧情人恢复关系或者不恢复，玩性爱游戏或者不玩，谈爱或不谈，等等。
- 我喜欢岛。岛，三面或四面是海，明媚，清新，飘逸，空洞......对外似连非连，张力奇大；内部，却是安稳的，静谧的，悠闲的，自由规律的。
- 这个时代人们的焦灼多半是因为攀比。
- 就像有些人结婚的对象并不是他最中意的那个人，和他结婚的那个人也许是他情侣中最差劲的，他和她结婚，只是因为眼下他想结婚。他乏了，累了，玩不动了。
            

