# Self-development 

## Make friend with time [把时间当作朋友，李笑来]

- 人们总说他们真正感兴趣的是别的事情。可事实上，那应该仅仅是因为他们还没开始做那件事情，所以还没有在那件事情上遭遇挫折而已。
- **不是有兴趣才能做好，而是做好了才有兴趣。**大多数事情需要熟能生巧。做的多了，自然擅长；擅长了，自然做得比人好；做得比人好，兴趣就大起来了，而后就更喜欢做，更擅长。
- 所有学习上的成功都只靠两件事：策略和坚持，而坚持本身就应该是最重要的策略。
- 没有什么比发现、培养、呵护、调整自己的心智力量更重要的事情了。
- 著名心理学家维克托.弗兰克：“即使在极端恶劣的环境里，人们也会拥有一种最后的自由，那就是选择自己态度的自由。”
- 我们自己的痛苦我们感同身受，而别人的痛苦我们很难做到感同身受。

 > <span style="color:blue">Hui: 朴素的真理，但我们还是时不时觉得自己家的经特别难念......人类真是愚昧，健忘，又短视。</span>
 
- Dan Goleman提出“Emotional Intelligence”， 他曾做过著名的"Delaying gratification" 实验
     - 希望自己的欲望马上获得满足是大多数人的天性
     - 野心永远是少数人的天性
- “推迟满足”是心智成熟的人必备的能力，也是需要挣扎和锻炼才可以习得的能力 。
- 把每天的时间开销记录下来，一方面可以培养自己的成就感，另一方面可以避免轻易地原谅自己。
- 不要害怕修改，完成任何一个任务的过程中，修改都是不可或缺的。你在修改说明你在进步。很多人一生最终一事无成的原因，就是因为他们是**脆弱的完美主义者**，天真地希望自己可以在这个不完美的世界里完美地生存——所以注定以失败告终。
- 养成任何一个哪怕是很小的习惯，都需要挣扎。然而，貌似痛苦的挣扎过程，在将来的某个时刻终归会变得其乐无穷。
- “浪费时间”这个说法是基于过程的，“成功失败”这个说法是基于结果的。对一个血肉之躯来说，最终的结果其实只有一个，就是死亡。失败从来都不是结果，因为绝大多数情况下，对大多数人来说，失败并不意味着死亡。人做事的时候，成也好、败也罢，通常还是要继续活下去。活下去，就意味着说还要不停地做很多事。
-  获得知识得途径：
    - 体验
    - 试错（Trial and error）
    - 观察
    - 阅读
- 面对无法亲身体验得知识，人们往往会心存恐惧，因为人们害怕未知。而群体面临无法体验得知识，往往会表现为疯狂。“很多时候人们的善良出自于软弱，而残暴不过来自于恐惧。”
- 日常生活中几乎所有主要的“沟通障碍”本质上都是因为沟通双方无法让对方理解与他们的经验相悖的知识或者信息造成的。
- 大脑中储存的信息要多到一定程度才有能力“融会贯通”。
- 自学能力：阅读，写作，检索。
- 很少有人仅凭天生的能力就可以拥有“神奇”的记忆力。“遗忘”是我们的自我保护功能。
- 嫉妒的产生源自于对自己与他人之间差异的扭曲理解。大多数人一生无法摆脱由比较而产生的情绪，不管是正面的，还是负面的。... 标记出并优先实施那些无需比较就可以获得欢乐和幸福的行动方案。时间会一如既往地分分钟钟、岁岁年年地流逝，但你会惊讶于你生活的变化。每一分钟，每一秒，每一天，每一年，时间的质量竟然会如此不同。
- 最为常见的逻辑错误是“以偏概全”。某个经验在某个人身上灵验了，并不意味着说这个经验在所有的人身上都会起作用。...“努力行动”并不是唯一导致成功的原因。...另外一个更加隐蔽的逻辑错误是“单向成立”。很多论断只不过是“单向成立”的。
- 接受自己和别人没有什么不同，至少没什么本质上的不同，是心智正常成长的重要前提之一。
- 电影精彩的原因：1）艺术加工；2）时间压缩。
- **浪费时间虚度年华的人有个共同特征——他们拼命想控制自己完全不能控制的，却在自己真正能掌控的地方彻底失败。**
- 往往只有优秀的人才拥有有效的人脉。...注重自身的质量，知道不给他人制造麻烦，独善其身是美的。常言道：“事多故人离”。
- 证明自己给别人看恰恰是最浪费生命的一种行为。...**所有傻逼都是自证的**。
- 你比比人强一点根本没用，真正有用的是你不仅比别人强，还要强出很多才行。...可是你知道如果你最终竟然在某一方面比别人强出许多的时候，你会面临什么境遇么？你身边的人不再在这方面跟你比较了，他们会自动放弃，然后跟你比你不如他们的地方！...**无论你怎么做，你还是很难获得对方承认的，因为你的想法和做法并不能影响他们的判断。所以，想办法“获取证明”实在是没有意义的事情。... 长久的观察和思考，有益于锻炼自己心平气和的能力。... 被别人左右，是一个人最可悲的状态之一**。
- 忘记自己的优点，成熟的人总是知道如何让别人舒服。
- 1) 人们普遍相信明天会拥有比今天更多的金钱；2) 人们普遍相信明天会有更多的时间。3) 人们对时间的曲解程度远远高于对金钱的曲解程度。
- 之所以可以“显得”游刃有余，是因为之前做过太多的准备。... 大多数的事情都需要提前准备，也都可以提前准备。
- **我们大脑中的灰质(gray matter)储存的各种信息只有很少一部分是有序储存的。... 随着信息输入越来越多，大脑就需要越来越多的灰质细胞(gray cells)。科学家们已经发现使用两种或者两种以上语言的人，有更多的灰质细胞(gray cells)。而颅腔的大小是有限的，于是gray cell的增加，最终会导致gray matter密度越来越高，于是gray cell之间就越有可能由神经元连接起来。于是就有可能产生我们所说的“融会贯通”的现象——那些原本可能貌似毫不相干的信息现在有机会被联系在一起了。** (Hui:这个科学上准确么？)
- 我们“对特定信息的注意力”会使得我们“神奇地”捕捉到那些于“我们所关注的信息”相关的某些信息。
- 反思能力，几乎是人类特有的。因为有这种能力才慢慢拥有了类比能力。而类比能力是一个人所拥有的理解能力高低之关键。...需要太长时间才可以获得的经验很难传递，就是因为缺乏现有的经验作为支撑。而想让一个孩子去真正理解“时间终究会越来越快”这样一个道理无比困难，就是因为他们不仅没有“类似的现有经验”，还恰好有相反的“现存经验”。几乎所有失败的青少年教育，都是因为粗暴简单而有愚昧地无视孩子们所拥有的“现存经验”和“现存经验的作用”而造成的。

> Henri Poincare: 混沌理论告诉我们，初始条件的一个极小的差异将会导致最终结果的一个极大差异。

- 生活就是选择，而所谓的选择只不过是一个人所拥有的观念对之衡量后的结果。一个人所拥有的观念，说穿了，就是心智力的最终体现。

> 苏东坡《留侯论》：古之所谓豪杰之士，必有过人之节，人情有所不能忍者。匹夫见辱，拔剑而起，挺身而斗，此不足为勇也；天下有大志者，卒然临之而不惊，无故加之而不怒，此其所挟持者大，而其志者远也。

## Red Wine
 
See the notes on [Red Wine](http://linhui.org/RedWine) page.

## Getting More [谈判，Stuart Diamond]
### Preface
1. 本书独特之处
      - 目标至上
      - 情感投资
      - 谈判形势判断
      - 循序渐进
      - 交换评价不同的东西：对方在意什么？
      - 对方谈判准则
      - 积极，诚心，避免操纵谈判
      - 找出问题的结症并将其转化成机会
      - 接受双方差异
      - 准备清单
1. 无形的谈判技巧
     - 同仇敌忾可以顺利建立人际关系（找到共同点：都喜欢夏天，喜欢看书等等）
     - 关注他人的想法，需求
1. 本书反对使用的技巧：赤裸裸应用权力
1. 谈判新定义
     - 迫使对方按照你的意愿行事
     - 让对方按照你的思路思考
     - 让对方理解你想让他们理解的挂念
     - 让对方感受到你想让他们感受的：出现压力风险时，人容易感情用事。当对方意识到你在意他们感受时，他们会更愿意倾听，更容易被说服。
1. 谈判目标：确定自己的谈判目标时什么，在谈判一开始就要对此做到心中有数，而且还要在谈判过程中不断提醒自己：“什么是我想在这次会议结束时想要得到而现在尚未得到的东西？”
      - 谈判目标越具体越好
      - 帮助所有相关的人实现他们的目标
      - 目标写下来随时查看
1. 步子迈小些：贪婪会让对方厌恶你，不信任你，从而使你得到的更少。本书的主题是强调“争取更多”不是“获得一切”。
1. 一切谈判与情境密切相关
      - 我的谈判目标是什么？
      - 他们是谁？
      - 要想说服他们，需要采用哪些策略和技巧？
1. 你的态度，可信度和透明度
      - 做真实的自己
## Professionalism [专业主义]
### What is professionalism? 什么是专业主义
- The Oath of Hippocrates
1. 允许我行医,我要终生奉行人道主义。 
1. 向恩师表达尊敬与感谢之意。 
1. 在行医过程中严守良心与尊严。 
1. 以患者的健康与生命为第一位。  
1. 严格为患者保守秘密。
1. 保持医学界的名誉与宝贵的传统。
1. 把同事视为兄弟;不因患者的人种、宗教、国籍和社会地位的不同而区别对待。
1. 从受孕之始,即把人的生命作为至高无上之物来尊重。
1. 无论承受怎样的压力,在运用自己的知识时也不会违背人道主义。   
专家的词源本是“profess”,意思是“向上帝发誓,以此为职业”。

- 作者列举了诸如律师、医生、教授和会计这些普遍被认为是专家的职业。对于法律这门职业作者提到：“从某种意义而言,法律是一个非常可怕的领域,它有可能仅仅依靠不同的解释而改变我们的人生。”对于会计（安然事件），医生（等候三个小时,看三分钟病），作者最后指出，单是国家认定的一张资格证并不能定义专家，“资格只不过是一张纸片而已,如果不成为 真正的专家,便如“脚底的米粒”,捡起来也不能吃。”。那么什么是专家呢？

## About Love [素黑]

- 先懂得为自己寻找一条路，安放好自己，追求在恋爱以外其它有意义的事情，你的心才能强壮起来，才能处理万变，才有条件和本钱去恋爱。分散恋爱的精力，才能看穿自己和爱人之间的问题。
- 谨记别强求，两个人的离合有太多无法解释或被清楚理解的原因，有种智慧需要学习，就是随缘也是爱的方式。爱必须心安理得，顾己及人。最大的幸福是活得自在、自由和喜乐，心安理得，不否定关系，也不泥守关系。当你能无须害怕或隐瞒什么，保持清醒和觉知，接受命运发生在你身上的一切，你便自由了。人要面对爱，得先接受无常和变幻，知道养活爱得靠自我提升和进步。
- 自爱应该是无条件的，正如父母应该无条件的爱孩子一样，这是天职。爱自己的人面上散发的光芒是骗不了别人的，你会活在平静，淡定，喜悦种，绝少埋怨，鲜有不满，没有太多话需要澄清，内心是一片宁静而有力量的海。
- 自爱的人不乞求被爱，反而会乐于把自己丰富的爱向别人分享，因此，自爱的人会平易近人，让人喜欢亲近，因为你的爱带着很强的感染力，等待被爱的人是焦虑的，自爱爱人的人是平和的。能爱便能被爱。  
爱是自然的发生，强求不来。
- 想获得爱情，感受活在安全感里，必须先热爱生命，这是每一个人一生必须学习和经历的成长过程。学习承受得失成败，才能变得成熟，懂得自处，然后懂得和别人相处，孕育爱。  
最好的伴侣不是别人，而是自己的内心。不能享受孤独便不能接受生命，无法好好爱自己。  
别人不好过绝对不会让你更好过。成熟的爱是在稳定的情绪，良好的身体和理性的状况下，先了解怎样爱自己，才能从容地相处，知道要和什么样的人在一起。人，从来都是孤独面对自己。未曾孤独过，捱不过孤独的人，永远不知爱的滋味，有的只是依赖的味道，跟香水差不多。涂上去的东西，都不能长久。
- 感到优越是可耻的，在这个疯狂到不可理喻的世界，麻木到只剩下互相消费的贪欲爱恨，我只感到比海更深的无助。
- 爱是一生修行的路，相爱时享受，相处时互相尊重，即使没有缘分走在一起，这份爱已一生一世。
- 恋爱让我们看透自己的盲目和软弱，是脱胎换骨的起点。
- 对方只是反映你的内在问题，对方的问题可以影响你，但关键是你为何被影响？你缺失了什么而心乱，能量被干扰？先处理你自己的问题。
- 学习适应跟最爱的人生离死别，正是修养自己，提升生命的机缘。爱，就是这个意思。
- 人在干涸的感情世界里容易堕入一厢情愿的幻想中。
- 人与人之间的聚散有时却无期。
- 经历就是爱的厚度和层次，无须任何意义。爱不靠认知，需要经历和修养。
- 爱永远是大方的呈现和分享。
- 人缘上太多无法解释的矛盾，每个人最终只能诚实面对自己的生命，体谅一切不如意的发生。
- 如果对方需要找个弱者平衡自己的话，那是他的选择。
- 希望和很多女人只有性关系的欲望和生理本能，是男人最大也最无助的秘密欲望，只能转化为权力和名利的追求。于是，男人永远具有侵略性，永远是伤害者。
- 男人的沟通基础是当下的意愿，尽快解决问题离开对话和关系。女人的沟通基础是制造永恒感觉、意义和记忆，尽量延长对话关系。
- 对话是假的，只是独白的变相。
- 每句话都有期限，不在时间，在感情的极限。
- 学习成熟处理感情问题，尊重他人，照顾别人的感受。
- 口不对心，心不对脑，是很多女人感情问题的真相。
- 女人需要的是有能力爱女人的男人，而不是借女人安慰自己的男人。
 
> <span style="color:blue">Hui: 什么样的男人是有能力爱女人的？怎么识别这样的男人？</span>

- 调情这种游戏的背后并不纯粹，它附带了性挑逗、性幻想、性贪婪、性打猎和性虚荣的隐藏意识，超越了一般交际的言行。

- 性能量很重要，其重点不是做爱，而是创造性。身体蕴藏无穷的创造力，而性爱是最容易震撼体验的身体状态之一。身体是我们最大的筹码，让我们享受生命，享受性和爱。爱惜身体，尊重身体，才有资格要求做爱。


## Others

- 最好学会的东西：
      1. 善待批评
      1. 基本汽车保养：引擎盖下有什么？如何换轮胎和助推启动汽车？有备用轮胎，不要让汽油少于1/4
      1. 善于回应恭维
      1. 紧跟时事
      1. 杜绝闲话
      1. 丰富阅历
      1. 习惯模棱两可
      1. 躬自厚而薄责于人
      1. 灵活应变
      1. 创造被动收入：版税，租金，专利等
      1. 有爱的能力：照顾自己照顾别人
      1. 定义好事物的界限
      1. 学习网络
      1. 确立自己的日程而不是被推到别人的日程里
      1. 创造性思考，打破常规
      1. 诚实可信
- 知识是可以背诵的。只有把基本的分析技巧内化为自己的思维本能，才能鉴别和取舍，用理性构建自己的认识，而不被情绪和冲动所裹挟，也不被煽动和诱惑而操纵。不要犹豫，尽早认准大方向，消灭选择，义无反顾，想方设法找到你要奋斗的那个圈子，你会跟着这个圈子不断地往上走。
- 强大意味着你在一个团队里有优先选择权。
- 脑力
     - 可以通过锻炼提升
     - 越强的人恢复能力越强，处理同样的任务时越轻松
     - 顶不住了常常只是错觉，离真的顶不住还有很长一段距离
- 生活是一连串的选择。你相信自己会进步成长，还是相信自己不会有什么变化了？这是一个特别“底层”的选择，这个选择随之影响无数的选择：
     - 你会不会主动选择？
     - 你会不会过分在意别人的看法？
     - 你会不会认真思考“什么最重要”？
     - 你敢不敢把已经赚到的钱全部花出去？
     - 你有没有自信凭一己之力让你的家人过上有保障、尊严的生活？
  人过了40，生活中的方方面面，好和坏，其实都是当初的选择，真的没有什么可以抱怨的。
  
