# Data Science

## Data Quality

- Kaushak, Data Quality Sucks, Let’s Just Get Over It, (2006)  

  > 1. Assume those managing the data have a level of comfort with the data; 
1. Start making decisions that you are comfortable with; 
1. over time drill deeper in micro specific areas and learn more; 
1. Get more comfortable with data and its limitations over time; 
1. Consistency in calculations=Good.

## Data Visualization

Three rules to visualize insights with impact: 

1. Highlight your message and eliminate distractions;
1. Use visual cues to help lead your audience through your insight; 
1. Use contrast (size, color) to capture the reader’s attention.
 
##Big Data (大数据的冲击)

### What is big data

- Trend: Analyzing non-structured data

- Genernalized definition: 
    1. structured data
    2. non-structured data(text,voice,vedio,GPS,sensor)
    3. Data storage/processing/analyzing techniques: Hadoop, NoSQL, machine learning/satatistics
    4. Data Scientist/Data oriented organization

- Decide.com/FlightCaster

- Bottle neck of machine learning: store and process big data (doubt it)

* From point information to thread information 
     + Point information: purchase a product, received a service......
     + We need thread information to answer WHY!
     + Thread information: customer interaction data (non-structured or historical behavior)

     
### Walk Between Privacy and Innovation

- Collaborative Filtering (Amazon): method of making automative predictions about the interests of a user by collecting preferences or taste information from many users (collaborating). The **underline assumption** of the collaborative filtering approach is that if a person **A** has the same opinion as a person **B** on an issue, **A** is more likely to have **B**'s opinion on a different issue **X** than to have the opinion on **X** of **a person chosen randomly**.

- Rapleaf: using email address/name to get personal profile (linked to information on Facebook)

### Data Aggregator

- Pay as You Drive: car insurance (provide discount according to the driving habit)
- For company with internal technique skill: collection, cleaning, analyzing, result delivery, implementation
- Data Aggregator: provide some hard to collect off-line data (what are those?)
- Who will be data aggregator: those who develop devices for data entry and collection
- More personal, more useful, harder to get
- Payment service companies (VISA, American Express etc.): on the road to data aggregator [VISA collabrate with GAP]
- Aggregate data
     + Internal Data + External Data-->Premiun Data (multiplication effect)
     + Example: Catalina Marketing and Nilson evaluate the TV ad by studying the association between audience rating and actual purchse
     + What data to get? 
     + Example: iphone App: Nike+GPS, get running route (anonymous) and use the information to get insight for store location

### Data Scientist

- Sexy
- Characters:
     + Communication skill
     + Entrepreneuership: explore how to make data useful, lead to new data based services
     + Curiosity: not limited in art, techniques, medicine, natural science......but keenly curious about different areas. By analyzing data from differnt fields, data scientist with curiosity will find bonanza 
     
