# Politics 

## Democracy in America [Tocqueville]

这本书的作者是托克维尔（1805-1859），经历过法兰西第一帝国、波旁复辟王朝、七月王朝、法兰西第二共和国、法兰西第二帝国五个“朝代”。法国著名的历史学家、社会学家、政治家。《论美国的民主》是他在35岁时写的， 之后在41岁时还写了一本经典著作《旧制度与大革命》。托克维尔是法国贵族出身的，受过很好的教育， 但是他思想倾向却是自由主义的。时至今日，没有哪个国家会承认自己是不民主的，甚至朝鲜、缅甸这样的国家也都宣称自己是民主政体。金正恩全票当选，不是还沾了个“选”字么？为什么呢？ 因为今天民主似乎成为了一种普世价值，没有人敢公然去否定民主。问题是你走的是哪种民主政治？ 如果我们不接受民主普选，那否定的理由又是什么呢？从历史上看，并不是人们不知道民主有坏处， 但关键在于这些坏处是否能够掩盖民主的价值？抑或对民主的弊端，我们应该要更多的民主还是限制民主？ 要对民主这个话题深入的理解，托克维尔的《论美国的民主》不得不读。这本书是托克维尔在美国周游一圈回到法国写的， 其中讨论了民主这种政治体制在美国实行的状况如何。书中给出的答案是，要解决民主带来的问题，我们需要更多的民主。 当时欧洲有很多保守主义者反对民主，法国大革命的血腥招致各种批评，在此情况下，这可以说是一本为民主辩护的书。

## On the origin of human inequality (论人类不平等的起源)

> <span style="color:blue">Hui:《论人类不平等的起源》是法国大革命的灵魂。作者开篇提出人类间存在的两种不平等1）自然或者生理上；2）精神或者政治上的。卢梭在本书中主要探讨了精神和政治不平等的起源，这种不平等赋予一部分人以特权。书中讨论了人类发展的过程中权力何时取代了暴力，自然何时让位于法律。本书阐发了卢梭的政治哲学思想，为《社会契约论》奠定了基础。</span>

- Etruscans [艾特鲁斯坎人]：在罗马共和国建立之前统治罗马人民。最后一个王朝是塔尔干王朝（7BC-6BC）

- 公正的条约为你们保障了稳定的边疆、不可侵犯的主权以及国家的安全。你们卓越的宪法，建立在最高的智慧之上，并有伟大而友善的军队保护着。你们的国家享有安宁，你们无须惧怕任何战争和任何征服者，你们惟一的主人就是你们自己制定的法律，并且这些法律由你们所选出的正直的法官来掌管。你们不至太富有，以致耽于享乐而丧失活力，也不会为追求浅薄的快乐而丧失真正的美德和幸福；你们也没有贫穷到国内生产不能自给，以致于需要向外国寻求支援。 [Hui: 这是Rousseau描画的美好人类社会图景]

- 我们掌握的知识越多，我们就丢掉了更多的发现重大问题的工具。人类越是研究，就越不能了解自身。......我们必须从人类体制的持续变化中寻找人类的差别根源。......无论那些变化最初是怎样发生的，人类的所有个体都不可能在同一时间以同样的方式发生变化。......我们无从正确地识别，在人类的真实本性中，哪些是原始的，哪些是后来发展的。......由于忽视对人类本性的研究，我们难以确定自然权力的真正含义，或者界定得模糊不清。

- 早于理智而存在于自然人身上的两种法则：
     1. 人类对自身幸福和生存的深切关注
     1. 人类看到其他有知觉的生物，尤其是同类，在遭受痛苦和死亡时所感觉到的那种天然的不愉快
  ......如果我不想伤害我的同类，这似乎并不是因为他们具有理性，而是因为他们是有知觉的生命。

- 宗教的训诫让我们相信，上帝在创造人之后就让他脱离了自然状态，人生而不平等。

- 霍布斯，孟德斯鸠和康贝尔兰德
     1.  霍布斯（1588-1679）：英国哲学家，著有《论物体》、《利维坦》等。提出社会出现之前存在一个自然状态，并持有“性恶论”观点，认为人天生邪恶，喜欢相互争斗。他的著名论断是：自然状态中的人类，处于一切人反对一切人的战争状态。
     1. 孟德斯鸠（1689-1755）：他在《论法的精神》中说：“当人还是自然状态的时候，他应当是只有获得知识的能力，而知识却是不多的。显然，他最初的思想绝对不会是推理的思想。他应当是先想如何保存自己的生命，然后才能再去推究他生命的起源。这样的一个人只能首先感觉到自己是软弱的；他应该是极端怯懦的。如果人们认为这点还需要证实的话，那么可以看看森林中的野蛮人。什么都会是他们发抖，什么都会使他们逃跑”
     1. 康贝尔兰德（1631-1718）：英国人，针对霍布斯的性恶论，提出万物性善说。
 
- 有无确凿证据能够证明在医学最不发达的地方人们的寿命要比医学最发达的地方的人更短？......如果自然注定使人健康，那么思考就是一种违反自然的状态，而一个思考着的人必定是一种痛苦的动物。......一旦被人驯养，它们便丧失了大半优点。人类也是如此，当他具有了社会性，成为一个奴隶，他就变得胆小，奴性十足。

- 造成人与动物之间差别的不是理解能力而是人的自由意志。另一种差别是自我发展的能力。在环境的协助下，人类通过这种能力逐渐发展出其他能力。

- 没有动物知道什么是死亡，死亡以及对死亡的恐惧的知识是人在脱离动物状态之后获得的最初的知识之一。

- 智力的发展总是与人们的自然需求精确成正比的。

- 我们应该怎样看待农业呢？它需要投入如此多的劳动和预见，还需要依赖于其他的很多技术。

- 似乎天意如此深谋远虑，使人类所拥有的潜能只在合适的时机才得以发展，不致于发展太早而陷入无穷无尽的困惑之中，也不致于发展太晚以致于不能满足后来产生的需要。

- 我们不能像霍布斯那样断言，因为人们不知道善，所以人必定是天生邪恶的，人之所以邪恶，是因为他们不知道善为何物；他不会给同伴任何帮助，因为他认为他们没有权力要求他去帮忙，或者他认为自己有权得到他想要的任何东西，甚至愚蠢到认为自己是全世界的主人。......原始状态的每个人都只关心和平相处的一种方式，因而也是最适合人类生存的一种方式。......（卢梭《爱弥儿》：所有一切的坏事都是来源于孩子气，孩子之所以淘气，只因为他是很柔弱的。）

- 即使嗜杀如苏拉，也为他人的痛苦而伤感，**只要那不是由他造成的**。

- 与其在高深的辩论中，不如在自然的感情中，寻找一个人在他作恶之后会感到内疚的原因，尽管他可能完全没有受过任何教育箴言的启示。

- 人与人之间的差别不过是习惯所致，或者是由人们在适应社会生活时所选择的生活方式不同造成的。

- 即便自然在赋予人类各种禀性的时候有失公正，那么，在人们彼此之间几乎没有任何联系的情况下，哪些受到自然偏爱的人又比其他人多获得了什么好处呢？没有爱情的地方，美丽有什么用处？没有交易的地方，欺诈又有什么用处呢？......只有在人们相互依赖或者有共同的需要将他们联系在一起的时候，才能产生奴役关系。

- 它们是从事物的性质中能作出的最有可能的猜测，也是发现真相的惟一途径。
> <span style="color:blue">Hui: 我们所谓真相不过是最可能的猜测，人终其一生都在自我的影射下生活。</span>
>《爱弥儿》：痛苦的原因不在于缺乏什么，而在于对那些东西感到需要。

- 临时的关系逐渐转变为亲密而持久的关系。......人们开始比较不同的事物，获得了关于美和价值的观念，继而产生偏爱的感觉。......这就是迈向不平等的第一步......一旦人们开始互相品评，尊重的观念便在人的心底扎根，每个人都要求别人尊重他。......冶铁和农业技术促成了这种变革。

- 对于农业耕作来说，必须愿意牺牲即时的需求以换取将来的收获，这种远见是原始人所不能拥有的。

- 自然的不平等随着彼此的联系不知不觉加深了，这种人与人之间的差别通过他们不同的境遇逐渐加大，其影响更加显著，更加持久，并相应地开始影响个人命运。......人与人之间有了等级和出身的区别，这些区别不仅包括个人财富的多少，能影响他人的能力的大小，也在于个人的才智、美丽、体力、技术、价值和智慧，只有这些品质才能得到别人的尊重；不久之后，**这些品质就成为人们必须拥有或者最起码假装拥有的东西了。如今人们的兴趣是假装成他们原本不是的那种样子。** “本来就是”和“看起来是”成为两种完全不同的东西，于是从这种区别中产生了傲慢的虚荣和欺骗伎俩，数不尽的罪恶也开始相继上演。

- 对于富人来说，他们一旦体会到统治的乐趣，就会鄙弃其他一切乐趣，就像一群饿狼，一旦尝到人肉的滋味，就再也不想吃其他食物了。......很难使一个没有野心控制别人的人去服从别人。

- 所有现在盛行的不平等来源于人类能力的发展和思想的进步，并随着这二者的发展而逐渐加深，最终在私有制和法律建立之后，确立为永恒的合法现象。

## The Machiavellian Enterprise [马基雅维利的事业]

- Preface
     - Machiavelli轻视人们一般指望得到和之后得到的东西。...他说道，崇高的事物，头衔也罢，品质也罢，都是用来装潢门面的。崇高的人要装出样子，自己无匮乏之虞；他们关心的是美的事物而非匮乏和实用之物。Machiavelli似乎觉得，**所有的人，无论高低都会有匮乏之物；人真实状况就是不断欲求和之后解决匮乏的状况。**

- Ch1:君主国的类别极其获得方式
     - 《君主论》开篇促请年轻人明白，一心觊觎权位就是有德。
     - 运道和能力形成对照。依靠他人武力就是讲运道；依靠自己的武力就是有自信、有能力。能力和力量相连，运道与虚弱为伍。
- Ch2:世袭君主国
     - 非自然的君主引来了革新，废除了自然君主的先人留下的法律和规章。革新也可能由世袭君主引进，只是这些不明显表现为革新罢了。...不能不做的变动就是革新。
- 混合式君主国
     1. 君主与仆人组成：君主实行绝对的统治，所有的大臣都是君主的仆人
     1. 君主与贵族组成：诸侯有自己的国家和臣民，而且自己的头衔“不是君主恩赐的，而是由自己古老的血统带来的”。这些诸侯有忠实爱戴自己的臣民；他们享有君主也不能夺走的特权。
     1. 自治的君主属地（城邦）
- 要征服一个国家，首先要了解那个国家的基本特征，这样的基本特征类似自然事物的基本特征。一个国家的基本特征可以保持几千年而不改变，因此土耳其的基本特征与波斯的基本特征相同；法兰西的基本特征与高卢的基本特征无异。
- 人们对往昔自由的记忆不会消失？自由的名字比君主的血脉维持得更长。
- Machiavelli提请给予Romulus特别关注也许有他的理由。是否在告诉读者，机会无须来自运道？Romulus似乎没有可以利用的机会；也就是说，他的机会要在自己卑贱的出身里去寻找。
- 国家为实质或内容，人们向实质或内容之中引入统治的形式，也就是国家创建者的心灵和精神的产品。那么建立一个国家和获取一个国家哪有区别呢？

> <span style="color:blue">Hui: 实质上没有区别，最后都是要注入新统治者的心灵和精神。</span>

- 依靠他人的军队和运道新近获取的君主国
    - 依靠他人的军队和运道获得国家的例子是 Cesare Borgia
    
    > Cesare Borgia (1476-1507)，教皇亚历山大六世的私生子，野心勃勃的极权主义者，残忍冷酷，不择手段，一生都想用暴力统治意大利甚至周围国家。 这位被后世无数历史学家斥为堪比尼禄、卡里古拉之流的暴君，甚至更残酷邪恶的意大利大公，在《君主论》中是作为最可效法的君主典范和Italy统一的破碎梦想反复出现的。M不吝笔墨地花费了一个章节来论述他生平的成就。
    
    - 真正的话题却是如何守住运道突然间带来的东西。
    - Cesare的过失就是推选Guiliano Rovere为教皇朱利叶斯二世，他的错误在于认为伟人的行为与常人无异。
    - 第7章不是在谈论靠运道而获取他人疆土的事情。相反地，它还在延伸获取的自然欲望这个主题。...我们看到的是如何在极端条件下，在没有机会，没有军队的条件下获取事物。Alexander和Cesare开始他们获取生涯的时候依靠的不是运道，而且作者也近乎直白地告诉我们，他们失败的原因也不在乎运道。...第7章告诉我们**人依靠智谋可以找到机会，因而智谋可以取代运道。如果运道不好，就必须去做我们指望命运为我们做的事。**...第7章的主题最难理解，也许谈论的是最高层次的获取活动，其中没有运道相助，没有内容可供拿捏，也没有形式用作规约。精神上的坚毅果敢以及深谋远虑是君主需要具备的全部品质。
    - 与Lorenzo和许多君主一样，Cesare了解的仅仅是民众或者社会底层的人，而且知道民众在目睹一场壮观的行刑时心里既有满足又有惊骇。最佳的榜样人物是既了解君主的秉性，有体察下层民心的人。
    - 第1章告诉读者获取活动是其中的话题，这样我们就应该认识到，政治统治是有扩张性的。作者没有区分僭政与合法的统治。我们会得出结论，所有统治都是压迫人的统治，因为如果某人的自由或独立要得以保存，那么他就必须破坏别人的自由独立。第2章里什么是自然君主这个问题提了出来。这部著述的余下部分可以说是来回答这个问题的。
     

## Other

> 中国的资本市场是一个四层结构：散，庄，财阀（某某系，某某大鳄），赵家人（财阀背后的老板）。散户听K线图的，K线图听庄家的，庄家听财阀的，财阀听赵家人的。但凡有看不懂的行情，背后一定是庄家在做局。有看不懂的局，肯定是财阀在背后抢地盘。有看不懂的财阀的命运沉浮，那么背后一定又是一帮赵家人在北戴河谈心。

1. 宝能
     - 创始于1992年，总部位于深圳特区。历经二十余年稳健发展，现已成为一家以国际物流业务、综合开发业务、文化旅游业务、金融保险业务为其四大主要产业，健康医疗产业、民生产业为辅助性产业的大型现代化集团公司。
     - 物流产业方面：宝能旗下物流集团是中国最早开展现代物流服务的企业之一，建设经营的深圳笋岗物流园区占地1000多亩，建有各类专业市场、物流中心及配套设施近300万㎡，形成了八大专业市场。目前，物流集团正在积极向国际高端物流服务商转变，并着力推动笋岗物流园区整体转型，投资60亿元全力打造深业物流中心项目，定位国际性大宗物流产品交易中心及物流企业总部基地。
     - 文化旅游业方面，公司已在全国形成多个具有综合效益的旅游产业集聚区，成为未来二十年集团的核心竞争力之一。正在重点区域布局建设的项目包括：深圳桔钓沙超五星度假酒店、韶关宝能国际旅游度假项目、惠州罗浮山健康生态城等项目。
     - 金融保险业务方面，前海人寿作为宝能集团的核心金融平台，其法人代表正是宝能系的掌门人姚振华。而除了姚振华之外，还有深圳市深粤控股有限公司、深圳粤商物流有限公司、深圳市凯诚恒信仓库有限公司、深圳市华南汽车交易中心有限公司、深圳市健马科技开发有限公司、广州立白集团六家公司。据此前21世纪经济报道披露，宝能集团和上述钜盛华实业、深粤控股、粤商物流、凯诚恒信仓库、华南汽车交易中心等5家公司历史上也有着紧密的关联。
     - 在医疗产业、民生产业上，宝能集团重金布局的一个项目是广州宝仁医院，项目规划总用地871亩，项目总投资超过30亿元，一期建设包括医院、疗养康复、商业配套等。曾有内部人士透露，目前宝能医疗事业正与全国多家医院洽谈合作经营与收购，计划在未来5-10年内，投资500亿元在全国兴建10-20家三甲综合医院，完成辐射北上广深一线城市、省会城市和副省级城市的全国布局，形成大型综合医疗集团格局。
     - 在综合开发业务上，截至目前，宝能已覆盖全国12个省21个重点城市，已摘地开发建设项目共54个，项目总规划建筑面积2800万平方米，旗下包括“8座宝能城、3座宝能环球金融中心、3座宝能金融中心、3座宝能太古城、2座宝能公馆、2座宝能悦澜山”，这是宝能地产在综合物业已开发上的全部数字。
     
1. 华润
     - 前身是1938年中共为抗日战争在香港建立的地下交通站。1948年改组更名为华润公司，1952年隶属关系由中共中央办公厅变为中央贸易部（现为商务部）。1983年，改组成立华润（集团）有限公司。1999年12月，与外经贸部脱钩，列为中央管理。2003年归属国务院国有资产监督管理委员会领导下的中央企业。主营业务包括日用消费品制造与分销、地产及相关行业、基础设施及公用事业三块领域，旗下共有20家一级利润中心，在香港拥有5家上市公司：华润燃气（HK1193）、华润创业（HK291）、华润电力（HK836）、华润置地（HK1109）、和华润水泥（HK1313）。2013年7月8日，《财富》杂志发布的世界500强排行榜，华润集团名列187位，首次进入200强，排名上升46位。2014年，最新发布的世界500强排行榜，华润集团名列143位，再升44位。2015年7月22日，美国《财富》杂志发布2015年世界500强企业名单，华润集团以115位的优异成绩再次上榜，相比去年上升28位。

