# Jokes

- 56个民族55个加分
- 期末考啦，老娘不给你露一手，你还以为你教的好呢！
- 毕业不分手，异地绿成狗
- 千万不要以为你高中单身是因为学校禁止早恋......
- 婚姻就像围城，城里外的人想进去，城里的人玩的好开心。
- 据说新不孝有三：学文、考研、没对象。
- 淘宝精神: 为了省钱而花光身上所有钱的精神。
- 民主是一种很复杂的东西，复杂到这是中国人唯一没能山寨成功的东西。
- 某博士的毕业答辩会上，一个评委抱怨说：“你这论文写的什么啊，我看了3天都没看懂！”博士暴怒到：“这篇论文我写了3年，你才看了3天居然就想看懂，你当我在写小说啊？！”会场一篇寂静，遂全票通过答辩。
- 妈妈说，该学习的时候我在谈对象，该上班了我又跑去搞学业了，现在该谈对象的时候又在忙工作，然后就变成剩女了！说完最后还总结了一下说，我这辈子都在着重搞副业……
- 据说这是最早的呻吟体：  
……..密……封……线……内……不……要……答……题……
- 你瘦的时候在我心里，后来胖了，卡在里面出不来了。
- 唾沫是用来数钞票的，而不是用来讲道理的。
- 人生五大标准答案 ：喜欢就买 不行就分 多喝点水 注意安全 重启试试
- 一帮老头儿老太太无所事事，就去上老年大学，有一天集体忘记做作业了…… 校长闻知大怒，罚他们集体操场罚站，同时还带来了一个道士，好一阵的舞剑、画符、念咒、烧纸……老人们都看的不明就里，就问这是要干啥，校长很严肃的说道：干啥？请家长！
- 从来扯着嗓门喊着要走的人，都是最后自己把摔了一地的玻璃碎片，闷头弯腰一片一片拾了起来。而真正想离开的人，只是挑了一个风和日丽的下午，裹了件最常穿的大衣，出了门，然后就再也没有回来过。
- 刚刚一个很帅的帅哥在我面前，我们相视了很久，谁都没有打破这份平静。直到手累，我才慢慢的放下了镜子。
- 生子当如孙仲谋,找爹就找金日成。
- 这小伙子长得,把脸挡上跟个演员似的…
- 有刺青的不一定是流氓,他可能是岳飞。
- 都说女人是一本书，姑娘，您这身材，是合订本…… 
- 一个和尚挑水喝,两个和尚抬水喝,三个和尚没水喝,四个和尚斗地主,五个和尚可以去扮福娃了
- 拿什么来拯救你你这个贱人。 
- 您真是贱人多忘事啊 
- 黑猩猩不小心踩到了长臂猿拉的大便，长臂猿温柔细心地帮其擦洗干净后它们相爱了。别人问起他们是怎么走到一起的？黑猩猩感慨地说：猿粪！都是猿粪啊！
- 明天你醒来，枕边躺着一只蚊子，身边有一封遗书，上书：我奋斗了一晚，也没能刺破你的脸，你的脸皮厚得让我无颜活在这世上！主啊~宽恕他吧！我是自杀的。
- 一日 一对苍蝇母 子在一起吃午餐, 儿子问苍蝇妈妈:为什么我们每天都吃大便啊?苍蝇妈妈生气的说:吃饭的时候不要说这么恶心的话,趁热吃!!
- 两个饺子结婚了，送走客人后新郎回到卧室，竟发现床上躺着一个肉丸子！新郎大惊，忙问新娘在哪？肉丸子害羞的说：讨厌，人家脱了衣服你就不认识啦!
- 某晚，一裸男叫了一辆出租车，女司机目不转睛盯着看他，裸男大怒，吼道：你他妈没见过裸男呀！女司机也大怒：我看你他妈从哪儿掏钱！
- 狼崽从出生就吃素。狼爸狼妈绞尽脑汁训练狼崽捕猎。终于有天狼爸狼妈欣慰地看到儿子狂追兔子。狼崽抓住兔子凶相毕露恶狠狠地说：小子！把胡萝卜交出来！
- 巴黎圣母院少个敲钟的，就你了。
- 你出生时是不是被扔上去过３次而只被接住过２次？
- 你的牙如同天上的繁星，色泽鲜艳，相距甚远
- 《翻身姐妹》经典语录：
    1. 一个在前男友面前把礼服撑爆的人，什么事儿都干的出来的。
    1. 这是释放金钱和欲望的时刻，是渴望良知与本能的战争。我们的敌人非常强大，却又不堪一击；非常疯狂，却又想时刻保持着理智；一个伟大的党派，一个通知全宇宙的党派，它的名字就叫作，剁手党！
    1. “嗷嗷有钱”、“36D从不偷工减料，人送外号110”、“完美长腿110” 、“颜值爆表姐妹团”、 ”腹黑麻辣段子手 ”、“火腿肠海滩照大法”、“多挣钱，养好膘，世界末日也风骚”、“你不爱我的钱，我怎么带你愉快的玩耍”
    1. 我的人生就像西直门的立交桥，你是永远都不可能找到方向的。
    1. 别闹了，这世界上怎么会有女汉子呢？只不过都是些又穷又丑的女吊丝罢了。
    1. 你不可能一辈子绝望下去的，时间久了就习惯了呗。
- 说个上大学时候的事，寝室有位仁兄，整天对着电脑玩魔兽，衣服差不多一个星期洗一次，每次都是一大堆全放进盆里，用洗衣粉泡着，十几分钟后用水一冲搞定，问他都不用刷也不用揉的吗？这牲口瞟都没瞟我一眼回句：我用的是奥妙全自动。奥妙全自动？全自动？
- 晚自习的时候考试，拿出手机搜答案，突然，老师把灯一关，我……亮了。
- 感觉别人都是吃几口就饱了，而我是吃饱了还能再吃几口…
- 心情不好我就坐公交车，坐在有长头发后面的给她剪头发。(Hui: 谁家养大的熊孩子，主意这么损你爸妈知道么？)
- 在学校宿舍，我杯子里的水总被偷喝，用涂改液在杯子上写了：“别喝！”水还是不断减少，某天吃完药，剩两片不想再吃了，顺手扔杯子里了，第二天早晨来刚坐下，听见后方某男生低沉的声音幽怨地说：“够狠的啊，下药了！”
- 话说有一个美国小伙来中国留学，跟同宿舍的一个中国同学很是要好，俩人约定互相教对方语言，一年后，中国小伙顺利的通过了英语八级考试，而美国小伙则操着一口流利的河南话回到了美国。
- 下午去求个佛珠，小和尚告诉我说：方丈去进货了。
- 我一生气就想买东西,一买东西就得花钱,一花钱钱就少,钱一少我就生气。
- 只要瘦，什么都百搭，要是胖，什么都白搭。
- 几个吊丝出去秋游，坐车的时候，售票员问：你们从哪里来，要去哪里啊？ 他们幽默地齐声答道：“我们从东土大唐而来，要到西天取经去。。。”全车的人都笑了。售票员回道：“几位大师坐错车了，我这是往东南方向的，往西去的请到路对面去坐！”其中一个来了句：“那我们先去南海见下观音姐姐....”
- A：“帮我想个旅游节目宣传语，需要主题明确，意境突出，既能尊重别人，又可以突出自己。内容要略带性感，不显浮华，最好让人听一遍就记住。” B：“……大爷，来玩撒！”
- 红孩儿到底是不是牛魔王的儿子？铁扇公主会不会跟太上老君有什么不可告人的关系？芭蕉扇是太上老君摘的，却在铁扇公主手里；牛魔王根本不会三昧真火，红孩儿却天生就会。。。真TMD耐人寻味！吴承恩下了很大一盘棋？！
- 火车上，一乘客对乘务员说：“给我来瓶可乐，多少钱？” 乘务员：“8块。”乘客：“多大一瓶的？”乘务员：“就是外面卖3块钱的那种!”
- 上小学的时候，在路边买了个小葫芦，上课的时候偷偷在下面玩，不巧却被老师发现，问我在干什么，我不知道哪来的勇气，脑残的把葫芦举起来，对着他，说了一句：“我叫你一声，你敢答应吗......”
- 小时候的的三大偶像：雷锋、张海迪、小兵张嘎。简称“雷迪嘎嘎”
- 人生就像高压锅。压力太大的时候自己就熟了。
- 如果我能原谅你的庸俗，那么你能原谅我的装逼么？
- 蓝精灵对着阿凡达唱：“长大后，我就成了你”。
- 本人女，身高165，特羡慕那些娇小依人的小女生。某天晚上我弱弱的问道：老公，你是不是特羡慕那些老婆小鸟依人型的？我好像这辈子也没个机会了…老公看都木有看我一眼，说：“没关系，我是杨过。”心下暗喜，难道老公以为我是小龙女般的~“为什么呀？”想不到这厮来了句：身边跟个大雕。。。[Hui: Haha~~]
- Get your facts first, then you can distort them as you please.[MT]
- All you need in this life is ignorance and confidence, and then success is sure. [MT]
- 刘备问诸葛亮“你最喜欢是歌手是谁”。诸葛亮说“Justin Bieber”。刘备又问“为什么”？  
诸葛亮回答：“因为我特别喜欢他的一首歌”。刘备好奇的说“唱两句听听呗”。诸葛亮脸一红，唱到：“备备，备备，备备，哦…”
- 如果世界上只剩下他和一块砖头，我一定用板砖拍死他……