# Other 
## [Nov2015]不畏将来不念过去

- 若想改变,就从丢弃旧物开始 你留存的记忆越多,就意味着未来可以伤你的越多。你留存的记忆越细致,越是容易铸造出一个思维的牢笼,困于其中 ,越陷越深。 

> <span style="color:blue">Hui: 收藏旧物无关对错，是一种生活方式。我喜欢保留旧物，人是由记忆浇灌的，为什么记忆一定是伤人的？你会被记忆所伤，说明心灵还不够强大，还没有释怀，人生就是一场修行，路漫漫其修远兮。人生从来就不完美，回避隐藏并不能让你强大，面对真相、释怀才是最终的救赎，而后自道天凉好个秋。回避是因为在乎，刻意回避反而加深了刻痕，离释怀越远。</span>

- 到了最后,就在那个愿意放下偏见和骄傲的时候,遇见一个同样愿意的人,在一段靠谱的感情中,走向一段靠谱的婚姻
。然后,所有的剧情都落幕了,剩下的事,该来到的都来到了。不是因为你更爱谁,就可以不用面对那些鸡毛蒜皮,只
是愿意和不愿意而已。
- 欲望和天真绝无法做伴。
- 有勇气在世俗与爱情中找到平衡的人,才能相信他可以将爱情进行到底。这是我们这个时代的爱情。
- 艳遇其实就是在不提前设想、不设防的情况下发生的美丽意外,是都市人久久不敢随心而动之后,对自己内心直觉灵感的一种释放。
- 预言的自我实现:以没有确凿证据的预言为契机,唤起一种新的行动,这种行动最终使 起初的预言变为现实
- 真正的专家首先要理解专家的基本条件,然后再去思考如何成为专家。
- 我再提出一个预言——“任何人都能够成为专家”。

## Living History Farms
**Foodways**: The Ioway made use of Iowa’s prairies, rivers and wooded valleys to find food. They hunted and fished for meat. They gathered wild plants. The Ioway farmed along the rivers. Many foods were eaten fresh, while others were dried and stored for the rest of the year. The Ioway ate fresh food in season. They ate some foods raw, but also cooked many foods at ta fire pit. Each family prepared their own daily meals. Iowa women preserved food by drying it. They cut fresh meat into thin slices and hung it to dry in the sun. Ears of corn were hung from poles or speed on platforms to dry on the vine and then shell them. Squash were sliced into thin rings and hung on frames to dry. The Ioway used dried foods to make stews, the main dish in their diet. Dried meat was also pulverized and mixed with berries and animal fat to make pemmican. Dried corn could be ground into flour for breads and thickeners.

**Storing Food**: The Ioway stored dried foods in cache pits, bell-shaped holes dug into the ground. The cache pit could be up to five feet deep. Women first lined the pit with bark or grass to keep put moisture and pests. The Ioway then added ears of corn along the outside, filling the center with ben and then squash. The opening was covered by layers of animal hide, grass, planks and ashes.

## Knowledge Graph [知识图谱]

- 知识图谱就是把不同种类的信息(Heterogeneous Information) 
- 连接在一起而得到的一个关系网络。知识图谱提供了从“关系”的角度去分析问题的能力。
- 知识图谱是基于图的数据结构，它的储存方式有两种形式：RDF存储格式和图数据库(Graph Database)。

> <span style="color:blue">Hui: 如何将网络上的非结构化数据，利用机器学习、自然语言处理技术变成结构化数据？</span>

- 所谓的生态闭环，指的是构建有效的自反馈系统使其能够实时地反馈给我们的模型，并使得模型不断地自我优化从而提升准确率。

## Other Notes

- After all, the wool still comes from the sheep’s back-----in the long run, whatever you’re given you pay for.
- In the end, it’s not the years in your life that count. It’s the life in your years.
- 强关系有效是因为帮助你的意愿更强；弱关系有效，是因为帮助你的能力更强。为啥？因为弱关系更可能跨界，所以求助能力的理想状态是——在不同跨界领域建立多个“强关系”。
- 什么是淫秽？Stuart法官回答：看下才知道。很多概念，在大而化之的时候都可以存在，但一追究细节，立即土崩瓦解。
- 对他人要公平，否则会触怒他人与生俱来的本能。对自己千万要记住没有什么公平。长相，身高，家世，运气，从不公平。动辄要求公平，是失败者的标配。每要一次公平就意味着你对这个世界已无计可施。
- 人类文明至今只有2个大的类型：1） 农耕文明（agriculture civilization）：土地资源决定 社会结构和权力归属；2)工商业文明（industry and business civilization）：人们摆脱了土地资源的限制，可以跨区域（cross-region）获取生存资料（living resources）。在这种文明中，金钱的力量成为决定性因素（determining factor），而权力则处于高度不稳定 。坏处是竞争太激烈。好处是精英永远有机会。
- 思想录（Pensees）——17世纪哲学家、数学家 Pascal为基督教辩护的一本书——选自其中的一句话“人类不快乐的唯一原因是不知道如何安静的呆在房间里。(The sole cause of men’s unhappiness is that he does not know how to stay quietly in his room.)”
-  生活里有我们不喜欢的人，但没有比我们身份低配不上我们的人。愿意善待眼前这个世界的人也一定会被这个世界温柔相待。
- 花太多时间去思考只有时间才能证明的威胁和承诺是一种危险的游戏。
- 一个嫉妒你的朋友比一个公然的敌人更可怕。
- 人类善于撒谎，尤其是自我欺骗。
- 没人拥有一切，珍惜并充分利用自己已经拥有的东西。
- 独处慎思，群处慎言。（Govern your thoughts when alone, and your tongue when in company.）
- 长久不快乐，人的“快乐基因”会逐渐消失，不自觉嘴角下垂眉间纹加深，这副面孔又会吓退很多原本能带给我们愉悦的人。不要成为生活中那个难以取悦的人。不快乐的原因有：1)快乐门槛高2)快乐外因多。源自于内心的喜悦简单、稳定、强大。
- 恋人常有张居安思危的脸，为小事惴惴不安。
- 内心强大的10个特质：1)being firm in your belief yet be flexible enough to change when proven wrong ; 2) being aware and cautious yet not giving a damn to everything cross my life; 3) being calm in calamity and a cracker in celebration; 4) being experienced like your grandfather yet energetic like a child; 5) being well read though knowing you still know nothing; 6)being intelligent with a strong memory yet deleting all the trash and negativity; 7) being able to observe and learn from others’ mistakes yet not fearing to make my own; 8) being the one that all look up yet not looking down upon them; 9) being able to help others yet making provisions for your own self; 10)being able to accept defeat with grace yet not resting a moment to achieve success once again
- 从狭小 的世界到广大的世界去的路上是有风浪的。——《家庭与世界》泰戈尔
- 遇到困难是生活的一部分，和困难相伴是人生的常态。生活有时就像 一张铁砂纸，由无数细小，坚韧的铁粒构成，即可磨损你的意志，也可磨亮你的人生。
- 一个人的学识、思想、性格、格局会天然散发一种气味。
- 看尽别人的故事，你一直努力做个例外，然后发现逃不出相同的结局。
- 人总怕被拒绝，但怕是无法避免的，上帝赋予你恐惧的技能。
- 对理解不了的局面退回到道德判断。
- 热情：总想和别人融为一体得到认可和安全感的情绪。
- 不是价值观，共同体这样可以说清道明的东西把人连在一起，而是无法表的的共同体验。
- 就像我们看到所有的东西一样，我们希望“看到”自己也是真实存在在这个世界上的。Nathaniel Branden (1930-2014, Canadian-American psychotherapist and writer known for his work in the psychology of self-esteem)
- Tell me who you love and I will tell you who you are.
- A wise man thinks all that he says, a fool says all that he thinks.
- 《有限与无限的游戏》把这个世界上的游戏类型分成两类：  
1.有限游戏——所有当事人同意结束，就结束了。这种游戏从属于人。小到围棋，大到战争，都是如此。  
2.无限游戏——人的存在只是为了维持游戏本身的延续。比如经济系统、人生荣耀。想伟大，就要把所有的有限游戏变成无限游戏。想快乐，就要把所有的无限游戏变成有限游戏。伟大且快乐者，在这二者之间来去自由。
- 人生来自由，却无往不在这场以有涯随无涯的博弈(all pay auction) 当中。出路有四：  
第一，不参加。  
第二，如果你一定要下注，就在目标价值以下随机下注，一次性下注，不追加下注。  
第三，如果你一定要参加多轮的全付费游戏，就得从主观上调整这个游戏对你的payoff，毕竟效用因人而异。  
第四，在不能赢的大游戏中刻画出有可能赢的小游戏。不必成为芭蕾舞明星，练练芭蕾舞，只为怡情行不行？  
一个建议对所有人都有用：不要以人生为赌注，不要把回报寄托在将来成为赢家；要让人生本身就是回报，当下就是回报，最好每一刻都是回报。当下就要快乐，最好始终都快乐。
- Uncertainty arises because of limitations in our ability to observe the world, limitations in our ability to model it, and possibly even because of innate nondeterminism.
- 一句很动人的情话：“迟早会有人举着戒指对你笑，说着余生请你多指教。”
- 如果私人领域一直无法理直气壮地言明权利边界，那么公共空间自然更加无处构建。所以，我们一直有意无意地被置于一种混沌之中。在这样的渊源之下，我们单独去强调私德、公德、教养和素质都是无效的。定义人和人之间的界限是尊重的基本条件。清楚的意识到我要的并非是你要的，己所不欲勿施于人，己所欲也并非能够随意强加于人。只有定义了边界，才能将他人作为一个独立的个体来尊重而不只是自我的延伸。
- 爱自己不是自私自利不懂宽容改变，会爱自己是指你可以完全按照自己的意愿生活，并且还能拥有别人的爱与呵护，不论单身还是已婚，这种女人的气场里总是带着温暖与惬意，更多的时候这也是一直自律和心境的比拼，赢得自己才能赢得人生。会爱自己的女人无论嫁给谁都会幸福，即便你谁也不嫁那幸福的姿态和模样也依旧会光芒万丈，你对爱自己这件事念念不忘，那么绽放和飘零就都是美。“慎独”二字也适用于对生活和情感有较高追求的女人，在没有旁人的时候也凭借高度的自觉，坚持做那个最美好也最精致的自己。不允许自己懒惰邋遢，不允许自己脆弱逃避，不允许自己没有期限的痛苦彷徨，住整洁的屋，睡温馨的床，穿干净的衣，读温暖的书，交有益的友，爱值得的人。就算这些你也需要时间努力拥有，那我也希望你的这个夜晚，会因为这些文字而展露出你最美丽的笑颜，从明天起定个短期计划先去做，能做多少做多少，唯独不要怨天尤人和自暴自弃。天生丽质的女子凤毛麟角，绝大多数的美人儿都是后天养出来的。终究不是岁月败美人，而是美人惊艳了时光。
- 在多少岁恋爱结婚不重要，重要的事和你共度余生的那个人是不是最正确的人，是值得你去珍惜并且相处起来很舒服的那个人，是你可以做真实的自己和最好的自己。好的爱情可以让人变得更好、共同成长，爱本就是两个人相互磨合的过程，如果不适合相处起来会很困难。遇不到那个人可以慢慢等，去提升自己，努力变得更优秀。要么不爱要么深爱，对自己的幸福负责，不随便牵手，不轻易承诺。遇不到真爱，是因为你活得还不够漂亮，出色的颜值包括外在的精致和内在的才华，只有当你的脸能够闪烁出迷人的气场，你心灵的丰盈才能让身边的人感受到力量，缺哪一样你都算不上活得漂亮。不要以为你变得冷漠就是你的成长，成熟的你应该变得温柔，对全世界都温柔。
- 已经失去的东西就不必再停留，成长就是一段又一段锥心的痛，不计后果的那一段叫青春，从此以后我们必须独自长大并且担负责任。过得好当下的人，是不需要忧虑未来的，当温柔已经成为了一种处事的能力，女人的才华才能尽显华彩。
- 丈夫到底是个什么东西？放在那里不打理就长荒草，天天擦一遍他又会跑，一进家就打蔫出了门来精神，在你面前浪漫风情全不懂，在别人眼里却是情圣一大个。其实没什么好不懂的，丈夫，一丈之内是你夫，一丈之外是个男人，还担当着很多的社会角色，他们需要有更广阔的天地驰骋，以便更有能力来善待家人。这个社会有钱不是万能的，没钱也是万万不能的，“能力”这个词也已不能简单的用一声“我爱你”来诠释了，成为了丈夫后,他们还需要有让妻子和孩子享受基本幸福的本领，有时候丈夫们也没什么错。如果连这一点担当与责任心都没有的话，是不配升级做丈夫的。丈夫这东西，其实就是愿意为你一个人守候的那个男人，初衷都是好的，你要相信这一点，过程都是不容易的，你要理解这一点。
- 一半算是自嘲，一半算是抖落一下世俗生活的尘土——做雅痞这件事儿，其实的确还是挺辛苦的。
- 话糙理不糙，人生如妓，努力达到角色与体验的高度统一，才是正道。
- 不要评价一个人的出身，因为这无法改变；**不要评价一个人的遭遇，因为你不知道他的故事**。**不要评价一个人的感情，除非你参与了他的人生**。与其关注一个人的未来，不如是踏踏实实做好自己。
- 《西西里的美丽传说》里，莫妮卡·贝鲁奇的丈夫死在了战场，而她作为一个美艳的寡妇，失去了男人的保护，也没有任何经济来源，她于是只有通过出卖身体换面包吃。在那个战争年代，人都是很矛盾的——男人都想得到她，却纷纷假装厌弃她；女人都想成为她，却都想扑上去摧毁她，在背后毁灭她。其实她没有什么过错，她最大的过错就是生的太过美丽。
- “大家一定要小心那些有六块腹肌的男人和永远保持好身材的女人，这些人拥有你所想不到的决心和意志力。想一想大白天里，他们能“唰”的一下从床上爬起来，到外面跑上几圈。多可怕啊！他们什么事都能干得出来。这绝对不是一个笑话，但凡是有一副好身材的人，活得都不会太差。”
- 变态的工作关系也是应该避免的，你们要特别避免在你们不崇敬或者不想像他一样的人手下干活，那是很危险的。所有人在某种程度上都受到权威人物的控制，尤其是那些为我们提供回报的权威人物。在我年轻的时候，我的办法是找出我尊敬的人，然后想办法调到他手下去。在你们正确地仰慕的人手下工作，在生活中取得的成就将会更加令人满意。
- 在遭遇一件令你难以接受的悲剧时，你永远也不能因为摆脱不掉它的困扰、在生活中再屡遭失败而让这一件悲剧变成两件、三件。
- 复杂的官僚程序不是文明社会的最好制度。更好的制度是一张无缝的、非官僚的信任之网。
- 如果你的思维完全依赖于他人，只要一超出你的领域，就求助专家建议，那么你将遭受很多灾难。
- 技术从来不是人性的反面。  
技术只是人类机体的延伸。  
技术是人性最充分的显现。  
技术如果出问题，是人性本身出问题。
- 《死时谁为你哭泣》的作者罗宾·夏玛说：“不是因为某件事很难，你才不想做，而是因为你不想做，让这件事变得很难。”
- 有民主就不会有财富上的平均分配，平均按需分配是社会主义国家假想的现象。民主意味着一种精神上的平等，决定权上的平等，但在此基础上，人便会自动在财富的分配上区别开来，除非认为强制分配，否则无法平均，因为人的能力，品格和运气各不相同。
- 找到适合自己的工作与生活的平衡方式。人要取得平衡，不在于每天花多长时间工作、又能余下多长时间过自己的生活，而是在于你的选择：在于选择要什么、选择做什么、选择如何有质量的去做到，也在于你是否能寻求到内心的那份安宁与坦然。
- 培养并尊重内心的直觉。是的，在战术层面上，数据非常有用，但是，在战略层面，一个卓越的市场人的直觉同样可贵。因为他们的直觉能让公司看到数据看不到的东西——那些深藏在消费者心里的东西。例如：品牌的定位（是应该聚焦在一个诉求还是更多），品牌/产品的命名，一个品类到底需要多少个品牌才能获取最大市场份额等等。
- 爱情就是两个人一起犯贱，突然一个人不犯了，另一个就SB了。
- 说走就走是人生最华美的奢侈，也是最灿烂的自由。
- If you don't understand my silence, you will never understand my words.
- 人生自古谁无死，贱人先死我后死。
- 幸福如人饮水，冷暖自知。你不是别人，怎知那人走过的路，心中的乐与苦。
- 时间不知不觉，我们后知后觉。
- 认知没有什么终极正确，只有逐步升级。认知的升级，本质上来源于认知尺度的扩展。
      1.时间尺度——多读历史。
      2.空间尺度——多观世界。
      3.观念尺度——聆听高人。
认知没有正误之别。但确实有高下之分。因为所在尺度层次有异。
- **[机会成本]** 我做的事情价值多少，是由我放弃的事情反映出来的，而我放弃的事情，也是由我做的事情的价值反映的。同样的资源你怎么分，同样的抉择你怎么选，将一个人的层次或者说特质表露无疑。在你实际行动的诠释下，一切的言语都是很苍白无力的： _你做了什么，你就是什么，值什么_。
- 我与巴菲特工作这么多年，他这个人的优点之一是他总是自觉地从决策树的角度思考问题，并从数学的排列与组合的角度思考问题。
- 阅读本身并不是力量的来源，因为阅读所触发的思考和情绪才是。阅读一篇文章，触动一种情绪，持久保留下的是这种被触动的情绪而不是文章本身。一门学问最终要被转化成见识和技能保留下来。系统知识更多是在代与代的传递时才更加重要。
- 怎样拥有一学就是十几个小时的精力？
      - **增加精力储量:** 健康饮食，适度锻炼，充足睡眠。主动、适时地在疲劳之前及时地休息，调整好状态之后再开始学习和工作而不是强制自己学习，可以有效地延长我们的工作时间。
      - **减少精力的消耗:** 困难的、陌生的、缺乏主观意愿、反馈周期时间长、没有正反馈的事情消耗人的精力就比较严重。防止出现严重的自责情绪。越熟悉，消耗的精力会越少。尽量在熟悉的环境，把生活琐事都变成习惯和规律，尽量减少杂乱事务对自己精力的消耗，把自己旺盛的高质量的精力都投注到学习和工作上。
- 忍得了就忍，忍不了就改变，改变不了就认了。
- 莫与小人为仇，小人自有对头。
- 有些事很多人在做，你不做不代表你错了。
- 心中有敌，天下皆为敌；心中无敌，无敌于天下。欲胜人者先自胜，欲卑人者先自卑。
- 很多人在重组自己偏见的时候还以为自己在思考。
- 诺不轻信，故人不负我；诺不轻许，故我不负人。
- 如不识货，一时穷；如不识人，一世苦。
- 社交之所以累，是因为都想表现出自己其实并不具备的素质。
- 我们通过浪费每一分每一秒创造属于我们的历史[博尔赫斯(Jorge Luis Borges)]
- 不可知论（agnosticism）英语中agnostic这个词来源于希腊语a（没有）和gnosis（认识），这是最早在1869年由英国的托马斯·亨利·赫胥黎(Thomas  Henry Huxley)创造的，用于描述他的哲学。
- 人生是没有回头的。你必须一直往前走。错了不要紧，摔倒了也不要紧。要紧的是，你还有希望，你还有改正的勇气和爬起来的力量。
- 很多时候，这些小小的，细致入微的东西。轻易地被我们所忽略，以为这些都是应有的。而当我们遇到困难时，却习惯性的把它放大。仿佛这是一道坎，永远也跨不过去。而随着时间的推移，慢慢回忆过往经历时。发现，当时所遇到的东西根本就是小事一桩。只要轻轻一跃，就可跨越。
- 我们永远不知道，生活会从我们手里拿走什么。同样的，我们也不知道，生活会塞到我们手里什么。世间从无卑贱之物。是我们自己，将它想得卑贱了。其实，人心同草木一样，只是简单的存在。何来卑贱之说呢？
- 时间是怪物。它残忍而冷血。却又绵长而温情。它带走一切，却又治愈一切。
- School is learning things you don't want to know, surrounded by people you wish you didn't know, while working toward a future you don't know will ever come.[Dave Kellett]
- Every person takes the limits of their own field of vision for the limits of the world.[Arthur Schopenhauer]
- 情绪成熟的人走进屋里说的第一句话不是“宝贝，我来了”，而是“亲爱的，你在这儿！”。他们可能不是很有趣或者亮眼，但他们不是每分每秒都需要其他人的鼓励。他们愿意给你鼓励。当你成功时，他们为你开心，但不是因为他为你的成功奉献了很多，而是单纯地为了这件事情本身。**爱情的最高境界是对方可以看到你是谁，而这就要求他们愿意放弃对自我的过度关注。**
- Reading makes a full man, conference a ready man, and writing an exact man.[Bacon]
- 尊重生命本身，多去感受其中有趣的体验，而非简单快速的生活方式。...生活的意义是即使一个人，也能把日子过得热气腾腾的情趣。
- 如何获取知识

   > 1. 投入感情：人会对某些瞬间记忆犹新，因为在投入时大脑会建立更深厚的情感关系，强化人回忆事情的能力。因此我们在阅读时投入感情有利于记住东西，日后积累的基础上创新。
1.  学习金字塔理论：学习金字塔理论认为，学习最有效的方式是将学到的知识传授给别人或马上付诸事件。学习源于犯错，犯错源于行动。
1.  猎奇：让思想碰撞：研究发现特殊经历能产生新的神经联络，会和你已有的思想碰撞。与不同的人交往，或者尝试新的事情往往能产生新观点。  
以上3个方面也解释了为什么人们在旅行或者留学的时候能够产出更多的东西。
 
- 如何构建知识体系

   > 1. 建立知识之间的联系——阅读时问自己，还有什么现象可以被这个知识解释？
1. 构思知识的多种用法——问自己，这个知识可以用于做那些事情？
1. 探索事物背后的原因——遇到反常或有趣的事情，问自己：为什么会这样？哪些理论可解释？相似的事件？

- 大城市 v.s 小地方
    - 自己要什么？
    - 长期生活能给自己带来什么？
    - 自身能力能否在此安身立命
    - 代价 
有的人想要的就是安稳，希望今天的样子就是生命的终点的样子。但有的人就要“无限的可能性”，那会让你觉得刺激而充满希望。

   > 一线城市
- 以能力而非资历，背景去判断一个人
- 尊重生活方式和文化的多元性
- 丰富的公共生活和以尊重隐私为前提的人际关系
- 每天变化，总遇见不同的人和事

   > 小城市: 安稳，安全，可控, 人际关系的亲疏更倾向于对血缘，地缘的依赖

- 山泉绕屋知深浅，微念沧波感不平；小院西风向晚晴，嚣嚣恩怨未分明。

- 大家一定要小心那些有六块腹肌的男人和永远保持好身材的女人，这些人拥有你所想不到的决心和意志力。想一想大白天里，他们能“唰”的一下从床上爬起来，到外面跑上几圈。多可怕啊！他们什么事都能干得出来。这绝对不是一个笑话，但凡是有一副好身材的人，活得都不会太差。

- Aren’t entrepreneurs supposed to be gregarious and commanding-----verbally adept and able to inspire employees, clients and investors with the sheer force of their personality?

- 一百个变淡的朋友就有一百种变淡的原因，但本质都是“道不同”。我们的机遇再也无交汇，我们的经历再无相似，你的苦闷我无法理解，我的彷惶于你而言是变相的炫耀。

- 有欲望的人注定痛苦，因为有华丽的梦就有贫瘠的现实。当欲望时刻鼓励着你本该平静的心，你就很难低下头来，老老实实接受目前没有起色，甚至很长一段时间都没有起色的生活。大城市的可怕之处不在于高消费，快节奏和复杂的人脉，更在于你视野开阔之后不断膨胀的欲望和野心。

- 在性行为上，人类有两大发明——
   1. 延缓性过程的时间，以获取更多快乐
   1. 发明正面性交姿势，以获取更多快乐

- 为什么要快乐？作为以生存繁衍为第一目标的生物，要那么多快乐有毛线用？答案也许是——
   1. 协作是人这个种群的首要生存法则。
   1. 快乐可以增进协作。

- John Carter 发现，取得伟大成就的人和取得一般成就的人最大的区别有两点：  
   1. 他们相信自己，他们认为自己可以改变什么
   1. 他们喜欢问为什么，无法容忍自相矛盾，模糊性和不清不明。保持对世界的好奇心。
   
- 段子手：用做学术的手段去学习如何成为一个合格的段子手：）
    - 记性好：大多数人不知道记忆力的重要性，也不知道记忆力就是要不断练习的。就这么简单。从短段子开始，到长段子，到做一次公开演讲，到讲好一节课，到讲清楚一个理论…… 全靠记忆力，这是有效沟通的最基础技能。仅在这一点上，大多数人已经败掉了。
    - 脑子里要装下很多很多的段子。因为最重要的“铺垫”，其实是寻找合适的听众和合适的场合。所以，脑子里要装下很多很多的段子，只有这样才能提高“在恰当的场合面对恰当的听众，恰好有合适的段子可以讲“的概率。
    - 所有的能力，都跟前一样，可以“攒”出来；段子也一样，要搜集，要整理，要归类，要重新组织……这事儿非常隐秘。其实是因为每次都是为了获取最好的效果，都不得不选择“罪不经意的方式”去讲，导致的结果就是大多数人误以为这是一种天赋，这是一种有天赋的人才能“信手拈来”、“随心所欲”的本领 —— 其实根本不是。
    - 每一次的“成功”，都是一种积累。一方面是自己的各种技巧熟练程度的提高，比如，识别恰当时机、恰当听众的能力的提高，捕捉听众细微反应给予恰当的刺激的能力的提高。另一方面是在听众心目中自己的声誉积累；这很重，要因为下次他们会更自然而然，甚至更不由自主地配合你 —— 这是一种良性循环形成的过程。

- 总体上来看，“美国人一年读多少本书”、“中国人一年读多少本书”、“犹太人一年读多少本书”，这类问题其实意义并不大。在哪儿都一样，真正尊重知识的人就是少数，古今中外都一样。

- 婚姻是件小事

    1. 并非每个人都适合婚姻。这是需要首先明确的事。
    2. 婚姻是一件小事。这是第二件需要明确的事。
    3. 我们仍然处于匮乏的焦虑当中，**对于任何事都抱持着争抢资源而不是随遇而安的心态，当然，这其中也包括寻找结婚对象。**
    4. 婚姻，其实不过就是一种人际关系。它不是一种本能需求，和吃饭、喝水、呼吸不同，绝不是每个人都需要的。
    5. 这些人逼迫的未必只是婚姻，他们惯于把一切“不同”逼迫成“相同”。
    6. 结婚，就是两个成年人决定在一起生活，并分享生活。别无其他。不要美化它，也无需丑化它。需要自问的事情包括：
       - 第一，你是否可以允许自己的个性被有限度的减损？婚姻从来不是加法，它是一种融合，这决定了在很多事情上，认可这个人际关系的人必须做出妥协。任何一种成功相处的人际关系都是妥协的结果，婚姻也绝不例外。
       - 第二，你想从婚姻中得到什么？有人想依仗一段婚姻关系的加持得到更体面的物质生活，有人想得到安全感和不孤单。无论前者还是后者，都是对婚姻的误会。无论钱财还是温暖，婚姻都无法为你永久达成。解决你财务自由的只有你自己或者和你具备血缘关系的爹妈，婚姻是很亲密，但它溃散起来，会比你想象的彻底得多。这很残忍，但是真相。而要得到不孤单，连你的爹妈都给不了，只能依靠你自己，那是一种心理调适的有效机制，需要学习面对和接纳现实，既然如此，婚姻怎么可能给你这套内在的系统呢？
       - 第三，你能给予什么？别以为结婚是一个结局，结完万事大吉。它其实是一个开始，要处理一段崭新的人际关系。必备的技能包括，接纳所有光环破碎的可能，懂得处理琐碎的事，必须耐烦，要明白并不因为关系的亲近，在情绪上就一定同步，你高兴地时候，对方或许正好悲伤，你不想说话的时候，对方却正好兴奋不已，学会接纳和处理好常态性的情绪齿轮的错位。

那么，什么时候才适合结婚？当你觉得那是一件小事的时候。婚姻只是一种生活状态的调整，而不是与过去彻底断了联系，又重新植入了崭新的系统。它没有这种颠覆性的东西。你会发现，结婚之后，自己的想法不会产生任何质变，也更不会多长出一个脑袋。所以，你得在长大的过程中，逐渐让自己明白，婚姻真的是一件人生小事，当你不再以一种走向神圣、庄严和自我悲壮化的心态去面对它的时候，才是真正适合走入它的时刻。

成年人的意涵包括，经济独立，精神自立，知道为人处世时的平和，也懂得维护内心的个性，精神内里的边界稳固，有稳定的价值观，懂得享受自由同时明白自律，知道对他人的宽容，对于自己厌恶的人和事，会用合适和体面的方式拒绝；对于热爱的东西，知道自己努力获取而不是要求别人为自己买单。这样的人就不会太差。

婚姻的本质需要一再强调和理解：两个成年人决定共同生活并分享生活。这意味着，懂得尊重对方，**不要试图把对方改变成自己想象中的样子，他是怎样的，结婚后就是怎样的，不要幻想着结婚后他就会改成你想象中的样子**，生活要建立在现实之上，不是建立在虚构之上的。宽容和信任都不再是概念，而是渗透在一件件琐事中的东西。

作为一种有捆绑义务的人际关系，都会有一条必然的、指向平淡的下落曲线。这是结婚之初就要清醒地做好心理准备的另一件事。**永远对一个人保有浓烈的激情是不符合生物进化规律的**。大多数时候，相处，是平缓。对于婚姻关系的戏剧化想象，只会让你断裂在热恋和憎恶之间。那不是生活的真相。

**你要做的是先把自己变成成年人，让自己足够强大，然后和一个同样是成年人、同样内心强大的人一起生活，才会真的快乐**。

婚姻不是必需品，不是生活完满的象征，不是爱情的坟墓，不是温柔的港湾，它就是一种人际关系，一件人生小事。

- 婚姻中掺杂了太多柴米油盐，你越努力感情才能越纯粹，你才能有底气去找找鸡毛蒜皮之后的浪漫，这才是婚姻的潜规则。
- 自证预言的运作机理颇有些令人迷惑：好事很少心想事成，坏事往往无中生有。但这也不是不能解释：或许这与人类大脑中根深蒂固的“恐惧情绪”有关——喜悦会使一个人停下行动去享受喜悦，而恐惧却恰恰相反，会引发一个人马上采取行动去避免危险。事实上，这种出于恐惧的决策几乎总是事与愿违。
自证预言几乎无所不在，它也使因果分析变得更为复杂：**自证预言实现的那一瞬间，一个原本并不存在的原因竟然“无中生有”变成了真正的原因。**

- 兰陵美酒郁金香，玉碗盛来琥珀光。 但使主人能醉客，不知何处是他乡。
-  人事有代谢，往来成古今。 江山留胜迹，我辈复登临。 水落鱼梁浅，天寒梦泽深。 羊公碑尚在，读罢泪沾襟！[孟浩然 《与诸子登岘山》]
- 岭深常得蛟龙在，梧高自有凤凰栖
- 制定“互联网+”行动计划，推动移动互联网、云计算、大数据、物联网等与现代制造业结合，促进电子商务、工业互联网和互联网金融健康发展，引导互联网企业拓展国际市场。
     —— 全国人大会上，李克强在《政府工作报告》中首次提出“互联网+”行动计划。
- 朝阳区有30万仁波切，10万国学大师，10万易经风水大师，10万养生大师。
     ——媒体人刘春的一条微博。网民纷纷补充道：还有50万VC和PE投资人、50万朝阳群众、10万影视从业者、10万公知……
     
- 参与广场舞的许多女性都可以被称作中国历史上“第一代孤独母亲”。
     ——《污名与冲突：时代夹缝中的广场舞》一文作者、香港中文大学人类学硕士生王芊霓认为广场舞大妈们不应该成为笑料。

- One night ,we can build a nouveau |nu:'vəu|, three generations to cultivate an aristocart |ə'rɪstəkræt|

- 事实上，超强记忆法不但对学习无益，而且可能有害。我们所学的知识往往有很强的结构性，正确的学习方法，是根据知识原本的逻辑和原理记忆。而正如我们前面介绍过的，超强记忆法追求的是用想象力另外建立一个联系！这是把已经搭好了的乐高积木先拆开再重新排列，不但多此一举，而且是破坏性的。超强记忆法用得越多，理解度可能就越差。所以练习超强记忆力不是做学问的正途，而是邪道。... [Hui: ？？不是太赞同，谁说记忆和理解是此消彼长的关系？脑子里要有足够多的东西才能彼此连接，融会贯通，看到事物内部的联系才能加强理解能力，这是一个良性循环。作者这里可能专门指代死记硬背，感觉例子太极端。] 知识和信息的区别是什么？**知识不是信息。知识是有价值观基础的、逻辑化、结构化了的信息。**正如爱因斯坦的名言——“所谓教育，就是当一个人把在学校所学全部忘光之后剩下的东西。”

- 一个人可以做成一些事，但是很少能够做成一些大事。我们需要的是主动走出去，大胆寻求帮助，建立起关联，从而实现更大的愿景。在这个过程中，我收获的不仅是更多优秀的人、更多的资源支持，不仅是在企业管理方面的实践和积累，最最重要的是，我的人生边界得以不断扩大，生命变得更加丰富，视野和格局也更加的开阔。正是这些经历为我构建了一个更大、更高的平台，使我能够在更高的层次上去与这个世界对话。

- 快乐的时候，你听的是音乐。难过的时候，你开始懂得了歌词。

- 谁愿意孤苦一生：若不是情到深处难以自禁，又怎么会热血柔肠冷如霜。

- 分工产生效能。这是经济学大厦的第一块基石。互联网给我们看到了很多“逆分工”的假象，但最终的结局一定是更细密的人类分工。国家的竞争力，不是有多少人口，而是有多少参与到分工协作中的人口，能把多少国际人口卷入到自己的分工体系中。

- When you betray somebody else, you also betray yourself.   
[by Isaac Bashevis Singer, 1902年11月21日－1991年7月24日,出生于波兰華沙的美国籍猶太人作家，使用意第緒語寫作，短篇小說家，1978年諾貝爾文學獎得主。作品深刻描绘波兰和美国的犹太人生活。] 

- Do not take life too seriously. You will never get out of it alive.[Elbert Green Hubbard]
- 要知道，活着，钱虽然不是万能的，但是没钱却是万万不能的。金钱虽然无法避免生老病死，但是至少可以提升你的抗风险能力，让你更从容的面对接受磨难并且积极地寻找解决方式。即使最后还是避免不了最坏的结局，至少可以让接受这个结局的过程更加体面和有尊严。

- “粒粒皆辛苦”、“半丝半缕恒念物力维艰”不只写照了一种传统的俭朴观，**它还要求人们以有形的方式来看待财富**。
    
  > <span style="color:blue">Hui:很多我们不经过思索就接受的观点反映的其实是思维认知的局限，我们认知的高度定义了自己思想所在的维度。</span>

- 尤瓦尔.赫拉利在《人类简史》中讲，人善于想象和相信想象出来的东西，因此人统治了地球——钞票就是一种想象。

  > <span style="color:blue">Hui: 我想起乐观的偏见里提到人展望未来的能力，还有黑天鹅中讲到我们对未来的未知。其实这种想象也不总是坏的，正如乐观的偏见里提到的，我们需要这样一副玫瑰色的眼镜来快乐的生活。度，中庸之道。几千年沉淀下来的东西真的不一样。人类作为一种智慧生物的存在本身还是个婴儿。未来充满未知难道不应该么？人类存在本身就是一个极其可能受黑天鹅事件影响的。</span>
  
- 从沉甸甸的落袋为安，到看见屏幕上的一个数字就满足，又是一个过程。美国的大师级小说家唐.德里罗，在他具有浓烈预言色彩的《白噪音》里写了一个画面：

   > 主角杰克去自动取款机上检查银行账户，数字蹦出来，同他脑袋里估计的大体相当，杰克心里立刻涌上“一阵宽慰，一阵感激”，这宽慰和感激来自一个信念：某种深刻的个人价值，被证真和被坐实了。  

当杰克说到“价值”的时候，他不是指一定数额的美元，而是指更宏大的东西：一种拥有的感觉，被一个系统所保佑、所“祝福”的感觉。这种祝福，对消费社会的观察家让.鲍德里亚来说，是一个危险的幻觉，它让人们用看待商品的眼光来看待自己，商品构成了人生活的环境，组成了盘根错节、牢不可破的系统。

- 那么，这个世界最大的不公，就是凭什么不给我足够多的钱去花？凭什么我不能得到祝福？
 
   > ——现在，面对一个令自己沮丧的数字，人会冒出这种无名之火，觉得自己没钱不是因为能力不足，而是游戏中的其他人联手做局，坑了自己。

> <span style="color:blue">Hui: 《身份的焦虑》一书中提到之所以人追逐财富是因为现在社会将财富和能力之间划上无形的等号。而做为自私自大还无知的人类，没有人想承认自己没有能力，我们需要找到另外一个可以解释当前财富不如邻居的理由，于是愚蠢的我们开始退回道德判断。</span>

> 罗胖曰：被困在某个维度里的人，无法理解上一个维度的事情。  
而上一个维度里的人，也无法教会他。  
犹如一个成人和他的孩子，明明彼此亲爱，无奈难以沟通。  
这是这个时代最深的悲哀之一。  
2016年，我心中回响得最多的两句话是——“认识升级”比“知识学习”重要；“回到源头”比“搞清事实”重要。

> <span style="color:blue">Hui: 这就好像神和人类之间的关系，神在高一个维度上试图给我们解释那个维度的事情。这种不同维度的沟通障碍不仅仅是这个时代，而是整个人类历史上衡定不变的问题。</span>

- 积极主动是一种思维方式，其核心就是——遇到问题，先分解问题。所以优秀的人从来不靠“正能量”，而是靠**认知升级**。

